export const DET = new Set([
  "the",
  "a",
  "an",
  "this",
  "that",
  "these",
  "those",
  "some",
  "any",
  "no",
  "every",
  "each",
  "either",
  "neither",
]);

export const PRON = new Set([
  "i",
  "you",
  "he",
  "she",
  "it",
  "we",
  "they",
  "me",
  "him",
  "her",
  "us",
  "them",
  "my",
  "your",
  "his",
  "its",
  "our",
  "their",
  "mine",
  "yours",
  "hers",
  "ours",
  "theirs",
  "myself",
  "yourself",
  "himself",
  "herself",
  "itself",
  "ourselves",
  "themselves",
  "who",
  "whom",
  "whose",
  "what",
  "which",
  "this",
  "that",
  "these",
  "those",
]);

export const ADP = new Set([
  "in",
  "on",
  "at",
  "to",
  "for",
  "with",
  "from",
  "of",
  "about",
  "into",
  "onto",
  "upon",
  "over",
  "under",
  "between",
  "among",
  "through",
  "during",
  "before",
  "after",
  "without",
  "within",
  "against",
  "toward",
  "towards",
  "across",
  "behind",
  "beyond",
  "despite",
  "except",
  "plus",
  "versus",
  "via",
]);

export const PARTICLES = new Set([
  "up",
  "out",
  "off",
  "down",
  "in",
  "on",
  "away",
  "back",
  "over",
  "through",
  "around",
  "along",
  "aside",
  "forward",
  "together",
  "apart",
]);

export const AUX = new Set([
  "be",
  "am",
  "is",
  "are",
  "was",
  "were",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "doing",
  "will",
  "would",
  "shall",
  "should",
  "can",
  "could",
  "may",
  "might",
  "must",
  "need",
  "dare",
  "ought",
]);

export const CCONJ = new Set(["and", "or", "but", "nor", "yet", "so"]);

export const SCONJ = new Set([
  "if",
  "because",
  "although",
  "though",
  "while",
  "when",
  "whenever",
  "unless",
  "until",
  "since",
  "after",
  "before",
  "whether",
  "once",
  "whereas",
]);

export const ADV = new Set([
  "not",
  "n't",
  "never",
  "always",
  "already",
  "still",
  "just",
  "also",
  "too",
  "very",
  "really",
  "quite",
  "rather",
  "almost",
  "even",
  "only",
  "here",
  "there",
  "now",
  "then",
  "so",
  "well",
  "back",
  "away",
  "again",
  "together",
  "apart",
]);

/** lemma -> irregular forms (past / participle / 3sg extras) */
export const IRREGULAR_VERBS: Record<string, string[]> = {
  be: ["am", "is", "are", "was", "were", "been", "being"],
  have: ["has", "had", "having"],
  do: ["does", "did", "done", "doing"],
  go: ["goes", "went", "gone", "going"],
  get: ["gets", "got", "gotten", "getting"],
  make: ["makes", "made", "making"],
  know: ["knows", "knew", "known", "knowing"],
  think: ["thinks", "thought", "thinking"],
  take: ["takes", "took", "taken", "taking"],
  see: ["sees", "saw", "seen", "seeing"],
  come: ["comes", "came", "coming"],
  want: ["wants", "wanted", "wanting"],
  look: ["looks", "looked", "looking"],
  use: ["uses", "used", "using"],
  find: ["finds", "found", "finding"],
  give: ["gives", "gave", "given", "giving"],
  tell: ["tells", "told", "telling"],
  work: ["works", "worked", "working"],
  call: ["calls", "called", "calling"],
  try: ["tries", "tried", "trying"],
  ask: ["asks", "asked", "asking"],
  need: ["needs", "needed", "needing"],
  feel: ["feels", "felt", "feeling"],
  become: ["becomes", "became", "becoming"],
  leave: ["leaves", "left", "leaving"],
  put: ["puts", "putting"],
  mean: ["means", "meant", "meaning"],
  keep: ["keeps", "kept", "keeping"],
  let: ["lets", "letting"],
  begin: ["begins", "began", "begun", "beginning"],
  seem: ["seems", "seemed", "seeming"],
  help: ["helps", "helped", "helping"],
  show: ["shows", "showed", "shown", "showing"],
  hear: ["hears", "heard", "hearing"],
  play: ["plays", "played", "playing"],
  run: ["runs", "ran", "running"],
  move: ["moves", "moved", "moving"],
  live: ["lives", "lived", "living"],
  believe: ["believes", "believed", "believing"],
  bring: ["brings", "brought", "bringing"],
  happen: ["happens", "happened", "happening"],
  write: ["writes", "wrote", "written", "writing"],
  sit: ["sits", "sat", "sitting"],
  stand: ["stands", "stood", "standing"],
  lose: ["loses", "lost", "losing"],
  pay: ["pays", "paid", "paying"],
  meet: ["meets", "met", "meeting"],
  include: ["includes", "included", "including"],
  continue: ["continues", "continued", "continuing"],
  set: ["sets", "setting"],
  learn: ["learns", "learned", "learnt", "learning"],
  change: ["changes", "changed", "changing"],
  lead: ["leads", "led", "leading"],
  understand: ["understands", "understood", "understanding"],
  watch: ["watches", "watched", "watching"],
  follow: ["follows", "followed", "following"],
  stop: ["stops", "stopped", "stopping"],
  create: ["creates", "created", "creating"],
  speak: ["speaks", "spoke", "spoken", "speaking"],
  read: ["reads", "reading"],
  spend: ["spends", "spent", "spending"],
  grow: ["grows", "grew", "grown", "growing"],
  open: ["opens", "opened", "opening"],
  walk: ["walks", "walked", "walking"],
  win: ["wins", "won", "winning"],
  teach: ["teaches", "taught", "teaching"],
  offer: ["offers", "offered", "offering"],
  remember: ["remembers", "remembered", "remembering"],
  love: ["loves", "loved", "loving"],
  consider: ["considers", "considered", "considering"],
  appear: ["appears", "appeared", "appearing"],
  buy: ["buys", "bought", "buying"],
  wait: ["waits", "waited", "waiting"],
  serve: ["serves", "served", "serving"],
  die: ["dies", "died", "dying"],
  send: ["sends", "sent", "sending"],
  build: ["builds", "built", "building"],
  stay: ["stays", "stayed", "staying"],
  fall: ["falls", "fell", "fallen", "falling"],
  cut: ["cuts", "cutting"],
  reach: ["reaches", "reached", "reaching"],
  kill: ["kills", "killed", "killing"],
  raise: ["raises", "raised", "raising"],
  pass: ["passes", "passed", "passing"],
  sell: ["sells", "sold", "selling"],
  decide: ["decides", "decided", "deciding"],
  return: ["returns", "returned", "returning"],
  explain: ["explains", "explained", "explaining"],
  hope: ["hopes", "hoped", "hoping"],
  develop: ["develops", "developed", "developing"],
  carry: ["carries", "carried", "carrying"],
  break: ["breaks", "broke", "broken", "breaking"],
  receive: ["receives", "received", "receiving"],
  agree: ["agrees", "agreed", "agreeing"],
  support: ["supports", "supported", "supporting"],
  hit: ["hits", "hitting"],
  produce: ["produces", "produced", "producing"],
  eat: ["eats", "ate", "eaten", "eating"],
  cover: ["covers", "covered", "covering"],
  catch: ["catches", "caught", "catching"],
  draw: ["draws", "drew", "drawn", "drawing"],
  choose: ["chooses", "chose", "chosen", "choosing"],
  cause: ["causes", "caused", "causing"],
  point: ["points", "pointed", "pointing"],
  sleep: ["sleeps", "slept", "sleeping"],
  throw: ["throws", "threw", "thrown", "throwing"],
  wear: ["wears", "wore", "worn", "wearing"],
  forget: ["forgets", "forgot", "forgotten", "forgetting"],
  hide: ["hides", "hid", "hidden", "hiding"],
  lend: ["lends", "lent", "lending"],
  ring: ["rings", "rang", "rung", "ringing"],
  shut: ["shuts", "shutting"],
  swim: ["swims", "swam", "swum", "swimming"],
  wake: ["wakes", "woke", "woken", "waking"],
  hold: ["holds", "held", "holding"],
  turf: ["turfs", "turfed", "turfing"],
  end: ["ends", "ended", "ending"],
};

const FORM_TO_LEMMA = new Map<string, string>();
for (const [lemma, forms] of Object.entries(IRREGULAR_VERBS)) {
  FORM_TO_LEMMA.set(lemma, lemma);
  for (const form of forms) FORM_TO_LEMMA.set(form, lemma);
}

export function verbLemma(word: string): string | null {
  const lower = word.toLowerCase().replace(/n't$/, "").replace(/'d$/, "").replace(/'ve$/, "");
  return FORM_TO_LEMMA.get(lower) ?? null;
}

export function isIrregularVerbForm(word: string): boolean {
  const lower = word.toLowerCase().replace(/n't$/, "");
  const lemma = FORM_TO_LEMMA.get(lower);
  if (!lemma) return false;
  if (lower === lemma) return lemma === "be" || lemma === "have" || lemma === "do";
  const regularPast = `${lemma}ed`;
  const regularIng = `${lemma}ing`;
  const doubled = `${lemma}${lemma.at(-1)}ed`;
  if (lower === regularPast || lower === regularIng || lower === doubled) return false;
  if (lemma.endsWith("e") && (lower === `${lemma}d` || lower === `${lemma.slice(0, -1)}ing`)) {
    return false;
  }
  if (lower === `${lemma}s` || lower === `${lemma}es`) return lemma === "be" || lemma === "have" || lemma === "do" || lemma === "go";
  return true;
}
