export const APP_LOCALE_STORAGE_KEY = "appUiLocale";

export const copy = {
  ko: {
    appTitle: "AI 영어 교정 채팅",
    chatMode: "영어로 대화",
    askExpression: "표현 알아보기",
    inputPlaceholder: "예: '나는 오늘 운동을 했다' → 영어로 직접 써보세요",
    expressionPlaceholder: "한국어로 말하고 싶은 내용을 입력하세요",
    send: "전송",
    translate: "번역",
    listen: "듣기",
    corrected: "교정 문장",
    highlighted: "오류 표시",
    natural: "자연스러운 표현",
    explanation: "설명",
    example: "예문",
    useThisExpression: "이 표현으로 말하기",
    save: "📘 내 교재에 추가",
    saved: "✔ 추가됨",
    savedToBookToast: "✨ 내 영어 교재에 저장됨 (총 {count}개)",
    learningBookNav: "내 영어 교재",
    learningBookTitle: "내 영어 교재",
    learningEmpty:
      "아직 내 영어 교재가 비어 있어요.\n영어로 문장을 써보고, 마음에 드는 교정을 저장해보세요.",
    learningSearchPlaceholder: "내 표현 검색하기",
    learningSearchNoResults: "검색 결과가 없어요.",
    learningFilterEmpty: "이 조건에 맞는 카드가 없어요.",
    filterAll: "전체",
    filterNew: "새 문장",
    filterPracticing: "연습 중",
    filterUsable: "익숙한 표현",
    cardShowDetails: "자세히 보기",
    cardHideDetails: "간단히 보기",
    reviewPracticingCta: "연습 중인 표현 복습하기",
    reviewNewCta: "새 문장 복습하기",
    reviewTodayEmpty: "복습할 표현이 없어요. 새 문장을 저장해보세요.",
    learningBackToChat: "← 채팅으로",
    dashboardSavedToday: "오늘 저장",
    dashboardTotalCards: "총 카드",
    dashboardTotalCardsSubtle: "총 {count}개 표현",
    dashboardPracticing: "연습 중",
    dashboardUsable: "익숙한 표현",
    cardMySentence: "내가 실제로 쓴 문장",
    cardBetterExpression: "더 좋은 표현",
    cardMoreNatural: "더 자연스럽게",
    cardPoint: "포인트",
    practiceAgain: "🔁 다시 연습",
    deleteFromBook: "🗑 삭제",
    reviewFrontHint: "내가 실제로 썼던 문장",
    reviewReveal: "정답 보기",
    reviewForgot: "아직 어려움",
    reviewVague: "애매함",
    reviewFamiliar: "익숙함",
    reviewConfidencePrompt: "이 문장을 다음에 자연스럽게 쓸 수 있을 것 같나요?",
    progressStatusNew: "🆕 새 문장",
    progressStatusPracticing: "🔁 연습 중",
    progressStatusUsable: "✅ 익숙한 표현",
    progressSavedToday: "오늘 저장",
    progressNotReviewed: "아직 복습 전",
    progressReviewCount: "복습 {count}회",
    progressLastReviewedToday: "마지막 복습 오늘",
    progressLastReviewedYesterday: "마지막 복습 어제",
    progressLastReviewedDays: "마지막 복습 {count}일 전",
    archive: "아카이브",
    archiveEmpty: "저장된 표현이 없습니다.",
    savedItemsTab: "저장한 표현",
    sessionsTab: "대화 기록",
    sessionsEmpty: "저장된 대화 기록이 없습니다.",
    openSession: "열어보기",
    clearSessions: "대화 기록 초기화",
    freeTraining: "자유 연습",
    messagesUsed: "사용 메시지",
    resetArchive: "아카이브 초기화",
    closeArchive: "닫기",
    continuePractice: "이어서 연습하기",
    comeBackTomorrow: "내일 다시 하기",
    trainingDoneTitle: "오늘의 영어 훈련 완료 👍",
    trainingDoneBody: "내일 다시 이어서 연습해보세요",
    trainingDoneHint: "계속 연습하고 싶다면 이어서 대화할 수 있어요",
    delete: "삭제",
    reuse: "다시 쓰기",
    translating: "번역 중...",
    translation: "번역",
    translateFailed: "번역에 실패했어요. 다시 시도해 주세요.",
    dailyLimitReached:
      "오늘의 메시지 한도에 도달했어요. 내일 다시 시도해 주세요.",
    expressionHelperTitle: "💡 이렇게 말할 수 있어요",
    correctionTitle: "교정",
    noCorrectionNeeded: "수정할 필요가 없습니다.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "오늘의 영어 훈련을 완료했어요 👍",
    startNewSession: "새 대화 시작",
    endSession: "세션 종료",
    languageKorean: "한국어",
    languageEnglish: "English",
    languageSpanish: "Español",
  },
  en: {
    appTitle: "AI English Correction Chat",
    chatMode: "Chat in English",
    askExpression: "Ask expression",
    inputPlaceholder: "Try writing in English",
    expressionPlaceholder: "Type what you want to say in Korean",
    send: "Send",
    translate: "Translate",
    listen: "Listen",
    corrected: "Corrected",
    highlighted: "Highlighted mistakes",
    natural: "Natural",
    explanation: "Explanation",
    example: "Example",
    useThisExpression: "Say with this expression",
    save: "📘 Add to My English Book",
    saved: "✔ Added",
    savedToBookToast: "✨ Saved to My English Book ({count} total)",
    learningBookNav: "My English Book",
    learningBookTitle: "My English Book",
    learningEmpty:
      "Your English Book is empty.\nWrite a sentence in English and save useful corrections.",
    learningSearchPlaceholder: "Search my expressions",
    learningSearchNoResults: "No matching cards found.",
    learningFilterEmpty: "No cards match this filter.",
    filterAll: "All",
    filterNew: "New",
    filterPracticing: "Practicing",
    filterUsable: "Familiar",
    cardShowDetails: "Show details",
    cardHideDetails: "Show less",
    reviewPracticingCta: "Review Practicing Expressions",
    reviewNewCta: "Review New Expressions",
    reviewTodayEmpty: "Nothing to review yet — save a few sentences first.",
    learningBackToChat: "← Back to chat",
    dashboardSavedToday: "Saved Today",
    dashboardTotalCards: "Total cards",
    dashboardTotalCardsSubtle: "{count} total expressions",
    dashboardPracticing: "Practicing",
    dashboardUsable: "Familiar",
    cardMySentence: "What I actually wrote",
    cardBetterExpression: "Better expression",
    cardMoreNatural: "More natural",
    cardPoint: "Key point",
    practiceAgain: "🔁 Practice again",
    deleteFromBook: "🗑 Remove",
    reviewFrontHint: "The sentence you wrote",
    reviewReveal: "Show answer",
    reviewForgot: "Still Hard",
    reviewVague: "Not Sure",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Do you think you could naturally use this sentence next time?",
    progressStatusNew: "🆕 New",
    progressStatusPracticing: "🔁 Practicing",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Saved today",
    progressNotReviewed: "Not reviewed yet",
    progressReviewCount: "{count} reviews",
    progressLastReviewedToday: "last reviewed today",
    progressLastReviewedYesterday: "last reviewed yesterday",
    progressLastReviewedDays: "last reviewed {count} days ago",
    archive: "Archive",
    archiveEmpty: "No saved items yet.",
    savedItemsTab: "Saved expressions",
    sessionsTab: "Conversation history",
    sessionsEmpty: "No saved conversation sessions.",
    openSession: "Open",
    clearSessions: "Clear conversation history",
    freeTraining: "Free training",
    messagesUsed: "Messages used",
    resetArchive: "Reset archive",
    closeArchive: "Close",
    continuePractice: "Continue Practice",
    comeBackTomorrow: "Come back tomorrow",
    trainingDoneTitle: "You've completed today's training 👍",
    trainingDoneBody: "Come back tomorrow to continue.",
    trainingDoneHint: "If you want, you can keep practicing now.",
    delete: "Delete",
    reuse: "Reuse",
    translating: "Translating...",
    translation: "Translation",
    translateFailed: "Translation failed. Please try again.",
    dailyLimitReached: "You reached today's message limit. Please come back tomorrow.",
    expressionHelperTitle: "💡 You can say it like this",
    correctionTitle: "Correction",
    noCorrectionNeeded: "No changes needed.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Today's practice is complete 🎯",
    startNewSession: "Start New Session",
    endSession: "End Session",
    languageKorean: "Korean",
    languageEnglish: "English",
    languageSpanish: "Spanish",
  },
  es: {
    appTitle: "Chat de correccion de ingles con IA",
    chatMode: "Hablar en ingles",
    askExpression: "Preguntar expresion",
    inputPlaceholder: "Escribe en ingles",
    expressionPlaceholder: "Escribe en coreano lo que quieres decir",
    send: "Enviar",
    translate: "Traducir",
    listen: "Escuchar",
    corrected: "Correccion",
    highlighted: "Errores marcados",
    natural: "Expresion mas natural",
    explanation: "Explicacion",
    example: "Ejemplo",
    useThisExpression: "Hablar con esta expresion",
    save: "📘 Anadir a mi libro",
    saved: "✔ Anadido",
    savedToBookToast: "✨ Guardado en mi libro ({count} en total)",
    learningBookNav: "Mi libro de ingles",
    learningBookTitle: "Mi libro de ingles",
    learningEmpty:
      "Tu libro esta vacio.\nEscribe en ingles y guarda correcciones utiles con 📘.",
    learningSearchPlaceholder: "Buscar en mi libro",
    learningSearchNoResults: "No hay resultados.",
    learningFilterEmpty: "No hay tarjetas con este filtro.",
    filterAll: "Todo",
    filterNew: "Nuevas",
    filterPracticing: "Practicando",
    filterUsable: "Familiares",
    cardShowDetails: "Ver detalles",
    cardHideDetails: "Menos",
    reviewPracticingCta: "Repasar expresiones en practica",
    reviewNewCta: "Repasar expresiones nuevas",
    reviewTodayEmpty: "Nada para repasar todavia. Guarda algunas frases primero.",
    learningBackToChat: "← Volver al chat",
    dashboardSavedToday: "Guardadas hoy",
    dashboardTotalCards: "Tarjetas",
    dashboardTotalCardsSubtle: "{count} expresiones en total",
    dashboardPracticing: "Practicando",
    dashboardUsable: "Familiares",
    cardMySentence: "Lo que yo escribi",
    cardBetterExpression: "Mejor expresion",
    cardMoreNatural: "Mas natural",
    cardPoint: "Punto clave",
    practiceAgain: "🔁 Repasar",
    deleteFromBook: "🗑 Borrar",
    reviewFrontHint: "La frase que escribiste",
    reviewReveal: "Ver respuesta",
    reviewForgot: "Aun dificil",
    reviewVague: "Dudoso",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Crees que podrias usar esta frase de forma natural la proxima vez?",
    progressStatusNew: "🆕 Nueva",
    progressStatusPracticing: "🔁 Practicando",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Guardada hoy",
    progressNotReviewed: "Sin repasar",
    progressReviewCount: "{count} repasos",
    progressLastReviewedToday: "ultimo repaso hoy",
    progressLastReviewedYesterday: "ultimo repaso ayer",
    progressLastReviewedDays: "ultimo repaso hace {count} dias",
    archive: "Archivo",
    archiveEmpty: "No hay elementos guardados.",
    savedItemsTab: "Expresiones guardadas",
    sessionsTab: "Historial de conversaciones",
    sessionsEmpty: "No hay sesiones guardadas.",
    openSession: "Abrir",
    clearSessions: "Borrar historial",
    freeTraining: "Practica libre",
    messagesUsed: "Mensajes usados",
    resetArchive: "Reiniciar archivo",
    closeArchive: "Cerrar",
    continuePractice: "Continuar practicando",
    comeBackTomorrow: "Volver manana",
    trainingDoneTitle: "Has completado el entrenamiento de hoy 👍",
    trainingDoneBody: "Vuelve manana para continuar.",
    trainingDoneHint: "Si quieres, puedes seguir practicando ahora.",
    delete: "Eliminar",
    reuse: "Reutilizar",
    translating: "Traduciendo...",
    translation: "Traduccion",
    translateFailed: "No se pudo traducir. Intentalo de nuevo.",
    dailyLimitReached: "Llegaste al limite de mensajes de hoy. Vuelve manana.",
    expressionHelperTitle: "💡 Puedes decirlo asi",
    correctionTitle: "Correccion",
    noCorrectionNeeded: "No hace falta corregir.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Completaste la practica de hoy 🎯",
    startNewSession: "Start New Session",
    endSession: "Finalizar sesion",
    languageKorean: "Coreano",
    languageEnglish: "Ingles",
    languageSpanish: "Espanol",
  },
} as const;

export type Locale = keyof typeof copy;
export type UICopy = (typeof copy)[Locale];
