import generatedLocales from "@/lib/locales/generated.json";

export const APP_LOCALE_STORAGE_KEY = "appUiLocale";

export const LOCALE_OPTIONS = [
  { key: "ko", label: "한국어" },
  { key: "en", label: "English" },
  { key: "es", label: "Español" },
  { key: "ja", label: "日本語" },
  { key: "zh", label: "中文" },
  { key: "vi", label: "Tiếng Việt" },
  { key: "fr", label: "Français" },
  { key: "pt", label: "Português" },
  { key: "id", label: "Bahasa Indonesia" },
] as const;

export const copy = {
  ko: {
    appTitle: "영어 교정 채팅",
    chatEmptyHint:
      "예: \"I had a really busy day today.\"\n내 말로 영어 문장을 직접 써보세요",
    chatMode: "영어로 대화",
    askExpression: "표현 알아보기",
    inputPlaceholder: "영어로 직접 문장을 써보세요 (예: I went to the gym today.)",
    expressionPlaceholder: "한국어로 말하고 싶은 내용을 입력하세요",
    send: "전송",
    chatStartCta: "먼저 말하기",
    chatStartFailed: "대화를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
    translate: "번역",
    listen: "듣기",
    corrected: "교정 문장",
    highlighted: "오류 표시",
    natural: "또 다른 표현",
    correctionBlockTitle: "문법 교정",
    correctionMyLine: "내가 쓴 표현",
    correctionTryThis: "이렇게 바꿔보세요",
    explanation: "설명",
    example: "예문",
    useThisExpression: "이 표현 써보기",
    save: "표현 저장",
    saved: "✔ 저장됨",
    savedToBookToast: "내 영어 교재에 저장했어요 ({count}개)\n나중에 다시 복습할 수 있어요",
    learningBookNav: "내 영어 교재",
    learningBookTitle: "내 영어 교재",
    learningEmpty:
      "아직 저장한 표현이 없어요\n\n채팅 중 좋은 표현을 저장하면\n나만의 영어 교재가 만들어집니다",
    learningSearchPlaceholder: "내 표현 검색하기",
    learningSearchNoResults: "검색 결과가 없어요.",
    learningFilterEmpty: "이 조건에 맞는 카드가 없어요.",
    filterAll: "전체",
    filterNew: "새 문장",
    filterPracticing: "연습 중",
    filterUsable: "익숙한 표현",
    cardShowDetails: "자세히 보기",
    cardHideDetails: "간단히 보기",
    reviewPracticingCta: "연습 중인 표현 복습하기",
    reviewNewCta: "새 문장 복습하기",
    reviewTodayEmpty: "아직 복습할 표현이 없어요. 채팅에서 표현을 저장해 보세요.",
    learningBackToChat: "← 채팅으로",
    dashboardSavedToday: "오늘 저장",
    dashboardTotalCards: "총 카드",
    dashboardTotalCardsSubtle: "총 {count}개 표현",
    dashboardPracticing: "연습 중",
    dashboardUsable: "익숙한 표현",
    cardMySentence: "내가 실제로 쓴 문장",
    cardBetterExpression: "더 좋은 표현",
    cardMoreNatural: "또 다른 표현",
    cardPoint: "포인트",
    practiceAgain: "🔁 다시 연습",
    deleteFromBook: "🗑 삭제",
    reviewFrontHint: "내가 실제로 썼던 문장",
    reviewReveal: "정답 보기",
    reviewForgot: "아직 어려움",
    reviewVague: "애매함",
    reviewFamiliar: "익숙함",
    reviewConfidencePrompt: "이 문장을 다음에 자연스럽게 쓸 수 있을 것 같나요?",
    progressStatusNew: "🆕 새 문장",
    progressStatusPracticing: "🔁 연습 중",
    progressStatusUsable: "✅ 익숙한 표현",
    progressSavedToday: "오늘 저장",
    progressNotReviewed: "아직 복습 전",
    progressReviewCount: "복습 {count}회",
    progressLastReviewedToday: "마지막 복습 오늘",
    progressLastReviewedYesterday: "마지막 복습 어제",
    progressLastReviewedDays: "마지막 복습 {count}일 전",
    archive: "리포트",
    archiveEmpty: "저장된 표현이 없습니다.",
    savedItemsTab: "저장한 표현",
    sessionsTab: "학습 리포트",
    sessionsEmpty:
      "아직 완료된 학습 리포트가 없습니다.\n세션을 종료하면 리포트가 생성됩니다.",
    openSession: "리포트 보기",
    clearSessions: "리포트 전체 삭제",
    freeTraining: "자유 연습",
    messagesUsed: "사용 메시지",
    resetArchive: "아카이브 초기화",
    closeArchive: "닫기",
    reportMenuTitle: "리포트",
    reportListTitle: "완료된 학습",
    reportListEmpty:
      "아직 완료된 학습 리포트가 없습니다.\n대화를 끝내고 세션을 종료하면 리포트가 만들어져요.",
    reportClearAll: "전체 삭제",
    reportViewCta: "리포트 보기",
    reportTurnCount: "{count}개 대화",
    reportScoreLabel: "{score}점",
    reportDetailBadge: "세션 학습 리포트",
    reportTodayLearning: "오늘의 학습",
    reportStatExpressions: "표현",
    reportStatCorrections: "교정",
    reportStatTakeaways: "가져갈 표현",
    reportTimelineTitle: "대화 돌아보기",
    reportSummaryTitle: "대화 회고",
    reportScoreTitle: "이번 세션 점수",
    reportScoreInsufficient:
      "점수를 계산하기에는 대화량이 부족해요. 조금 더 대화한 뒤 세션을 종료해 보세요.",
    reportScoreNativeHint:
      "자연스러움 25점은 원어민, 0점은 영어를 거의 모르는 수준이에요. 문법은 이 점수에 넣지 않아요.",
    reportScoreBreakdownTitle: "점수 구성",
    reportScoreFactorAccuracy: "정확도",
    reportScoreFactorNaturalness: "자연스러움",
    reportScoreFactorFluency: "말하기 길이",
    reportScoreFactorSpoken: "구어 표현",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "잘한 점",
    reportImprovementsTitle: "개선할 점",
    reportMyExpression: "내 표현",
    reportBetterExpression: "더 자연스럽게",
    reportLearningTitle: "오늘 가져갈 표현",
    reportShowTranscript: "전체 대화 보기",
    reportHideTranscript: "전체 대화 숨기기",
    reportTranscriptReadonly:
      "읽기 전용입니다. 이 기록에서는 대화를 이어갈 수 없어요.",
    reportTranscriptYou: "나",
    reportTranscriptAi: "AI",
    reportReviewTitle: "대화 돌아보기",
    reportReviewHint: "그때 채팅 화면을 그대로 다시 볼 수 있어요.",
    reportReviewEmpty: "이 세션에 저장된 대화가 없어요.",
    reportChatCaptureLabel: "채팅 다시보기",
    reportLightCorrectionLabel: "자연스럽게",
    reportReviewDoneTitle: "대화를 모두 돌아봤어요.",
    reportReviewDoneBody: "이제 오늘 사용한 영어를 자세히 살펴볼까요?",
    reportGotoAnalysis: "상세 분석 보기",
    reportAnalysisTitle: "상세 분석",
    reportAnalysisHint: "이번 대화에서 실제로 쓴 영어를 근거로, 잘 쓴 표현과 더 자연스럽게 이어갈 방법을 살펴봐요.",
    reportAnalysisEmpty:
      "아직 대화가 짧아서 사용 습관을 판단하기 어려워요. 조금 더 대화하면 패턴을 분석할 수 있어요.",
    reportAnalysisStrengthsTitle: "잘하고 있어요",
    reportAnalysisImprovementsTitle: "개선해 보세요",
    reportAnalysisHabitsTitle: "대화 습관",
    reportAnalysisNextGoalTitle: "다음 대화 목표",
    reportAnalysisGenerating: "대화를 분석하는 중...",
    reportAnalysisCategoryNatural: "자연스러운 표현",
    reportAnalysisCategoryNuance: "뉘앙스",
    reportAnalysisCategoryWordChoice: "단어 선택",
    reportAnalysisCategoryTone: "말투",
    reportAnalysisCategoryFlow: "대화 흐름",
    reportAnalysisCategoryVariety: "표현 다양성",
    reportAnalysisCategoryConnection: "연결",
    reportAnalysisCategoryExpression: "생각 표현",
    reportAnalysisCategoryConversation: "대화 전략",
    reportAnalysisCategoryImprovement: "개선 포인트",
    reportAnalysisStrengthLabel: "잘한 표현",
    reportAnalysisWhyGood: "왜 좋았나요?",
    reportAnalysisCorrected: "교정",
    reportAnalysisWhy: "왜?",
    reportAnalysisAlternative: "다른 방식으로 말하면",
    reportAnalysisExample: "예문",
    reportTakeawaysTitle: "오늘 가져갈 것",
    reportTakeawaysHint: "오늘 이것만 기억해도 충분해요.",
    reportTakeawaysEmpty: "가져갈 핵심 표현이 아직 없어요.",
    reportCreatedToast: "학습 리포트가 저장됐어요",
    quizReadyToast: "복습 자료가 준비됐어요. 복습 탭에서 확인해 보세요.",
    reportSessionsTab: "세션 리포트",
    reportMonthlyTab: "월별 리포트",
    reportBack: "← 리포트",
    monthlyOpenFull: "월별 리포트 보기",
    homeTabChat: "채팅",
    homeTabSessions: "세션",
    homeTabMonthly: "월별",
    homeTabReports: "리포트",
    homeTabSaved: "표현",
    homeTabVocab: "단어장",
    homeTabQuiz: "복습",
    quizTodayTitle: "오늘의 복습",
    quizTodaySubtitle: "최근 대화에서 헷갈렸던 내용을 다시 연습해요.",
    quizMissionPrompt: "어제 배운 내용을\n2분만 복습해볼까요?",
    quizTodayCountLabel: "오늘의 문제",
    quizRecentReviewTitle: "최근 복습",
    quizTodayCardTitle: "오늘의 복습",
    quizTodayMeta: "{count}문제 · 약 {minutes}분",
    quizCompositionGrammar: "문법 {count}",
    quizCompositionVocab: "단어 {count}",
    quizCompositionExpression: "표현 {count}",
    quizStartCta: "복습 시작",
    quizContinueCta: "이어서 풀기",
    quizReviewAgainCta: "새 문제로 다시 풀기",
    quizCreateNewCta: "퀴즈 새로 만들기",
    quizTodayFinished: "오늘 이 학습 복습은 끝났어요. 내일 다시 만나요.",
    quizGenerating: "문제 만드는 중...",
    quizGenerateFailed: "문제를 만들지 못했어요. 잠시 후 다시 시도해 주세요.",
    quizLoading: "불러오는 중...",
    quizEmptyTitle: "아직 복습할 내용이 없어요.",
    quizEmptyBody:
      "채팅 후 리포트를 만들면\n문법과 단어 복습 자료가 바로 준비돼요.",
    quizEmptyCta: "영어로 대화하기",
    reviewFilterAll: "전체",
    reviewFilterGrammar: "문법",
    reviewFilterVocab: "단어",
    reviewMySentence: "내가 쓴 문장",
    reviewBetterSentence: "이렇게 바꿔보세요",
    reviewExamples: "예문",
    reviewSimilar: "비슷한 단어",
    reviewRefresh: "자료 다시 만들기",
    reviewGenerating: "복습 자료 만드는 중...",
    reviewGenerateFailed: "복습 자료를 만들지 못했어요.",
    reviewEmptyBody:
      "채팅에서 단어를 저장하고 리포트를 만들면\n틀린 문법과 저장한 단어로 복습 자료가 생겨요.",
    reviewCompleteCta: "복습 완료",
    reviewResetCta: "초기화",
    reviewSectionFallback: "복습 {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ 정답이에요",
    quizIncorrect: "다시 확인해볼까요?",
    quizNext: "다음 문제",
    quizSeeResult: "결과 보기",
    quizCompleteTitle: "오늘 복습 완료 ✓",
    quizCompleteScore: "{total}문제 중 {correct}문제를 맞혔어요.",
    quizRememberedTitle: "잘 기억하고 있어요",
    quizReviewAgainTitle: "다시 볼 내용",
    quizBackHome: "복습 홈으로",
    quizAlreadyDone: "오늘 복습을 이미 완료했어요.",
    quizTypeGrammar: "문법",
    quizTypeVocabulary: "단어",
    quizTypeExpression: "표현",
    homeBack: "← 홈",
    homeHubBadge: "홈",
    homeHubSubtitle: "오늘 연습할 곳을 골라 보세요.",
    homeOpenCta: "열기",
    homeDestChatDesc: "영어로 대화하고 교정받으며 연습합니다.",
    homeDestSessionsDesc: "완료한 세션의 학습 리포트를 돌아봅니다.",
    homeDestMonthlyDesc: "한 달 동안의 점수 성장과 학습을 확인합니다.",
    homeDestSavedDesc: "채팅에서 저장한 표현을 복습합니다.",
    homeDestVocabDesc: "모국어로 검색해 영어 단어를 저장합니다.",
    vocabTitle: "단어장",
    vocabFilterAll: "전체",
    vocabFilterWords: "단어",
    vocabFilterPhrases: "표현",
    vocabStatusLearning: "학습 중",
    vocabStatusFamiliar: "익숙함",
    vocabQueryHint: "UI 언어로 검색하면 영어 단어가 표시됩니다.",
    vocabSearchPlaceholder: "모국어로 단어 검색",
    vocabSearchCta: "검색",
    vocabSearching: "검색 중...",
    vocabResultsTitle: "검색 결과",
    vocabSavedTitle: "저장한 단어",
    vocabEmpty: "아직 저장한 단어가 없어요.\n위에서 검색해 추가해 보세요.",
    vocabHideGloss: "뜻 숨김",
    vocabShuffle: "랜덤 정렬",
    vocabRevealGloss: "눌러서 뜻 보기",
    vocabNoResults: "검색 결과가 없어요.",
    vocabSave: "저장",
    vocabSaved: "저장됨",
    vocabDelete: "삭제",
    vocabSavedToast: "단어장에 저장했어요",
    vocabSearchFailed: "검색에 실패했어요. 다시 시도해 주세요.",
    vocabSaveFromChat: "단어 확인",
    vocabPickTitle: "단어 선택",
    vocabPickHint: "채팅에 나온 단어를 눌러 단어장에 저장하세요.",
    vocabPickModeHint: "노란 표시는 단어, 하늘색은 숙어·복합어예요. 누르면 뜻을 볼 수 있어요.",
    vocabPickEmpty: "저장할 영어 단어가 아직 없어요. 먼저 대화를 나눠 보세요.",
    vocabPickCancel: "닫기",
    vocabPickSave: "{count}개 저장",
    vocabPickSaving: "저장 중...",
    vocabPickDone: "선택 완료",
    vocabPickSavedToast: "단어를 저장했어요",
    vocabPickNoneToast: "저장할 단어가 없어요",
    vocabPickFailed: "단어 저장에 실패했어요. 다시 시도해 주세요.",
    vocabPreviewLoading: "뜻을 불러오는 중...",
    vocabPreviewSave: "저장",
    vocabPreviewClose: "닫기",
    chatHistoryTitle: "채팅 기록",
    chatHistoryListTitle: "이전 대화",
    chatHistoryEmpty:
      "아직 저장된 채팅이 없어요.\n대화를 시작하면 여기에 기록이 쌓여요.",
    chatHistoryContinue: "이어서 대화",
    chatHistoryNew: "새 대화 시작",
    chatHistoryClear: "기록 전체 삭제",
    chatHistoryCurrent: "현재",
    chatHistoryHasReport: "리포트 있음",
    createReport: "리포트 생성",
    chatCardsOn: "카드 켜짐",
    chatCardsOff: "카드 꺼짐",
    chatCardsLabel: "카드",
    toggleLegendOn: "켜짐",
    toggleLegendOff: "꺼짐",
    sessionSavedToHistoryToast: "채팅 기록에 저장했어요",
    reportCreateEmptyToast: "리포트를 만들 대화가 아직 없어요",
    reportCreateConfirmTitle: "리포트를 만들까요?",
    reportCreateConfirmBody:
      "지금 대화를 마치고 이 내용으로 학습 리포트를 생성합니다. 계속할까요?",
    reportCreateConfirmCta: "리포트 생성",
    reportCreateConfirmCancel: "계속 대화하기",
    reportDailyLimitToast:
      "오늘은 무료 리포트를 이미 만들었어요. 프리미엄으로 더 만들 수 있어요.",
    monthlyGrowthTitle: "{month} 영어 성장",
    monthlyCurrentScore: "현재 점수",
    monthlyChange: "평균 점수",
    monthlySessions: "완료한 학습",
    monthlySessionCount: "{count}회",
    monthlyEmpty:
      "아직 이번 달 학습 기록이 없어요.\n대화를 완료하면 여기에 성장 기록이 쌓여요.",
    monthlyNeedMoreForTrend:
      "리포트가 더 쌓이면 성장 흐름을 확인할 수 있어요.",
    monthlyChartTitle: "점수 성장",
    monthlyChartNoScores:
      "점수가 있는 세션이 아직 없어요.\n조금 더 길게 대화한 뒤 세션을 종료해 보세요.",
    monthlyChartTapHint: "그래프의 점을 누르면 그 시점의 리포트를 볼 수 있어요.",
    monthlyListTitle: "이번 달 학습",
    monthlyCalendarHint: "색이 칠해진 날을 누르면 그날의 리포트를 볼 수 있어요.",
    monthlyDayReportsTitle: "이날의 리포트",
    monthlyNoScore: "점수 없음",
    continuePractice: "이어서 연습하기",
    comeBackTomorrow: "내일 다시 하기",
    trainingDoneTitle: "오늘의 영어 훈련 완료 👍",
    trainingDoneBody: "내일 다시 이어서 연습해보세요",
    trainingDoneHint: "계속 연습하고 싶다면 이어서 대화할 수 있어요",
    delete: "삭제",
    reuse: "다시 쓰기",
    translating: "번역 중...",
    translation: "번역",
    translateFailed: "번역에 실패했어요. 다시 시도해 주세요.",
    dailyLimitReached:
      "오늘의 메시지 한도에 도달했어요. 내일 다시 시도해 주세요.",
    expressionHelperTitle: "💡 이렇게 말할 수 있어요",
    correctionTitle: "교정",
    noCorrectionNeeded: "수정할 필요가 없습니다.",
    correctionFeedbackCorrect: "👍 좋은 문장이에요! 아주 자연스러워요.",
    correctionFeedbackError: "💡 거의 다 됐어요. 작은 부분만 고쳐볼까요?",
    sessionComplete: "오늘의 영어 훈련을 완료했어요 👍",
    startNewSession: "새 대화 시작",
    endSession: "세션 종료",
    languageKorean: "한국어",
    languageEnglish: "English",
    languageSpanish: "Español",
    planPremium: "프리미엄 플랜 · 무제한",
    planFree: "무료 플랜 · 오늘 {used}/{limit}",
    upgradeCta: "프리미엄 업그레이드",
    paywallLimitBanner: "오늘 무료 채팅 한도에 도달했어요. 프리미엄으로 계속 학습할 수 있어요.",
    paywallTitle: "프리미엄으로 계속 학습하기",
    paywallSubtitle:
      "하루 제한 없이 영어 문장을 만들고, 교정받고, 내 영어 교재에 저장하세요.",
    paywallBenefitsTitle: "프리미엄 혜택",
    paywallBenefits:
      "하루 채팅 제한 해제\n리포트·복습 무제한\n내 영어 교재 저장 및 복습",
    paywallCta: "월 4,900원으로 시작하기",
    paywallRestore: "구매 복원",
    paywallLater: "나중에 하기",
    paywallNativeOnly: "앱에서 결제를 진행할 수 있어요",
    paywallPurchasing: "결제 진행 중…",
    paywallRestoring: "복원 중…",
    paywallActivatedToast: "프리미엄이 활성화됐어요",
    paywallRestoredToast: "구매가 복원됐어요",
    paywallRestoreEmpty: "복원할 구매 내역이 없어요",
    paywallPurchaseFailed: "결제를 완료하지 못했어요. 다시 시도해 주세요.",
    paywallPurchaseTimeout:
      "결제 연결 시간이 초과됐어요. Play 스토어에서 설치한 앱인지 확인 후 다시 시도해 주세요.",
    paywallNoProduct:
      "결제 상품을 불러오지 못했어요. Play Console·RevenueCat 설정을 확인해 주세요.",
    paywallCancelled: "결제가 취소됐어요",
  },
  en: {
    appTitle: "English correction chat",
    chatEmptyHint:
      "Example: \"I had a really busy day today.\"\nTry writing full sentences in your own words.",
    chatMode: "Chat in English",
    askExpression: "Ask expression",
    inputPlaceholder: "Write your own English (e.g. I went to the gym today.)",
    expressionPlaceholder: "Type what you want to say in Korean",
    send: "Send",
    chatStartCta: "AI starts",
    chatStartFailed: "Couldn’t start the conversation. Please try again.",
    translate: "Translate",
    listen: "Listen",
    corrected: "Corrected",
    highlighted: "Highlighted mistakes",
    natural: "Another expression",
    correctionBlockTitle: "Correction",
    correctionMyLine: "What you wrote",
    correctionTryThis: "Try this instead",
    explanation: "Explanation",
    example: "Example",
    useThisExpression: "Use this expression",
    save: "Save expression",
    saved: "✔ Saved",
    savedToBookToast: "Saved to My English Book ({count})\nYou can review this anytime.",
    learningBookNav: "My English Book",
    learningBookTitle: "My English Book",
    learningEmpty:
      "No saved expressions yet\n\nSave useful expressions while you chat\nand build your personal English book",
    learningSearchPlaceholder: "Search my expressions",
    learningSearchNoResults: "No matching cards found.",
    learningFilterEmpty: "No cards match this filter.",
    filterAll: "All",
    filterNew: "New",
    filterPracticing: "Practicing",
    filterUsable: "Familiar",
    cardShowDetails: "Show details",
    cardHideDetails: "Show less",
    reviewPracticingCta: "Review Practicing Expressions",
    reviewNewCta: "Review New Expressions",
    reviewTodayEmpty: "Nothing to review yet. Save a few expressions from chat first.",
    learningBackToChat: "← Back to chat",
    dashboardSavedToday: "Saved Today",
    dashboardTotalCards: "Total cards",
    dashboardTotalCardsSubtle: "{count} total expressions",
    dashboardPracticing: "Practicing",
    dashboardUsable: "Familiar",
    cardMySentence: "What I actually wrote",
    cardBetterExpression: "Better expression",
    cardMoreNatural: "Another expression",
    cardPoint: "Key point",
    practiceAgain: "🔁 Practice again",
    deleteFromBook: "🗑 Remove",
    reviewFrontHint: "The sentence you wrote",
    reviewReveal: "Show answer",
    reviewForgot: "Still Hard",
    reviewVague: "Not Sure",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Do you think you could naturally use this sentence next time?",
    progressStatusNew: "🆕 New",
    progressStatusPracticing: "🔁 Practicing",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Saved today",
    progressNotReviewed: "Not reviewed yet",
    progressReviewCount: "{count} reviews",
    progressLastReviewedToday: "last reviewed today",
    progressLastReviewedYesterday: "last reviewed yesterday",
    progressLastReviewedDays: "last reviewed {count} days ago",
    archive: "Reports",
    archiveEmpty: "No saved items yet.",
    savedItemsTab: "Saved expressions",
    sessionsTab: "Learning reports",
    sessionsEmpty:
      "No completed learning reports yet.\nEnd a session to create one.",
    openSession: "View report",
    clearSessions: "Clear all reports",
    freeTraining: "Free training",
    messagesUsed: "Messages used",
    resetArchive: "Reset archive",
    closeArchive: "Close",
    reportMenuTitle: "Reports",
    reportListTitle: "Completed sessions",
    reportListEmpty:
      "No completed learning reports yet.\nFinish a chat and end the session to create one.",
    reportClearAll: "Clear all",
    reportViewCta: "View report",
    reportTurnCount: "{count} turns",
    reportScoreLabel: "{score} pts",
    reportDetailBadge: "Session learning report",
    reportTodayLearning: "Today’s learning",
    reportStatExpressions: "Expressions",
    reportStatCorrections: "Corrections",
    reportStatTakeaways: "Takeaways",
    reportTimelineTitle: "Conversation",
    reportSummaryTitle: "Conversation recap",
    reportScoreTitle: "Session score",
    reportScoreInsufficient:
      "Not enough conversation to score reliably. Chat a bit more, then end the session.",
    reportScoreNativeHint:
      "Naturalness: 25 = native speaker, 0 = almost no English. Grammar is scored separately.",
    reportScoreBreakdownTitle: "Score breakdown",
    reportScoreFactorAccuracy: "Accuracy",
    reportScoreFactorNaturalness: "Naturalness",
    reportScoreFactorFluency: "Turn length",
    reportScoreFactorSpoken: "Spoken style",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "What went well",
    reportImprovementsTitle: "What to improve",
    reportMyExpression: "Your line",
    reportBetterExpression: "More natural",
    reportLearningTitle: "Expressions to take with you",
    reportShowTranscript: "View full conversation",
    reportHideTranscript: "Hide conversation",
    reportTranscriptReadonly:
      "Read-only — you can’t continue this chat from here.",
    reportTranscriptYou: "You",
    reportTranscriptAi: "AI",
    reportReviewTitle: "Conversation review",
    reportReviewHint: "See the chat exactly as it looked at the time.",
    reportReviewEmpty: "No conversation saved for this session.",
    reportChatCaptureLabel: "Chat replay",
    reportLightCorrectionLabel: "More natural",
    reportReviewDoneTitle: "You’ve reviewed the full conversation.",
    reportReviewDoneBody: "Ready to look closely at the English you used?",
    reportGotoAnalysis: "View detailed analysis",
    reportAnalysisTitle: "Detailed analysis",
    reportAnalysisHint: "Based on the English you actually used — what worked, and how to take it further.",
    reportAnalysisEmpty:
      "This chat is still short, so it’s hard to judge habits. Talk a bit more and we can analyze the pattern.",
    reportAnalysisStrengthsTitle: "What went well",
    reportAnalysisImprovementsTitle: "Try this next",
    reportAnalysisHabitsTitle: "Conversation habits",
    reportAnalysisNextGoalTitle: "Next-chat goal",
    reportAnalysisGenerating: "Analyzing the conversation...",
    reportAnalysisCategoryNatural: "Natural phrasing",
    reportAnalysisCategoryNuance: "Nuance",
    reportAnalysisCategoryWordChoice: "Word choice",
    reportAnalysisCategoryTone: "Tone",
    reportAnalysisCategoryFlow: "Flow",
    reportAnalysisCategoryVariety: "Variety",
    reportAnalysisCategoryConnection: "Connection",
    reportAnalysisCategoryExpression: "Expression",
    reportAnalysisCategoryConversation: "Conversation",
    reportAnalysisCategoryImprovement: "To try next",
    reportAnalysisStrengthLabel: "Strong line",
    reportAnalysisWhyGood: "Why it worked",
    reportAnalysisCorrected: "Correction",
    reportAnalysisWhy: "Why?",
    reportAnalysisAlternative: "Another way to say it",
    reportAnalysisExample: "Example",
    reportTakeawaysTitle: "Takeaways",
    reportTakeawaysHint: "Remember just these for today.",
    reportTakeawaysEmpty: "No key takeaways for this session yet.",
    reportCreatedToast: "Learning report saved",
    quizReadyToast: "Your review materials are ready. Open the Review tab.",
    reportSessionsTab: "Session reports",
    reportMonthlyTab: "Monthly report",
    reportBack: "← Reports",
    monthlyOpenFull: "View monthly report",
    homeTabChat: "Chat",
    homeTabSessions: "Sessions",
    homeTabMonthly: "Monthly",
    homeTabReports: "Reports",
    homeTabSaved: "Saved",
    homeTabVocab: "Vocab",
    homeTabQuiz: "Review",
    quizTodayTitle: "Today’s review",
    quizTodaySubtitle: "Practice what you struggled with in recent chats.",
    quizMissionPrompt: "Spend 2 minutes reviewing\nwhat you learned recently.",
    quizTodayCountLabel: "Today’s questions",
    quizRecentReviewTitle: "Recent review",
    quizTodayCardTitle: "Today’s review",
    quizTodayMeta: "{count} questions · about {minutes} min",
    quizCompositionGrammar: "Grammar {count}",
    quizCompositionVocab: "Words {count}",
    quizCompositionExpression: "Expressions {count}",
    quizStartCta: "Start review",
    quizContinueCta: "Continue",
    quizReviewAgainCta: "Try new questions",
    quizCreateNewCta: "Create a new quiz",
    quizTodayFinished: "That’s all for today’s review. Come back tomorrow.",
    quizGenerating: "Creating questions...",
    quizGenerateFailed: "Couldn’t create questions. Please try again.",
    quizLoading: "Loading...",
    quizEmptyTitle: "Nothing to review yet.",
    quizEmptyBody:
      "Create a report after chatting,\nand grammar and vocabulary review cards will be ready.",
    quizEmptyCta: "Chat in English",
    reviewFilterAll: "All",
    reviewFilterGrammar: "Grammar",
    reviewFilterVocab: "Words",
    reviewMySentence: "What you wrote",
    reviewBetterSentence: "Try this instead",
    reviewExamples: "Examples",
    reviewSimilar: "Similar words",
    reviewRefresh: "Rebuild materials",
    reviewGenerating: "Creating review materials...",
    reviewGenerateFailed: "Couldn’t create review materials.",
    reviewEmptyBody:
      "Save words while chatting, then create a report.\nReview cards use your grammar mistakes and saved words.",
    reviewCompleteCta: "Done reviewing",
    reviewResetCta: "Clear all",
    reviewSectionFallback: "Review {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ Correct",
    quizIncorrect: "Let’s check that again",
    quizNext: "Next",
    quizSeeResult: "See results",
    quizCompleteTitle: "Today’s review done ✓",
    quizCompleteScore: "You got {correct} of {total} right.",
    quizRememberedTitle: "Looking solid",
    quizReviewAgainTitle: "Worth another look",
    quizBackHome: "Back to review home",
    quizAlreadyDone: "You’ve already finished today’s review.",
    quizTypeGrammar: "Grammar",
    quizTypeVocabulary: "Vocabulary",
    quizTypeExpression: "Expression",
    homeBack: "← Home",
    homeHubBadge: "Home",
    homeHubSubtitle: "Choose where you’d like to practice today.",
    homeOpenCta: "Open",
    homeDestChatDesc: "Practice English in conversation with corrections.",
    homeDestSessionsDesc: "Review learning reports from completed sessions.",
    homeDestMonthlyDesc: "See this month’s score growth and learning.",
    homeDestSavedDesc: "Review expressions you saved from chat.",
    homeDestVocabDesc: "Search in your language and save English words.",
    vocabTitle: "Vocabulary",
    vocabFilterAll: "All",
    vocabFilterWords: "Words",
    vocabFilterPhrases: "Phrases",
    vocabStatusLearning: "Learning",
    vocabStatusFamiliar: "Familiar",
    vocabQueryHint: "Search in your UI language to find English words.",
    vocabSearchPlaceholder: "Search a word in your language",
    vocabSearchCta: "Search",
    vocabSearching: "Searching...",
    vocabResultsTitle: "Results",
    vocabSavedTitle: "Saved words",
    vocabEmpty: "No saved words yet.\nSearch above to add some.",
    vocabHideGloss: "Hide meanings",
    vocabShuffle: "Shuffle",
    vocabRevealGloss: "Tap to see meaning",
    vocabNoResults: "No results found.",
    vocabSave: "Save",
    vocabSaved: "Saved",
    vocabDelete: "Delete",
    vocabSavedToast: "Saved to vocabulary",
    vocabSearchFailed: "Search failed. Please try again.",
    vocabSaveFromChat: "Check words",
    vocabPickTitle: "Pick words",
    vocabPickHint: "Tap highlighted words in this chat to save them.",
    vocabPickModeHint: "Amber = word, sky = phrase/idiom. Tap to see the meaning, then Save.",
    vocabPickEmpty: "No English words to save yet. Chat a bit first.",
    vocabPickCancel: "Close",
    vocabPickSave: "Save {count}",
    vocabPickSaving: "Saving...",
    vocabPickDone: "Done",
    vocabPickSavedToast: "Word saved",
    vocabPickNoneToast: "No words to save",
    vocabPickFailed: "Couldn’t save words. Please try again.",
    vocabPreviewLoading: "Loading meaning...",
    vocabPreviewSave: "Save",
    vocabPreviewClose: "Close",
    chatHistoryTitle: "Chat history",
    chatHistoryListTitle: "Past chats",
    chatHistoryEmpty:
      "No saved chats yet.\nStart a conversation and it will show up here.",
    chatHistoryContinue: "Continue chat",
    chatHistoryNew: "Start new chat",
    chatHistoryClear: "Clear all",
    chatHistoryCurrent: "Current",
    chatHistoryHasReport: "Has report",
    createReport: "Create report",
    chatCardsOn: "Cards on",
    chatCardsOff: "Cards off",
    chatCardsLabel: "Cards",
    toggleLegendOn: "On",
    toggleLegendOff: "Off",
    sessionSavedToHistoryToast: "Saved to chat history",
    reportCreateEmptyToast: "No conversation yet to create a report",
    reportCreateConfirmTitle: "Create a report?",
    reportCreateConfirmBody:
      "This will end the current chat and create a learning report from it. Continue?",
    reportCreateConfirmCta: "Create report",
    reportCreateConfirmCancel: "Keep chatting",
    reportDailyLimitToast:
      "You’ve already made today’s free report. Go Premium for more.",
    monthlyGrowthTitle: "{month} growth",
    monthlyCurrentScore: "Current score",
    monthlyChange: "Average",
    monthlySessions: "Completed",
    monthlySessionCount: "{count}",
    monthlyEmpty:
      "No learning records this month yet.\nFinish a chat to start building your growth timeline.",
    monthlyNeedMoreForTrend:
      "Complete more reports to see your growth trend.",
    monthlyChartTitle: "Score growth",
    monthlyChartNoScores:
      "No scored sessions yet.\nChat a bit longer, then end the session.",
    monthlyChartTapHint: "Tap a point on the chart to open that session report.",
    monthlyListTitle: "This month’s learning",
    monthlyCalendarHint: "Tap a colored day to open that day’s report.",
    monthlyDayReportsTitle: "Reports this day",
    monthlyNoScore: "No score",
    continuePractice: "Continue Practice",
    comeBackTomorrow: "Come back tomorrow",
    trainingDoneTitle: "You've completed today's training 👍",
    trainingDoneBody: "Come back tomorrow to continue.",
    trainingDoneHint: "If you want, you can keep practicing now.",
    delete: "Delete",
    reuse: "Reuse",
    translating: "Translating...",
    translation: "Translation",
    translateFailed: "Translation failed. Please try again.",
    dailyLimitReached: "You reached today's message limit. Please come back tomorrow.",
    expressionHelperTitle: "💡 You can say it like this",
    correctionTitle: "Correction",
    noCorrectionNeeded: "No changes needed.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Today's practice is complete 🎯",
    startNewSession: "Start New Session",
    endSession: "End Session",
    languageKorean: "Korean",
    languageEnglish: "English",
    languageSpanish: "Spanish",
    planPremium: "Premium · Unlimited",
    planFree: "Free plan · {used}/{limit} today",
    upgradeCta: "Upgrade to Premium",
    paywallLimitBanner: "You've reached today's free chat limit. Go Premium to keep practicing.",
    paywallTitle: "Keep learning with Premium",
    paywallSubtitle:
      "Write, get corrections, and save to My English Book — without a daily chat limit.",
    paywallBenefitsTitle: "Premium includes",
    paywallBenefits:
      "No daily chat limit\nUnlimited reports and review\nSave and review in My English Book",
    paywallCta: "Start for ₩4,900/month",
    paywallRestore: "Restore purchases",
    paywallLater: "Not now",
    paywallNativeOnly: "You can complete payment in the app",
    paywallPurchasing: "Processing…",
    paywallRestoring: "Restoring…",
    paywallActivatedToast: "Premium is now active",
    paywallRestoredToast: "Your purchase was restored",
    paywallRestoreEmpty: "No purchases to restore",
    paywallPurchaseFailed: "We couldn't complete the purchase. Please try again.",
    paywallPurchaseTimeout:
      "The purchase timed out. Install the app from the Play Store, then try again.",
    paywallNoProduct:
      "We couldn't load the subscription product. Check Play Console and RevenueCat setup.",
    paywallCancelled: "Purchase cancelled",
  },
  es: {
    appTitle: "Chat de corrección de inglés",
    chatEmptyHint:
      "Ejemplo: \"I had a really busy day today.\"\nEscribe frases completas con tus palabras.",
    chatMode: "Hablar en ingles",
    askExpression: "Preguntar expresion",
    inputPlaceholder: "Escribe en inglés con tus palabras (ej. I went to the gym today.)",
    expressionPlaceholder: "Escribe en coreano lo que quieres decir",
    send: "Enviar",
    chatStartCta: "Empieza la IA",
    chatStartFailed: "No se pudo empezar la conversación. Inténtalo de nuevo.",
    translate: "Traducir",
    listen: "Escuchar",
    corrected: "Correccion",
    highlighted: "Errores marcados",
    natural: "Otra expresión",
    correctionBlockTitle: "Corrección",
    correctionMyLine: "Lo que escribiste",
    correctionTryThis: "Prueba esto",
    explanation: "Explicacion",
    example: "Ejemplo",
    useThisExpression: "Usar esta expresión",
    save: "Guardar expresión",
    saved: "✔ Guardado",
    savedToBookToast: "Guardado en tu libro de inglés ({count})\nPuedes repasarlo cuando quieras.",
    learningBookNav: "Mi libro de inglés",
    learningBookTitle: "Mi libro de inglés",
    learningEmpty:
      "Todavia no guardaste expresiones\n\nGuarda frases utiles mientras chateas\ny arma tu libro personal de ingles",
    learningSearchPlaceholder: "Buscar en mi libro",
    learningSearchNoResults: "No hay resultados.",
    learningFilterEmpty: "No hay tarjetas con este filtro.",
    filterAll: "Todo",
    filterNew: "Nuevas",
    filterPracticing: "Practicando",
    filterUsable: "Familiares",
    cardShowDetails: "Ver detalles",
    cardHideDetails: "Menos",
    reviewPracticingCta: "Repasar expresiones en practica",
    reviewNewCta: "Repasar expresiones nuevas",
    reviewTodayEmpty: "Nada para repasar todavia. Guarda algunas expresiones desde el chat.",
    learningBackToChat: "← Volver al chat",
    dashboardSavedToday: "Guardadas hoy",
    dashboardTotalCards: "Tarjetas",
    dashboardTotalCardsSubtle: "{count} expresiones en total",
    dashboardPracticing: "Practicando",
    dashboardUsable: "Familiares",
    cardMySentence: "Lo que yo escribi",
    cardBetterExpression: "Mejor expresion",
    cardMoreNatural: "Otra expresión",
    cardPoint: "Punto clave",
    practiceAgain: "🔁 Repasar",
    deleteFromBook: "🗑 Borrar",
    reviewFrontHint: "La frase que escribiste",
    reviewReveal: "Ver respuesta",
    reviewForgot: "Aun dificil",
    reviewVague: "Dudoso",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Crees que podrias usar esta frase de forma natural la proxima vez?",
    progressStatusNew: "🆕 Nueva",
    progressStatusPracticing: "🔁 Practicando",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Guardada hoy",
    progressNotReviewed: "Sin repasar",
    progressReviewCount: "{count} repasos",
    progressLastReviewedToday: "ultimo repaso hoy",
    progressLastReviewedYesterday: "ultimo repaso ayer",
    progressLastReviewedDays: "ultimo repaso hace {count} dias",
    archive: "Informes",
    archiveEmpty: "No hay elementos guardados.",
    savedItemsTab: "Expresiones guardadas",
    sessionsTab: "Informes de aprendizaje",
    sessionsEmpty:
      "Aún no hay informes completados.\nFinaliza una sesión para crear uno.",
    openSession: "Ver informe",
    clearSessions: "Borrar todos los informes",
    freeTraining: "Practica libre",
    messagesUsed: "Mensajes usados",
    resetArchive: "Reiniciar archivo",
    closeArchive: "Cerrar",
    reportMenuTitle: "Informes",
    reportListTitle: "Sesiones completadas",
    reportListEmpty:
      "Aún no hay informes de aprendizaje.\nTermina el chat y finaliza la sesión para crear uno.",
    reportClearAll: "Borrar todo",
    reportViewCta: "Ver informe",
    reportTurnCount: "{count} turnos",
    reportScoreLabel: "{score} pts",
    reportDetailBadge: "Informe de la sesión",
    reportTodayLearning: "Aprendizaje de hoy",
    reportStatExpressions: "Expresiones",
    reportStatCorrections: "Correcciones",
    reportStatTakeaways: "Para llevar",
    reportTimelineTitle: "Conversación",
    reportSummaryTitle: "Resumen de la conversación",
    reportScoreTitle: "Puntuación de la sesión",
    reportScoreInsufficient:
      "No hay suficiente conversación para puntuar con fiabilidad. Habla un poco más y luego finaliza la sesión.",
    reportScoreNativeHint:
      "Naturalidad: 25 = nativo, 0 = casi no sabe inglés. La gramática no entra aquí.",
    reportScoreBreakdownTitle: "Desglose de la puntuación",
    reportScoreFactorAccuracy: "Precisión",
    reportScoreFactorNaturalness: "Naturalidad",
    reportScoreFactorFluency: "Longitud del turno",
    reportScoreFactorSpoken: "Estilo oral",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "Lo que salió bien",
    reportImprovementsTitle: "Qué mejorar",
    reportMyExpression: "Tu frase",
    reportBetterExpression: "Más natural",
    reportLearningTitle: "Expresiones para llevarte",
    reportShowTranscript: "Ver conversación completa",
    reportHideTranscript: "Ocultar conversación",
    reportTranscriptReadonly:
      "Solo lectura: no puedes continuar este chat desde aquí.",
    reportTranscriptYou: "Tú",
    reportTranscriptAi: "IA",
    reportReviewTitle: "Repaso de la conversación",
    reportReviewHint: "Mira el chat tal como se veía en ese momento.",
    reportReviewEmpty: "No hay conversación guardada en esta sesión.",
    reportChatCaptureLabel: "Repetición del chat",
    reportLightCorrectionLabel: "Más natural",
    reportReviewDoneTitle: "Ya repasaste toda la conversación.",
    reportReviewDoneBody: "¿Miramos de cerca el inglés que usaste hoy?",
    reportGotoAnalysis: "Ver análisis detallado",
    reportAnalysisTitle: "Análisis detallado",
    reportAnalysisHint: "A partir del inglés que usaste: qué funcionó y cómo llevarlo más lejos.",
    reportAnalysisEmpty:
      "La conversación aún es corta para juzgar hábitos. Habla un poco más y podremos analizar el patrón.",
    reportAnalysisStrengthsTitle: "Lo que te salió bien",
    reportAnalysisImprovementsTitle: "Prueba esto",
    reportAnalysisHabitsTitle: "Hábitos de conversación",
    reportAnalysisNextGoalTitle: "Objetivo de la próxima vez",
    reportAnalysisGenerating: "Analizando la conversación...",
    reportAnalysisCategoryNatural: "Expresión natural",
    reportAnalysisCategoryNuance: "Matiz",
    reportAnalysisCategoryWordChoice: "Elección de palabras",
    reportAnalysisCategoryTone: "Tono",
    reportAnalysisCategoryFlow: "Flujo",
    reportAnalysisCategoryVariety: "Variedad",
    reportAnalysisCategoryConnection: "Conexión",
    reportAnalysisCategoryExpression: "Expresión",
    reportAnalysisCategoryConversation: "Conversación",
    reportAnalysisCategoryImprovement: "Para mejorar",
    reportAnalysisStrengthLabel: "Buena expresión",
    reportAnalysisWhyGood: "¿Por qué estuvo bien?",
    reportAnalysisCorrected: "Corrección",
    reportAnalysisWhy: "¿Por qué?",
    reportAnalysisAlternative: "Otra forma de decirlo",
    reportAnalysisExample: "Ejemplo",
    reportTakeawaysTitle: "Para llevarte hoy",
    reportTakeawaysHint: "Con recordar esto es suficiente por hoy.",
    reportTakeawaysEmpty: "Aún no hay expresiones clave para llevarte.",
    reportCreatedToast: "Informe de aprendizaje guardado",
    quizReadyToast: "Tu material de repaso está listo. Ábrelo en la pestaña Repaso.",
    reportSessionsTab: "Informes de sesión",
    reportMonthlyTab: "Informe mensual",
    reportBack: "← Informes",
    monthlyOpenFull: "Ver informe mensual",
    homeTabChat: "Chat",
    homeTabSessions: "Sesiones",
    homeTabMonthly: "Mensual",
    homeTabReports: "Informes",
    homeTabSaved: "Guardado",
    homeTabVocab: "Vocabulario",
    homeTabQuiz: "Repaso",
    quizTodayTitle: "Repaso de hoy",
    quizTodaySubtitle:
      "Practica lo que te costó en conversaciones recientes.",
    quizMissionPrompt: "Dedica 2 minutos a repasar\nlo que aprendiste recientemente.",
    quizTodayCountLabel: "Preguntas de hoy",
    quizRecentReviewTitle: "Repaso reciente",
    quizTodayCardTitle: "Repaso de hoy",
    quizTodayMeta: "{count} preguntas · unos {minutes} min",
    quizCompositionGrammar: "Gramática {count}",
    quizCompositionVocab: "Palabras {count}",
    quizCompositionExpression: "Expresiones {count}",
    quizStartCta: "Empezar repaso",
    quizContinueCta: "Continuar",
    quizReviewAgainCta: "Nuevas preguntas",
    quizCreateNewCta: "Crear un cuestionario nuevo",
    quizTodayFinished: "Con esto termina el repaso de hoy. Vuelve mañana.",
    quizGenerating: "Creando preguntas...",
    quizGenerateFailed: "No se pudieron crear las preguntas. Inténtalo de nuevo.",
    quizLoading: "Cargando...",
    quizEmptyTitle: "Aún no hay nada que repasar.",
    quizEmptyBody:
      "Crea un informe después de chatear\ny tendrás fichas de gramática y vocabulario.",
    quizEmptyCta: "Hablar en inglés",
    reviewFilterAll: "Todo",
    reviewFilterGrammar: "Gramática",
    reviewFilterVocab: "Palabras",
    reviewMySentence: "Lo que escribiste",
    reviewBetterSentence: "Prueba así",
    reviewExamples: "Ejemplos",
    reviewSimilar: "Palabras parecidas",
    reviewRefresh: "Volver a crear el material",
    reviewGenerating: "Creando material de repaso...",
    reviewGenerateFailed: "No se pudo crear el material de repaso.",
    reviewEmptyBody:
      "Guarda palabras al chatear y crea un informe.\nEl repaso usa tu gramática y las palabras guardadas.",
    reviewCompleteCta: "Repaso listo",
    reviewResetCta: "Vaciar",
    reviewSectionFallback: "Repaso {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ Correcto",
    quizIncorrect: "¿Lo revisamos?",
    quizNext: "Siguiente",
    quizSeeResult: "Ver resultado",
    quizCompleteTitle: "Repaso de hoy listo ✓",
    quizCompleteScore: "Acertaste {correct} de {total}.",
    quizRememberedTitle: "Lo recuerdas bien",
    quizReviewAgainTitle: "Para revisar",
    quizBackHome: "Volver al inicio del repaso",
    quizAlreadyDone: "Ya completaste el repaso de hoy.",
    quizTypeGrammar: "Gramática",
    quizTypeVocabulary: "Vocabulario",
    quizTypeExpression: "Expresión",
    homeBack: "← Inicio",
    homeHubBadge: "Inicio",
    homeHubSubtitle: "Elige dónde quieres practicar hoy.",
    homeOpenCta: "Abrir",
    homeDestChatDesc: "Practica inglés en conversación con correcciones.",
    homeDestSessionsDesc: "Revisa los informes de tus sesiones completadas.",
    homeDestMonthlyDesc: "Mira el crecimiento de este mes.",
    homeDestSavedDesc: "Repasa las expresiones que guardaste.",
    homeDestVocabDesc: "Busca en tu idioma y guarda palabras en inglés.",
    vocabTitle: "Vocabulario",
    vocabFilterAll: "Todo",
    vocabFilterWords: "Palabras",
    vocabFilterPhrases: "Expresiones",
    vocabStatusLearning: "Aprendiendo",
    vocabStatusFamiliar: "Familiar",
    vocabQueryHint: "Busca en el idioma de la interfaz para ver palabras en inglés.",
    vocabSearchPlaceholder: "Busca una palabra en tu idioma",
    vocabSearchCta: "Buscar",
    vocabSearching: "Buscando...",
    vocabResultsTitle: "Resultados",
    vocabSavedTitle: "Palabras guardadas",
    vocabEmpty: "Aún no hay palabras guardadas.\nBusca arriba para añadir.",
    vocabHideGloss: "Ocultar significados",
    vocabShuffle: "Aleatorio",
    vocabRevealGloss: "Toca para ver el significado",
    vocabNoResults: "No hay resultados.",
    vocabSave: "Guardar",
    vocabSaved: "Guardado",
    vocabDelete: "Eliminar",
    vocabSavedToast: "Guardado en el vocabulario",
    vocabSearchFailed: "La búsqueda falló. Inténtalo de nuevo.",
    vocabSaveFromChat: "Revisar palabras",
    vocabPickTitle: "Elegir palabras",
    vocabPickHint: "Toca las palabras resaltadas del chat para guardarlas.",
    vocabPickModeHint: "Ámbar = palabra, celeste = locución. Toca para ver el significado.",
    vocabPickEmpty: "Aún no hay palabras en inglés. Habla un poco primero.",
    vocabPickCancel: "Cerrar",
    vocabPickSave: "Guardar {count}",
    vocabPickSaving: "Guardando...",
    vocabPickDone: "Listo",
    vocabPickSavedToast: "Palabra guardada",
    vocabPickNoneToast: "No hay palabras para guardar",
    vocabPickFailed: "No se pudieron guardar. Inténtalo de nuevo.",
    vocabPreviewLoading: "Cargando significado...",
    vocabPreviewSave: "Guardar",
    vocabPreviewClose: "Cerrar",
    chatHistoryTitle: "Historial de chat",
    chatHistoryListTitle: "Chats anteriores",
    chatHistoryEmpty:
      "Aún no hay chats guardados.\nEmpieza una conversación y aparecerá aquí.",
    chatHistoryContinue: "Continuar chat",
    chatHistoryNew: "Nuevo chat",
    chatHistoryClear: "Borrar todo",
    chatHistoryCurrent: "Actual",
    chatHistoryHasReport: "Con informe",
    createReport: "Crear informe",
    chatCardsOn: "Tarjetas visibles",
    chatCardsOff: "Tarjetas ocultas",
    chatCardsLabel: "Tarjetas",
    toggleLegendOn: "On",
    toggleLegendOff: "Off",
    sessionSavedToHistoryToast: "Guardado en el historial",
    reportCreateEmptyToast: "Aún no hay conversación para crear un informe",
    reportCreateConfirmTitle: "¿Crear un informe?",
    reportCreateConfirmBody:
      "Esto terminará el chat actual y creará un informe de aprendizaje. ¿Continuar?",
    reportCreateConfirmCta: "Crear informe",
    reportCreateConfirmCancel: "Seguir hablando",
    reportDailyLimitToast:
      "Ya usaste el informe gratis de hoy. Pasa a Premium para crear más.",
    monthlyGrowthTitle: "Crecimiento · {month}",
    monthlyCurrentScore: "Puntuación actual",
    monthlyChange: "Promedio",
    monthlySessions: "Completadas",
    monthlySessionCount: "{count}",
    monthlyEmpty:
      "Aún no hay registros de aprendizaje este mes.\nTermina una conversación para ver tu progreso aquí.",
    monthlyNeedMoreForTrend:
      "Con más informes podrás ver la tendencia de crecimiento.",
    monthlyChartTitle: "Crecimiento de puntuación",
    monthlyChartNoScores:
      "Todavía no hay sesiones con puntuación.\nHabla un poco más y termina la sesión.",
    monthlyChartTapHint:
      "Toca un punto del gráfico para abrir el informe de esa sesión.",
    monthlyListTitle: "Aprendizaje de este mes",
    monthlyCalendarHint: "Toca un día coloreado para ver el informe de ese día.",
    monthlyDayReportsTitle: "Informes de este día",
    monthlyNoScore: "Sin puntuación",
    continuePractice: "Continuar practicando",
    comeBackTomorrow: "Volver manana",
    trainingDoneTitle: "Has completado el entrenamiento de hoy 👍",
    trainingDoneBody: "Vuelve manana para continuar.",
    trainingDoneHint: "Si quieres, puedes seguir practicando ahora.",
    delete: "Eliminar",
    reuse: "Reutilizar",
    translating: "Traduciendo...",
    translation: "Traduccion",
    translateFailed: "No se pudo traducir. Intentalo de nuevo.",
    dailyLimitReached: "Llegaste al limite de mensajes de hoy. Vuelve manana.",
    expressionHelperTitle: "💡 Puedes decirlo asi",
    correctionTitle: "Correccion",
    noCorrectionNeeded: "No hace falta corregir.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Completaste la practica de hoy 🎯",
    startNewSession: "Start New Session",
    endSession: "Finalizar sesion",
    languageKorean: "Coreano",
    languageEnglish: "Ingles",
    languageSpanish: "Espanol",
    planPremium: "Premium · Ilimitado",
    planFree: "Plan gratis · {used}/{limit} hoy",
    upgradeCta: "Mejorar a Premium",
    paywallLimitBanner: "Llegaste al límite gratis de hoy. Premium te deja seguir practicando.",
    paywallTitle: "Sigue aprendiendo con Premium",
    paywallSubtitle:
      "Escribe, recibe correcciones y guarda en tu libro — sin límite diario de chat.",
    paywallBenefitsTitle: "Premium incluye",
    paywallBenefits:
      "Sin límite diario de chat\nInformes y repaso ilimitados\nGuardar y repasar en tu libro",
    paywallCta: "Empezar por 4.900 ₩/mes",
    paywallRestore: "Restaurar compras",
    paywallLater: "Ahora no",
    paywallNativeOnly: "Puedes pagar en la app",
    paywallPurchasing: "Procesando…",
    paywallRestoring: "Restaurando…",
    paywallActivatedToast: "Premium activado",
    paywallRestoredToast: "Compra restaurada",
    paywallRestoreEmpty: "No hay compras para restaurar",
    paywallPurchaseFailed: "No se pudo completar la compra. Inténtalo de nuevo.",
    paywallPurchaseTimeout:
      "La compra tardó demasiado. Instala la app desde Play Store e inténtalo de nuevo.",
    paywallNoProduct:
      "No se pudo cargar el producto. Revisa Play Console y RevenueCat.",
    paywallCancelled: "Compra cancelada",
  },
  ja: generatedLocales.ja,
  zh: generatedLocales.zh,
  vi: generatedLocales.vi,
  fr: generatedLocales.fr,
  pt: generatedLocales.pt,
  id: generatedLocales.id,
} as const;

export type Locale = keyof typeof copy;
export type UICopy = (typeof copy)[Locale];

export function isLocale(value: string): value is Locale {
  return Object.prototype.hasOwnProperty.call(copy, value);
}
