import generatedLocales from "@/lib/locales/generated.json";
import {
  type LearningLanguageCode,
  uiLocaleOptions,
} from "@/lib/learningLanguages";

export const APP_LOCALE_STORAGE_KEY = "appUiLocale";

/** UI languages follow learning languages — do not maintain a separate list. */
export const LOCALE_OPTIONS = uiLocaleOptions();

const generatedBillingOverlay = {
  videoLearnQuotaReached:
    "You’ve used this month’s import points. Library and saved videos can still be replayed.",
  videoLearnTooLong:
    "This video is longer than 15 minutes, so it can’t be prepared.",
  videoLearnQuotaHint:
    "{used}/{limit} import points this month · 1 point per 3 minutes · library and saved videos are free",
  studyImageSoon:
    "Photo reading is off for now. Please use PDF, EPUB, or TXT.",
  studyDropHint:
    "Choose a file or drop it here.\nPDF, EPUB, and TXT are supported.",
  planPremium: "Premium · this month’s library + {limit} import points",
  paywallCta: "Start for ₩9,900/month",
  paywallLimitBanner:
    "You've reached a free limit. Go Premium to keep learning from video.",
  paywallSubtitle:
    "Premium opens this month’s study library and 80 import points for your own links. Saved videos and library titles don’t use points.",
  paywallBenefits:
    "This month’s full study library\n80 import points for your own videos (3 min = 1 point)\nReplaying saved videos is free\nNo daily chat limit",
  videoLearnBody:
    "Pick a title from this month’s library, or paste your own link. Library titles are free; custom links use import points.",
  videoLearnLibraryTitle: "This month’s library",
  videoLearnLibrarySubtitleFree:
    "Free trial: {used}/{limit} episodes. It doesn’t refill each month — subscribe to open the full monthly pack.",
  videoLearnLibrarySubtitlePremium:
    "This month’s study pack · no points charged",
  videoLearnLibraryEmpty:
    "A library for this language isn’t ready yet. Premium members can paste a link instead.",
  videoLearnLibraryTrial: "Trial",
  videoLearnLibraryLocked: "Locked",
  videoLearnImportLocked:
    "Pasting your own link is a Premium feature and uses import points.",
  videoLearnCatalogLocked:
    "This episode is in the Premium library.",
  chatAttachPhoto: "Photo",
  chatRemovePhoto: "Remove photo",
  chatCall: "Call",
  chatCalling: "Calling…",
  chatInCall: "On a call",
  chatMute: "Mute",
  chatUnmute: "Unmute",
  chatHangUp: "Hang up",
  chatCallEnded: "Call ended · {duration}",
  chatCallFailed: "Couldn't connect the call. Try again.",
  chatMicDenied: "Microphone permission is needed for a call.",
  chatNativeMode: "Chat",
  chatTutorMode: "Help",
  sessionMenu: "Menu",
  videoLearnCancelPrep: "Stop preparing",
  chatDuringCall: "The tutor answers out loud while you are on a call.",
  reportContent: "Report this reply",
  reportTitle: "Report AI content",
  reportSubtitle: "Tell us what was wrong with this AI-generated reply. We review reports and adjust the assistant.",
  reportReasonOffensive: "Offensive or inappropriate",
  reportReasonInaccurate: "Wrong or misleading",
  reportReasonUnsafe: "Unsafe or harmful advice",
  reportReasonOther: "Something else",
  reportNoteLabel: "Anything to add? (optional)",
  reportSubmit: "Send report",
  reportCancel: "Cancel",
  reportThanks: "Thanks — your report was sent.",
  reportFailed: "Couldn't send the report. Please try again.",
  billingOpen: "Plan",
  billingScreenTitle: "Plan & billing",
  billingFreeLabel: "Free",
  billingPremiumLabel: "Premium",
  billingClose: "Close",
  headerImportPoints: "{remaining} pts",
  discoverImportPoints: "{n} pts",
  chatReading: "Reading",
} as const;

export const copy = {
  ko: {
    appTitle: "{targetLanguage} 교정 채팅",
    chatEmptyHint:
      "예: \"I had a really busy day today.\"\n내 말로 {targetLanguage} 문장을 직접 써보세요",
    chatMode: "{targetLanguage}로 대화",
    askExpression: "표현 알아보기",
    inputPlaceholder: "{targetLanguage}로 직접 문장을 써보세요 (예: I went to the gym today.)",
    expressionPlaceholder: "한국어로 말하고 싶은 내용을 입력하세요",
    send: "전송",
    chatStartCta: "먼저 말하기",
    chatStartFailed: "대화를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
    chatAttachPhoto: "사진",
    chatRemovePhoto: "사진 빼기",
    chatCall: "통화",
    callTranscriptTitle: "통화 기록",
    chatCallNoPoints: "통화 포인트를 다 썼어요. 다음 달에 다시 채워져요.",
    chatCalling: "연결 중…",
    chatInCall: "통화 중",
    chatMute: "음소거",
    chatUnmute: "음소거 해제",
    chatHangUp: "끊기",
    chatCallEnded: "통화 종료 · {duration}",
    chatCallFailed: "통화를 연결하지 못했어요. 다시 시도해 주세요.",
    chatMicDenied: "통화를 하려면 마이크 권한이 필요해요.",
    chatNativeMode: "일상 대화",
    chatTutorMode: "도움 모드",
    sessionMenu: "메뉴",
    videoLearnCancelPrep: "생성 취소",
    chatDuringCall: "통화 중에는 튜터가 음성으로 답해요.",
    reportContent: "이 답변 신고",
    reportTitle: "AI 콘텐츠 신고",
    reportSubtitle: "이 AI 답변의 어떤 점이 문제였는지 알려주세요. 신고를 확인하고 도우미를 조정합니다.",
    reportReasonOffensive: "불쾌하거나 부적절해요",
    reportReasonInaccurate: "틀렸거나 오해를 줘요",
    reportReasonUnsafe: "위험하거나 해로운 조언이에요",
    reportReasonOther: "그 밖의 문제",
    reportNoteLabel: "덧붙일 내용이 있나요? (선택)",
    reportSubmit: "신고 보내기",
    reportCancel: "취소",
    reportThanks: "신고를 보냈어요. 고맙습니다.",
    reportFailed: "신고를 보내지 못했어요. 다시 시도해 주세요.",
    billingOpen: "플랜",
    billingScreenTitle: "플랜 및 결제",
    billingFreeLabel: "무료",
    billingPremiumLabel: "프리미엄",
    billingClose: "닫기",
    headerImportPoints: "{remaining}포인트",
    chatReading: "해석",
    translate: "번역",
    listen: "듣기",
    insightAnalyze: "분석",
    inspectTabSentence: "문장",
    insightSaveWord: "단어 저장",
    insightLoading: "이 표현을 살펴보는 중...",
    insightFailed: "설명을 불러오지 못했어요. 다시 시도해 주세요.",
    insightClose: "닫기",
    insightBack: "이전 설명",
    insightInSentence: "이 문장에서는",
    insightPattern: "구조",
    insightExamples: "다른 예문",
    insightTip: "주의",
    insightComparison: "비슷하지만 다른 표현",
    insightHint: "궁금한 부분을 선택한 뒤 분석을 누르세요.",
    corrected: "교정 문장",
    highlighted: "오류 표시",
    natural: "또 다른 표현",
    correctionBlockTitle: "문법 교정",
    correctionMyLine: "내가 쓴 표현",
    correctionTryThis: "이렇게 바꿔보세요",
    explanation: "설명",
    example: "예문",
    useThisExpression: "이 표현 써보기",
    save: "표현 저장",
    saved: "✔ 저장됨",
    savedToBookToast: "내 {targetLanguage} 교재에 저장했어요 ({count}개)\n나중에 다시 복습할 수 있어요",
    learningBookNav: "내 {targetLanguage} 교재",
    learningBookTitle: "내 {targetLanguage} 교재",
    learningEmpty:
      "아직 저장한 표현이 없어요\n\n채팅 중 좋은 표현을 저장하면\n나만의 {targetLanguage} 교재가 만들어집니다",
    learningSearchPlaceholder: "내 표현 검색하기",
    learningSearchNoResults: "검색 결과가 없어요.",
    learningFilterEmpty: "이 조건에 맞는 카드가 없어요.",
    filterAll: "전체",
    filterNew: "새 문장",
    filterPracticing: "연습 중",
    filterUsable: "익숙한 표현",
    cardShowDetails: "자세히 보기",
    cardHideDetails: "간단히 보기",
    reviewPracticingCta: "연습 중인 표현 복습하기",
    reviewNewCta: "새 문장 복습하기",
    reviewTodayEmpty: "아직 복습할 표현이 없어요. 채팅에서 표현을 저장해 보세요.",
    learningBackToChat: "← 채팅으로",
    dashboardSavedToday: "오늘 저장",
    dashboardTotalCards: "총 카드",
    dashboardTotalCardsSubtle: "총 {count}개 표현",
    dashboardPracticing: "연습 중",
    dashboardUsable: "익숙한 표현",
    cardMySentence: "내가 실제로 쓴 문장",
    cardBetterExpression: "더 좋은 표현",
    cardMoreNatural: "또 다른 표현",
    cardPoint: "포인트",
    practiceAgain: "🔁 다시 연습",
    deleteFromBook: "🗑 삭제",
    reviewFrontHint: "내가 실제로 썼던 문장",
    reviewReveal: "정답 보기",
    reviewForgot: "아직 어려움",
    reviewVague: "애매함",
    reviewFamiliar: "익숙함",
    reviewConfidencePrompt: "이 문장을 다음에 자연스럽게 쓸 수 있을 것 같나요?",
    progressStatusNew: "🆕 새 문장",
    progressStatusPracticing: "🔁 연습 중",
    progressStatusUsable: "✅ 익숙한 표현",
    progressSavedToday: "오늘 저장",
    progressNotReviewed: "아직 복습 전",
    progressReviewCount: "복습 {count}회",
    progressLastReviewedToday: "마지막 복습 오늘",
    progressLastReviewedYesterday: "마지막 복습 어제",
    progressLastReviewedDays: "마지막 복습 {count}일 전",
    archive: "리포트",
    archiveEmpty: "저장된 표현이 없습니다.",
    savedItemsTab: "저장한 표현",
    sessionsTab: "학습 리포트",
    sessionsEmpty:
      "아직 완료된 학습 리포트가 없습니다.\n세션을 종료하면 리포트가 생성됩니다.",
    openSession: "리포트 보기",
    clearSessions: "리포트 전체 삭제",
    freeTraining: "자유 연습",
    messagesUsed: "사용 메시지",
    resetArchive: "아카이브 초기화",
    closeArchive: "닫기",
    reportMenuTitle: "리포트",
    reportListTitle: "완료된 학습",
    reportListEmpty:
      "아직 완료된 학습 리포트가 없습니다.\n대화를 끝내고 세션을 종료하면 리포트가 만들어져요.",
    reportClearAll: "전체 삭제",
    reportViewCta: "리포트 보기",
    reportTurnCount: "{count}개 대화",
    reportScoreLabel: "{score}점",
    reportDetailBadge: "세션 학습 리포트",
    reportTodayLearning: "오늘의 학습",
    reportStatExpressions: "표현",
    reportStatCorrections: "교정",
    reportStatTakeaways: "가져갈 표현",
    reportTimelineTitle: "대화 돌아보기",
    reportSummaryTitle: "대화 회고",
    reportScoreTitle: "이번 세션 점수",
    reportScoreInsufficient:
      "점수를 계산하기에는 대화량이 부족해요. 조금 더 대화한 뒤 세션을 종료해 보세요.",
    reportScoreNativeHint:
      "자연스러움 25점은 원어민, 0점은 {targetLanguage}를 거의 모르는 수준이에요. 문법은 이 점수에 넣지 않아요.",
    reportScoreBreakdownTitle: "점수 구성",
    reportScoreFactorAccuracy: "정확도",
    reportScoreFactorNaturalness: "자연스러움",
    reportScoreFactorFluency: "말하기 길이",
    reportScoreFactorSpoken: "구어 표현",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "잘한 점",
    reportImprovementsTitle: "개선할 점",
    reportMyExpression: "내 표현",
    reportBetterExpression: "더 자연스럽게",
    reportLearningTitle: "오늘 가져갈 표현",
    reportShowTranscript: "전체 대화 보기",
    reportHideTranscript: "전체 대화 숨기기",
    reportTranscriptReadonly:
      "읽기 전용입니다. 이 기록에서는 대화를 이어갈 수 없어요.",
    reportTranscriptYou: "나",
    reportTranscriptAi: "AI",
    reportReviewTitle: "대화 돌아보기",
    reportReviewHint: "그때 채팅 화면을 그대로 다시 볼 수 있어요.",
    reportReviewEmpty: "이 세션에 저장된 대화가 없어요.",
    reportChatCaptureLabel: "채팅 다시보기",
    reportLightCorrectionLabel: "자연스럽게",
    reportReviewDoneTitle: "대화를 모두 돌아봤어요.",
    reportReviewDoneBody: "이제 오늘 사용한 {targetLanguage}를 자세히 살펴볼까요?",
    reportGotoAnalysis: "상세 분석 보기",
    reportAnalysisTitle: "상세 분석",
    reportAnalysisHint: "이번 대화에서 실제로 쓴 {targetLanguage}를 근거로, 잘 쓴 표현과 더 자연스럽게 이어갈 방법을 살펴봐요.",
    reportExpressionsTitle: "표현 알아보기",
    reportExpressionsHint: "한국어로 물어본 뒤 대화에 넣은 {targetLanguage} 표현이에요.",
    reportExpressionIntent: "말하려고 한 것",
    reportExpressionUsed: "대화에 넣은 표현",
    reportExpressionSimpler: "더 쉽게",
    reportExpressionNative: "더 원어민스럽게",
    reportExpressionAnalysis: "이 문장 분석",
    reportAnalysisEmpty:
      "아직 대화가 짧아서 사용 습관을 판단하기 어려워요. 조금 더 대화하면 패턴을 분석할 수 있어요.",
    reportAnalysisStrengthsTitle: "잘하고 있어요",
    reportAnalysisImprovementsTitle: "개선해 보세요",
    reportAnalysisHabitsTitle: "대화 습관",
    reportAnalysisNextGoalTitle: "다음 대화 목표",
    reportAnalysisGenerating: "대화를 분석하는 중...",
    reportAnalysisCategoryNatural: "자연스러운 표현",
    reportAnalysisCategoryNuance: "뉘앙스",
    reportAnalysisCategoryWordChoice: "단어 선택",
    reportAnalysisCategoryTone: "말투",
    reportAnalysisCategoryFlow: "대화 흐름",
    reportAnalysisCategoryVariety: "표현 다양성",
    reportAnalysisCategoryConnection: "연결",
    reportAnalysisCategoryExpression: "생각 표현",
    reportAnalysisCategoryConversation: "대화 전략",
    reportAnalysisCategoryImprovement: "개선 포인트",
    reportAnalysisStrengthLabel: "잘한 표현",
    reportAnalysisWhyGood: "왜 좋았나요?",
    reportAnalysisCorrected: "교정",
    reportAnalysisWhy: "왜?",
    reportAnalysisAlternative: "다른 방식으로 말하면",
    reportAnalysisExample: "예문",
    reportTakeawaysTitle: "오늘 가져갈 것",
    reportTakeawaysHint: "오늘 이것만 기억해도 충분해요.",
    reportTakeawaysEmpty: "가져갈 핵심 표현이 아직 없어요.",
    reportCreatedToast: "학습 리포트가 저장됐어요",
    quizReadyToast: "복습 자료가 준비됐어요. 복습 탭에서 확인해 보세요.",
    reportSessionsTab: "세션 리포트",
    reportMonthlyTab: "월별 리포트",
    reportBack: "← 리포트",
    monthlyOpenFull: "월별 리포트 보기",
    homeTabChat: "채팅",
    homeTabSessions: "세션",
    homeTabMonthly: "월별",
    homeTabReports: "리포트",
    homeTabSaved: "표현",
    homeTabVocab: "단어장",
    homeTabQuiz: "문장 검색",
    homeTabRead: "웹 읽기",
    homeTabVideo: "영상 학습",
    homeTabStudy: "자료 학습",
    studyLibraryTitle: "내 학습자료",
    studyAdd: "+ 자료 추가",
    studyAddImage: "이미지",
    studyDropHint: "파일을 선택하거나 여기에 놓으세요.\nPDF, EPUB, TXT를 읽을 수 있어요.",
    studyOpen: "열기",
    studyContinue: "이어서 읽기",
    studyDelete: "삭제",
    studyBack: "← 목록",
    studyEmpty: "아직 올린 자료가 없어요.\n책·PDF·텍스트를 추가하고 읽다가\n모르는 문장을 눌러 분석하세요.",
    studySavedExpressions: "저장한 표현 {count}",
    studyAnalyzedSentences: "분석한 문장 {count}",
    studyPages: "{current} / {total} 페이지",
    studyStageReading: "파일 읽는 중...",
    studyStageExtracting: "텍스트 추출 중...",
    studyStageNormalizing: "문서 정리 중...",
    studyStageReady: "준비 완료",
    studyUnsupported: "이 파일 형식은 아직 지원하지 않습니다.",
    studyProtected: "이 파일은 보호되어 있어 현재 불러올 수 없습니다.",
    studyNoText: "이 PDF에서는 텍스트를 찾지 못했습니다.",
    studyTooLarge: "파일이 너무 커서 불러올 수 없습니다.",
    studyImageSoon: "사진으로 읽는 기능은 잠시 꺼 두었어요. PDF, EPUB, TXT를 이용해 주세요.",
    studyImageHint: "아래 문장을 누르면 해석과 분석을 볼 수 있어요. 사진은 두 손가락으로 확대할 수 있어요.",
    studySelectGloss: "뜻",
    studySelectHint: "문장을 누르면 해석과 분석을 볼 수 있어요. 두 손가락으로 확대할 수 있어요.",
    studyChapterPrev: "이전",
    studyChapterNext: "다음",
    studyOcrPage: "이 페이지의 글자를 찾는 중...",
    studyZoomIn: "확대",
    studyZoomOut: "축소",
    studyFailed: "자료를 불러오지 못했어요. 다른 파일로 시도해 주세요.",
    studyResumeHint: "이전에 {percent}%까지 읽었습니다.",
    learningLanguageLabel: "학습 언어",
    uiLanguageLabel: "UI 언어",
    videoLearnHeadline: "영상으로 {targetLanguage} 배우기",
    videoLearnBody:
      "이번 달 라이브러리에서 고르거나, 링크를 붙여 직접 가져올 수 있어요. 라이브러리는 차감이 없고, 가져오기는 3분당 1포인트예요.",
    videoLearnUrlPlaceholder: "YouTube 영상 링크를 붙여넣으세요",
    videoLearnLoad: "영상 불러오기",
    videoLearnInvalidUrl: "YouTube 영상 링크를 입력해 주세요.",
    videoLearnGenerating: "{targetLanguage} 자막을 준비하는 중...",
    videoLearnStepSpeech: "대화 내용 추출",
    videoLearnStepContext: "주제·장면 정리",
    videoLearnStepTranslate: "한국어 학습자료 생성",
    videoLearnStepCleanup: "재생 준비",
    videoLearnWhy: "이 표현은 뭐야?",
    videoLearnWhyDetail: "한국어로는 이런 느낌이에요",
    videoLearnSave: "저장",
    videoLearnSavedToast: "학습자료에 저장했어요",
    videoLearnTranscriptShow: "전체 자막 보기",
    videoLearnTranscriptHide: "전체 자막 닫기",
    videoLearnKeyExpression: "핵심 표현",
    videoLearnMeaningHere: "이 문장에서의 의미",
    videoLearnNuance: "뉘앙스",
    videoLearnSimilar: "비슷한 표현",
    videoLearnBack: "다른 영상",
    videoLearnIdleCue: "학습자료에서 구간을 골라 보세요.",
    videoLearnIdleEnglish: "재생하면 이 구간의 {targetLanguage} 자막이 여기에 나와요.",
    videoLearnFailed: "자막을 만들지 못했어요. 잠시 후 다시 시도해 주세요.",
    videoLearnNoSpeech: "이 영상에서 음성을 찾지 못했어요.",
    videoLearnWrongLanguage:
      "이 영상은 학습 언어와 달라요. {targetLanguage}로 된 영상을 골라 주세요.",
    videoLearnQuotaReached:
      "이번 달 가져오기 포인트를 다 썼어요. 라이브러리와 저장한 영상은 다시 볼 수 있어요.",
    videoLearnTooLong:
      "이 영상은 15분을 넘어서 준비할 수 없어요.",
    videoLearnQuotaHint:
      "가져오기 {used}/{limit}포인트 · 3분당 1포인트 · 라이브러리·저장 영상은 차감 없음",
    videoLearnLibraryTitle: "이번 달 라이브러리",
    videoLearnLibrarySubtitleFree:
      "무료 체험 {used}/{limit}편 · 매달 채워지지 않아요. 구독하면 이번 달 전체를 볼 수 있어요.",
    videoLearnLibrarySubtitlePremium:
      "이번 달 학습 팩 · 포인트 차감 없음",
    videoLearnLibraryEmpty:
      "이 언어 라이브러리는 아직 준비 중이에요. 프리미엄이면 링크를 붙여 가져올 수 있어요.",
    videoLearnLibraryTrial: "체험",
    videoLearnLibraryLocked: "잠김",
    videoLearnImportLocked:
      "직접 가져오기는 프리미엄에서 포인트를 씁니다.",
    videoLearnCatalogLocked:
      "이 편은 프리미엄 라이브러리예요.",
    videoLearnMoreGenerating: "나머지 해석을 만들고 있어요…",
    videoLearnWaitingGloss: "해석이 준비되면 재생합니다",
    videoLearnStudyTitle: "{targetLanguage} 문장",
    videoLearnStudyHint:
      "문장을 누르면 그 구간만 재생됩니다. 왼쪽 막대를 누르면 문장 분석이 열리고, 그 안에서 단어를 고를 수 있어요.",
    videoLearnStudyEmpty: "아직 추출된 문장이 없어요.",
    videoLearnRangeMode: "구간 묶기",
    videoLearnRangeHint:
      "구간 묶기를 누른 뒤, 위·아래 문장을 눌러 범위를 고르세요. 끝 구간을 다시 누르면 줄어듭니다.",
    videoLearnPlayRange: "묶어서 듣기",
    videoLearnClearRange: "선택 해제",
    videoLearnMergeCues: "구간 통합",
    videoLearnSplitCue: "구간 쪼개기",
    videoLearnMergeNeedRange: "위·아래 문장을 눌러 2개 이상 고른 뒤 통합하세요.",
    videoLearnBundleGaugeHint:
      "게이지를 위·아래로 밀어도 됩니다. 빨간 점은 지금 구간입니다.",
    videoLearnBundleClickHint:
      "위·아래 문장을 눌러 범위에 넣으세요. 끝 구간을 다시 누르면 줄어들어요.",
    videoLearnBundleUp: "위",
    videoLearnBundleDown: "아래",
    videoLearnSplitTooShort: "이 구간은 너무 짧아서 쪼갤 수 없어요.",
    videoLearnSplitNeedSelection:
      "게이지를 움직여 앞·뒤 경계를 정한 뒤 쪼개기를 확정하세요.",
    videoLearnSplitHint:
      "구간 쪼개기를 누르면 게이지가 나와요. 앞·뒤를 조절한 뒤 확정하세요.",
    videoLearnSplitSliderHint: "막대를 좌우로 움직여 쪼갤 위치를 정하세요.",
    videoLearnSplitFront: "앞",
    videoLearnSplitBack: "뒤",
    videoLearnSplitConfirm: "이 위치에서 쪼개기",
    videoLearnSplitCancel: "취소",
    videoLearnCuesEditedToast: "구간을 수정했어요",
    videoLearnUndoMerge: "묶기 취소",
    videoLearnUndoSplit: "쪼개기 취소",
    videoLearnUndoEdit: "이전으로",
    videoLearnResetAllCues: "원상태 복구",
    videoLearnUndoMergeToast: "묶기 전으로 되돌렸어요",
    videoLearnUndoSplitToast: "쪼개기 전으로 되돌렸어요",
    videoLearnResetAllCuesToast: "구간을 처음 상태로 되돌렸어요",
    videoLearnFullscreen: "전체화면",
    videoLearnFullscreenExit: "전체화면 종료",
    videoLearnFullscreenHint: "아래 얇은 바를 누르면 그 구간만 재생해요.",
    videoLearnWatchHint:
      "{targetLanguage} 자막을 보며 들으세요. 문장을 누르면 그 구간만 재생되고, 왼쪽 막대로 문장 분석을 연 뒤 단어를 고를 수 있어요.",
    videoLearnSaveSession: "이 영상 학습자료 저장",
    videoLearnSessionSaved: "저장됨",
    videoLearnSessionSavedToast: "영상 학습자료를 저장했어요. 나중에 다시 볼 수 있어요.",
    videoLearnSavedSessions: "저장된 영상 학습",
    videoLearnOpenSession: "이어서 학습",
    videoLearnDeleteSession: "삭제",
    videoLearnSessionLines: "문장",
    videoLearnSessionDeletedToast: "저장한 학습자료를 삭제했어요",
    discoverCta: "학습자료 찾아보기",
    discoverCtaHint: "직접 찾기 어려우신가요? 관심사로 실제 콘텐츠를 추천해 드려요.",
    discoverTitle: "학습자료 찾기",
    discoverSubtitle: "공개 소스에서 실제 영상·글을 찾아 기존 학습 기능으로 연결합니다.",
    discoverChannelsLabel: "내 채널",
    discoverTabChannels: "채널",
    discoverTabTopics: "카테고리",
    discoverChannelSearch: "채널 찾기",
    discoverChannelSearchPlaceholder: "예: BBC News, HugoDécrypte",
    discoverChannelAdd: "추가",
    discoverChannelAdded: "추가됨",
    discoverChannelRemove: "삭제",
    discoverChannelOpen: "채널 영상 보기",
    discoverChannelEmpty:
      "채널을 검색해 추가하세요. 아이콘이나 이름을 누르면 그 채널 영상을 가져와요.",
    discoverChannelSearchEmpty: "채널을 찾지 못했어요.",
    discoverChannelSubscribers: "구독자 {count}",
    discoverClose: "접기",
    discoverTopicLabel: "관심 주제",
    discoverTopicPlaceholder: "예: 여행, 축구, 일상 대화",
    discoverTopicAny: "전체",
    discoverTopicDaily: "일상 대화",
    discoverTopicTravel: "여행",
    discoverTopicFood: "음식·요리",
    discoverTopicWork: "직장·비즈니스",
    discoverTopicNews: "뉴스·시사",
    discoverTopicSchool: "공부·학교",
    discoverTopicEntertainment: "예능·드라마",
    discoverTopicSports: "스포츠",
    discoverTopicTech: "IT·과학",
    discoverTopicCulture: "문화·사회",
    discoverTopicHealth: "건강·라이프",
    discoverTopicMusic: "음악",
    discoverTopicFamily: "가족·육아",
    discoverTopicInterview: "인터뷰·토크",
    discoverTopicVlog: "브이로그",
    discoverTopicShopping: "쇼핑·패션",
    discoverTopicFinance: "경제·재테크",
    discoverTopicNature: "자연·동물",
    discoverTopicHobbies: "취미·게임",
    discoverNaturalLabel: "검색어로 찾기 (선택)",
    discoverNaturalPlaceholder: "예: 친구랑 수다, 축구 인터뷰",
    discoverTypeVideo: "영상",
    discoverTypeReading: "읽기",
    discoverDurationLabel: "길이",
    discoverDurationShort: "짧게",
    discoverDurationMedium: "보통",
    discoverDurationLong: "길게",
    discoverDurationAny: "상관없음",
    discoverLevelLabel: "난이도",
    discoverLevelAny: "상관없음",
    discoverLevelBeginner: "초급",
    discoverLevelIntermediate: "중급",
    discoverLevelAdvanced: "고급",
    discoverCaptionsLabel: "자막",
    discoverCaptionsAny: "상관없음",
    discoverCaptionsOriginal: "공식 자막 있음",
    discoverCaptionsBadge: "공식 자막",
    discoverImportPoints: "{n}포인트",
    discoverSearch: "자료 찾기",
    discoverMore: "더 보기",
    discoverFindingMore: "뒤에서 더 찾아 두는 중…",
    discoverSearching: "찾는 중…",
    discoverNeedTopic: "관심 주제를 선택하거나 자연어 검색어를 입력해 주세요.",
    discoverEmpty: "조건에 맞는 자료를 찾지 못했어요. 주제나 길이를 조금 넓혀보세요.",
    discoverFailed: "자료를 찾지 못했어요. 잠시 후 다시 시도해 주세요.",
    discoverYoutubeUnavailable:
      "YouTube 검색이 아직 설정되지 않았어요. URL을 직접 붙여넣어 학습할 수 있어요.",
    discoverProviderQuota: "검색 한도를 잠시 넘었어요. 조금 뒤 다시 시도하거나 URL을 직접 입력해 주세요.",
    discoverProviderFailed: "외부 검색에 실패했어요. URL을 직접 입력해 학습할 수 있어요.",
    discoverOpenPreview: "재생",
    discoverOpenRead: "읽기",
    discoverLearn: "학습하기",
    discoverReadingMinutes: "예상 {minutes}분",
    webReadHeadline: "{targetLanguage} 콘텐츠를 읽다가\n궁금한 표현을 바로 분석해보세요.",
    webReadHowTo:
      "다른 앱에서 문장을 길게 눌러 선택한 뒤, 메뉴의 「분석」을 누르면 이 앱의 문장 분석이 열립니다.\n브라우저 오버레이로 화면의 문장을 눌러도 됩니다.",
    webReadReadingTitle: "이어서 읽고 분석하세요",
    webReadUrlPlaceholder: "URL을 입력하세요",
    webReadOpen: "열기",
    webReadResume: "이어서 읽기",
    webReadPastePlaceholder: "고른 {targetLanguage}를 붙여넣어도 됩니다",
    webReadBack: "뒤로",
    webReadForward: "앞으로",
    webReadReload: "새로고침",
    webReadHome: "웹 읽기 종료",
    webReadInvalidUrl: "올바른 주소를 입력해 주세요.",
    webReadLoadError: "페이지를 열지 못했어요. 주소와 연결을 확인해 주세요.",
    webReadUnsupported: "이 주소는 열 수 없어요.",
    webReadNoSelection: "분석할 문장이나 표현을 선택해 주세요.",
    webReadWebLimited:
      "선택한 {targetLanguage}를 아래에 붙여 넣어도 됩니다.",
    webReadSelectionHint:
      "다른 앱에서 글을 고른 뒤 「분석」을 누르세요. 문장 분석 창이 이 앱에서 열립니다.",
    webReadNeedOverlay:
      "다른 앱 위에 표시와 화면 녹화 허용이 필요합니다.",
    webReadShortcutReddit: "Reddit",
    webReadShortcutBbc: "BBC",
    webReadShortcutOther: "Guardian",
    exploreHeadline: "이 {targetLanguage}, 왜 이렇게 표현할까요?",
    exploreHint: "궁금한 {targetLanguage} 문장이나 표현을 입력해보세요.",
    explorePlaceholder: "I used to go there when...",
    exploreSubmit: "분석하기",
    exploreRecent: "최근 분석",
    exploreLoading: "문장을 살펴보는 중...",
    exploreFailed: "분석을 불러오지 못했어요. 다시 시도해 주세요.",
    exploreTapHint: "궁금한 부분을 눌러보세요.",
    exploreWhy: "왜 이렇게 쓰였나요?",
    exploreUsage: "기본적인 사용",
    exploreOtherUsages: "다른 쓰임",
    exploreMeaningHere: "이 문장에서는",
    analysisSpokenAlso: "처음 해석",
    dimensionSyntax: "문법 구조",
    dimensionUsage: "쓰임",
    dimensionPhonology: "발음",
    dimensionMorphology: "형태",
    dimensionPragmatics: "뉘앙스",
    dimensionEtymology: "유래",
    analysisKeyElements: "알아두면 좋아요",
    quizTodayTitle: "오늘의 복습",
    quizTodaySubtitle: "최근 대화에서 헷갈렸던 내용을 다시 연습해요.",
    quizMissionPrompt: "어제 배운 내용을\n2분만 복습해볼까요?",
    quizTodayCountLabel: "오늘의 문제",
    quizRecentReviewTitle: "최근 복습",
    quizTodayCardTitle: "오늘의 복습",
    quizTodayMeta: "{count}문제 · 약 {minutes}분",
    quizCompositionGrammar: "문법 {count}",
    quizCompositionVocab: "단어 {count}",
    quizCompositionExpression: "표현 {count}",
    quizStartCta: "복습 시작",
    quizContinueCta: "이어서 풀기",
    quizReviewAgainCta: "새 문제로 다시 풀기",
    quizCreateNewCta: "퀴즈 새로 만들기",
    quizTodayFinished: "오늘 이 학습 복습은 끝났어요. 내일 다시 만나요.",
    quizGenerating: "문제 만드는 중...",
    quizGenerateFailed: "문제를 만들지 못했어요. 잠시 후 다시 시도해 주세요.",
    quizLoading: "불러오는 중...",
    quizEmptyTitle: "아직 복습할 내용이 없어요.",
    quizEmptyBody:
      "채팅에서 문장을 쓰고 단어를 저장하면\n문법과 단어 복습 자료가 준비돼요.",
    quizEmptyCta: "{targetLanguage}로 대화하기",
    reviewFilterAll: "전체",
    reviewFilterGrammar: "문법",
    reviewFilterVocab: "단어",
    reviewMySentence: "내가 쓴 문장",
    reviewBetterSentence: "이렇게 바꿔보세요",
    reviewExamples: "예문",
    reviewSimilar: "비슷한 단어",
    reviewRefresh: "자료 다시 만들기",
    reviewGenerating: "복습 자료 만드는 중...",
    reviewGenerateFailed: "복습 자료를 만들지 못했어요.",
    reviewEmptyBody:
      "채팅에서 단어를 저장하면\n틀린 문법과 저장한 단어로 복습 자료가 생겨요.",
    reviewCompleteCta: "복습 완료",
    reviewResetCta: "초기화",
    reviewSectionFallback: "복습 {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ 정답이에요",
    quizIncorrect: "다시 확인해볼까요?",
    quizNext: "다음 문제",
    quizSeeResult: "결과 보기",
    quizCompleteTitle: "오늘 복습 완료 ✓",
    quizCompleteScore: "{total}문제 중 {correct}문제를 맞혔어요.",
    quizRememberedTitle: "잘 기억하고 있어요",
    quizReviewAgainTitle: "다시 볼 내용",
    quizBackHome: "복습 홈으로",
    quizAlreadyDone: "오늘 복습을 이미 완료했어요.",
    quizTypeGrammar: "문법",
    quizTypeVocabulary: "단어",
    quizTypeExpression: "표현",
    homeBack: "← 홈",
    homeHubBadge: "홈",
    homeHubSubtitle: "오늘 연습할 곳을 골라 보세요.",
    homeOpenCta: "열기",
    homeDestChatDesc: "{targetLanguage}로 대화하고 교정받으며 연습합니다.",
    homeDestSessionsDesc: "완료한 세션의 학습 리포트를 돌아봅니다.",
    homeDestMonthlyDesc: "한 달 동안의 점수 성장과 학습을 확인합니다.",
    homeDestSavedDesc: "채팅에서 저장한 표현을 복습합니다.",
    homeDestVocabDesc: "모국어로 검색해 {targetLanguage} 단어를 저장합니다.",
    vocabTitle: "단어장",
    vocabFilterAll: "전체",
    vocabFilterWords: "단어",
    vocabFilterPhrases: "표현",
    vocabStatusLearning: "학습 중",
    vocabStatusFamiliar: "익숙함",
    vocabQueryHint: "UI 언어로 검색하면 {targetLanguage} 단어가 표시됩니다.",
    vocabSearchPlaceholder: "모국어로 단어 검색",
    vocabSearchCta: "검색",
    vocabSearching: "검색 중...",
    vocabResultsTitle: "검색 결과",
    vocabSavedTitle: "저장한 단어",
    vocabEmpty: "아직 저장한 단어가 없어요.\n위에서 검색해 추가해 보세요.",
    vocabHideGloss: "뜻 숨김",
    vocabShuffle: "랜덤 정렬",
    vocabRevealGloss: "눌러서 뜻 보기",
    vocabNoResults: "검색 결과가 없어요.",
    vocabSave: "저장",
    vocabSaved: "저장됨",
    vocabDelete: "삭제",
    vocabSavedToast: "단어장에 저장했어요",
    vocabSearchFailed: "검색에 실패했어요. 다시 시도해 주세요.",
    vocabSaveFromChat: "단어 확인",
    vocabPickTitle: "단어 선택",
    vocabPickHint: "채팅에 나온 단어를 눌러 단어장에 저장하세요.",
    vocabPickModeHint: "노란 표시는 단어, 하늘색은 숙어·복합어예요. 누르면 뜻을 볼 수 있어요.",
    vocabPickEmpty: "저장할 {targetLanguage} 단어가 아직 없어요. 먼저 대화를 나눠 보세요.",
    vocabPickCancel: "닫기",
    vocabPickSave: "{count}개 저장",
    vocabPickSaving: "저장 중...",
    vocabPickDone: "선택 완료",
    vocabPickSavedToast: "단어를 저장했어요",
    vocabPickNoneToast: "저장할 단어가 없어요",
    vocabPickFailed: "단어 저장에 실패했어요. 다시 시도해 주세요.",
    vocabPreviewLoading: "뜻을 불러오는 중...",
    vocabPreviewSave: "저장",
    vocabPreviewClose: "닫기",
    vocabOtherSenses: "다른 뜻",
    vocabTabSaved: "저장한 단어",
    vocabTabCharacters: "문자",
    characterGuideHint:
      "문자를 누르면 발음과 쓰임을 바로 확인할 수 있어요.",
    characterPronunciation: "발음",
    characterCategory: "종류",
    characterMeaning: "의미",
    characterUsage: "쓰임",
    characterTone: "성조",
    characterTone1: "1성",
    characterTone2: "2성",
    characterTone3: "3성",
    characterTone4: "4성",
    characterToneNeutral: "경성",
    characterExamples: "예시",
    characterForms: "단어 속 형태",
    characterFormIsolated: "단독",
    characterFormInitial: "앞",
    characterFormMedial: "가운데",
    characterFormFinal: "끝",
    chatHistoryTitle: "채팅 기록",
    chatHistoryListTitle: "이전 대화",
    chatHistoryEmpty:
      "아직 저장된 채팅이 없어요.\n대화를 시작하면 여기에 기록이 쌓여요.",
    chatHistoryContinue: "이어서 대화",
    chatHistoryNew: "새 대화 시작",
    chatHistoryClear: "기록 전체 삭제",
    chatHistoryCurrent: "현재",
    chatHistoryHasReport: "리포트 있음",
    createReport: "리포트 생성",
    chatCardsOn: "카드 켜짐",
    chatCardsOff: "카드 꺼짐",
    chatCardsLabel: "카드",
    toggleLegendOn: "켜짐",
    toggleLegendOff: "꺼짐",
    sessionSavedToHistoryToast: "채팅 기록에 저장했어요",
    reportCreateEmptyToast: "리포트를 만들 대화가 아직 없어요",
    reportCreateConfirmTitle: "리포트를 만들까요?",
    reportCreateConfirmBody:
      "지금 대화를 마치고 이 내용으로 학습 리포트를 생성합니다. 계속할까요?",
    reportCreateConfirmCta: "리포트 생성",
    reportCreateConfirmCancel: "계속 대화하기",
    reportDailyLimitToast:
      "오늘은 무료 리포트를 이미 만들었어요. 프리미엄으로 더 만들 수 있어요.",
    monthlyGrowthTitle: "{month} {targetLanguage} 성장",
    monthlyCurrentScore: "현재 점수",
    monthlyChange: "평균 점수",
    monthlySessions: "완료한 학습",
    monthlySessionCount: "{count}회",
    monthlyEmpty:
      "아직 이번 달 학습 기록이 없어요.\n대화를 완료하면 여기에 성장 기록이 쌓여요.",
    monthlyNeedMoreForTrend:
      "리포트가 더 쌓이면 성장 흐름을 확인할 수 있어요.",
    monthlyChartTitle: "점수 성장",
    monthlyChartNoScores:
      "점수가 있는 세션이 아직 없어요.\n조금 더 길게 대화한 뒤 세션을 종료해 보세요.",
    monthlyChartTapHint: "그래프의 점을 누르면 그 시점의 리포트를 볼 수 있어요.",
    monthlyListTitle: "이번 달 학습",
    monthlyCalendarHint: "색이 칠해진 날을 누르면 그날의 리포트를 볼 수 있어요.",
    monthlyDayReportsTitle: "이날의 리포트",
    monthlyNoScore: "점수 없음",
    continuePractice: "이어서 연습하기",
    comeBackTomorrow: "내일 다시 하기",
    trainingDoneTitle: "오늘의 {targetLanguage} 훈련 완료 👍",
    trainingDoneBody: "내일 다시 이어서 연습해보세요",
    trainingDoneHint: "계속 연습하고 싶다면 이어서 대화할 수 있어요",
    delete: "삭제",
    reuse: "다시 쓰기",
    translating: "번역 중...",
    translation: "번역",
    translateFailed: "번역에 실패했어요. 다시 시도해 주세요.",
    dailyLimitReached:
      "오늘의 메시지 한도에 도달했어요. 내일 다시 시도해 주세요.",
    expressionHelperTitle: "💡 이렇게 말할 수 있어요",
    expressionSentHint: "이 표현으로 대화를 이어갔어요.",
    correctionTitle: "교정",
    noCorrectionNeeded: "수정할 필요가 없습니다.",
    correctionFeedbackCorrect: "👍 좋은 문장이에요! 아주 자연스러워요.",
    correctionFeedbackError: "💡 거의 다 됐어요. 작은 부분만 고쳐볼까요?",
    sessionComplete: "오늘의 {targetLanguage} 훈련을 완료했어요 👍",
    startNewSession: "새 대화 시작",
    endSession: "세션 종료",
    languageKorean: "한국어",
    languageEnglish: "English",
    languageSpanish: "Español",
    planPremium: "프리미엄 · 이번 달 라이브러리 + 가져오기 {limit}포인트",
    planFree: "무료 플랜 · 오늘 {used}/{limit}",
    upgradeCta: "프리미엄 업그레이드",
    paywallLimitBanner:
      "무료 한도에 도달했어요. 프리미엄으로 영상 학습을 이어갈 수 있어요.",
    paywallTitle: "프리미엄으로 계속 학습하기",
    paywallSubtitle:
      "프리미엄은 이번 달 학습 라이브러리 전체와, 직접 가져오기 80포인트를 줍니다. 라이브러리와 저장한 영상은 포인트가 나가지 않아요.",
    paywallBenefitsTitle: "프리미엄 혜택",
    paywallBenefits:
      "이번 달 학습 라이브러리 전체\n직접 가져오기 80포인트 (3분=1포인트)\n저장한 영상 다시 보기는 차감 없음\n하루 채팅 제한 해제",
    paywallCta: "월 9,900원으로 시작하기",
    paywallRestore: "구매 복원",
    paywallLater: "나중에 하기",
    paywallNativeOnly: "앱에서 결제를 진행할 수 있어요",
    paywallPurchasing: "결제 진행 중…",
    paywallRestoring: "복원 중…",
    paywallActivatedToast: "프리미엄이 활성화됐어요",
    paywallRestoredToast: "구매가 복원됐어요",
    paywallRestoreEmpty: "복원할 구매 내역이 없어요",
    paywallPurchaseFailed: "결제를 완료하지 못했어요. 다시 시도해 주세요.",
    paywallPurchaseTimeout:
      "결제 연결 시간이 초과됐어요. Play 스토어에서 설치한 앱인지 확인 후 다시 시도해 주세요.",
    paywallNoProduct:
      "결제 상품을 불러오지 못했어요. Play Console·RevenueCat 설정을 확인해 주세요.",
    paywallCancelled: "결제가 취소됐어요",
  },
  en: {
    appTitle: "{targetLanguage} correction chat",
    chatEmptyHint:
      "Example: \"I had a really busy day today.\"\nTry writing full sentences in your own words.",
    chatMode: "Chat in {targetLanguage}",
    askExpression: "Ask expression",
    inputPlaceholder: "Write your own {targetLanguage} (e.g. I went to the gym today.)",
    expressionPlaceholder: "Type what you want to say in Korean",
    send: "Send",
    chatStartCta: "AI starts",
    chatStartFailed: "Couldn’t start the conversation. Please try again.",
    chatAttachPhoto: "Photo",
    chatRemovePhoto: "Remove photo",
    chatCall: "Call",
    callTranscriptTitle: "Call transcript",
    chatCallNoPoints:
      "You're out of call points. They refill next month.",
    chatCalling: "Calling…",
    chatInCall: "On a call",
    chatMute: "Mute",
    chatUnmute: "Unmute",
    chatHangUp: "Hang up",
    chatCallEnded: "Call ended · {duration}",
    chatCallFailed: "Couldn't connect the call. Try again.",
    chatMicDenied: "Microphone permission is needed for a call.",
    chatNativeMode: "Chat",
    chatTutorMode: "Help",
    sessionMenu: "Menu",
    videoLearnCancelPrep: "Stop preparing",
    chatDuringCall: "The tutor answers out loud while you are on a call.",
    reportContent: "Report this reply",
    reportTitle: "Report AI content",
    reportSubtitle: "Tell us what was wrong with this AI-generated reply. We review reports and adjust the assistant.",
    reportReasonOffensive: "Offensive or inappropriate",
    reportReasonInaccurate: "Wrong or misleading",
    reportReasonUnsafe: "Unsafe or harmful advice",
    reportReasonOther: "Something else",
    reportNoteLabel: "Anything to add? (optional)",
    reportSubmit: "Send report",
    reportCancel: "Cancel",
    reportThanks: "Thanks — your report was sent.",
    reportFailed: "Couldn't send the report. Please try again.",
    billingOpen: "Plan",
    billingScreenTitle: "Plan & billing",
    billingFreeLabel: "Free",
    billingPremiumLabel: "Premium",
    billingClose: "Close",
    headerImportPoints: "{remaining} pts",
    chatReading: "Reading",
    translate: "Translate",
    listen: "Listen",
    insightAnalyze: "Analyze",
    inspectTabSentence: "Sentence",
    insightSaveWord: "Save word",
    insightLoading: "Looking at this expression...",
    insightFailed: "Couldn't load the explanation. Please try again.",
    insightClose: "Close",
    insightBack: "Previous",
    insightInSentence: "In this sentence",
    insightPattern: "Pattern",
    insightExamples: "More examples",
    insightTip: "Watch out",
    insightComparison: "Similar but different",
    insightHint: "Select the part you're curious about, then tap Analyze.",
    corrected: "Corrected",
    highlighted: "Highlighted mistakes",
    natural: "Another expression",
    correctionBlockTitle: "Correction",
    correctionMyLine: "What you wrote",
    correctionTryThis: "Try this instead",
    explanation: "Explanation",
    example: "Example",
    useThisExpression: "Use this expression",
    save: "Save expression",
    saved: "✔ Saved",
    savedToBookToast: "Saved to My {targetLanguage} Book ({count})\nYou can review this anytime.",
    learningBookNav: "My {targetLanguage} Book",
    learningBookTitle: "My {targetLanguage} Book",
    learningEmpty:
      "No saved expressions yet\n\nSave useful expressions while you chat\nand build your personal {targetLanguage} book",
    learningSearchPlaceholder: "Search my expressions",
    learningSearchNoResults: "No matching cards found.",
    learningFilterEmpty: "No cards match this filter.",
    filterAll: "All",
    filterNew: "New",
    filterPracticing: "Practicing",
    filterUsable: "Familiar",
    cardShowDetails: "Show details",
    cardHideDetails: "Show less",
    reviewPracticingCta: "Review Practicing Expressions",
    reviewNewCta: "Review New Expressions",
    reviewTodayEmpty: "Nothing to review yet. Save a few expressions from chat first.",
    learningBackToChat: "← Back to chat",
    dashboardSavedToday: "Saved Today",
    dashboardTotalCards: "Total cards",
    dashboardTotalCardsSubtle: "{count} total expressions",
    dashboardPracticing: "Practicing",
    dashboardUsable: "Familiar",
    cardMySentence: "What I actually wrote",
    cardBetterExpression: "Better expression",
    cardMoreNatural: "Another expression",
    cardPoint: "Key point",
    practiceAgain: "🔁 Practice again",
    deleteFromBook: "🗑 Remove",
    reviewFrontHint: "The sentence you wrote",
    reviewReveal: "Show answer",
    reviewForgot: "Still Hard",
    reviewVague: "Not Sure",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Do you think you could naturally use this sentence next time?",
    progressStatusNew: "🆕 New",
    progressStatusPracticing: "🔁 Practicing",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Saved today",
    progressNotReviewed: "Not reviewed yet",
    progressReviewCount: "{count} reviews",
    progressLastReviewedToday: "last reviewed today",
    progressLastReviewedYesterday: "last reviewed yesterday",
    progressLastReviewedDays: "last reviewed {count} days ago",
    archive: "Reports",
    archiveEmpty: "No saved items yet.",
    savedItemsTab: "Saved expressions",
    sessionsTab: "Learning reports",
    sessionsEmpty:
      "No completed learning reports yet.\nEnd a session to create one.",
    openSession: "View report",
    clearSessions: "Clear all reports",
    freeTraining: "Free training",
    messagesUsed: "Messages used",
    resetArchive: "Reset archive",
    closeArchive: "Close",
    reportMenuTitle: "Reports",
    reportListTitle: "Completed sessions",
    reportListEmpty:
      "No completed learning reports yet.\nFinish a chat and end the session to create one.",
    reportClearAll: "Clear all",
    reportViewCta: "View report",
    reportTurnCount: "{count} turns",
    reportScoreLabel: "{score} pts",
    reportDetailBadge: "Session learning report",
    reportTodayLearning: "Today’s learning",
    reportStatExpressions: "Expressions",
    reportStatCorrections: "Corrections",
    reportStatTakeaways: "Takeaways",
    reportTimelineTitle: "Conversation",
    reportSummaryTitle: "Conversation recap",
    reportScoreTitle: "Session score",
    reportScoreInsufficient:
      "Not enough conversation to score reliably. Chat a bit more, then end the session.",
    reportScoreNativeHint:
      "Naturalness: 25 = native speaker, 0 = almost no {targetLanguage}. Grammar is scored separately.",
    reportScoreBreakdownTitle: "Score breakdown",
    reportScoreFactorAccuracy: "Accuracy",
    reportScoreFactorNaturalness: "Naturalness",
    reportScoreFactorFluency: "Turn length",
    reportScoreFactorSpoken: "Spoken style",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "What went well",
    reportImprovementsTitle: "What to improve",
    reportMyExpression: "Your line",
    reportBetterExpression: "More natural",
    reportLearningTitle: "Expressions to take with you",
    reportShowTranscript: "View full conversation",
    reportHideTranscript: "Hide conversation",
    reportTranscriptReadonly:
      "Read-only — you can’t continue this chat from here.",
    reportTranscriptYou: "You",
    reportTranscriptAi: "AI",
    reportReviewTitle: "Conversation review",
    reportReviewHint: "See the chat exactly as it looked at the time.",
    reportReviewEmpty: "No conversation saved for this session.",
    reportChatCaptureLabel: "Chat replay",
    reportLightCorrectionLabel: "More natural",
    reportReviewDoneTitle: "You’ve reviewed the full conversation.",
    reportReviewDoneBody: "Ready to look closely at the {targetLanguage} you used?",
    reportGotoAnalysis: "View detailed analysis",
    reportAnalysisTitle: "Detailed analysis",
    reportAnalysisHint: "Based on the {targetLanguage} you actually used — what worked, and how to take it further.",
    reportExpressionsTitle: "How to say it",
    reportExpressionsHint: "{targetLanguage} you put into the chat after asking in your language.",
    reportExpressionIntent: "What you meant",
    reportExpressionUsed: "Line used in chat",
    reportExpressionSimpler: "Simpler",
    reportExpressionNative: "More native",
    reportExpressionAnalysis: "Sentence notes",
    reportAnalysisEmpty:
      "This chat is still short, so it’s hard to judge habits. Talk a bit more and we can analyze the pattern.",
    reportAnalysisStrengthsTitle: "What went well",
    reportAnalysisImprovementsTitle: "Try this next",
    reportAnalysisHabitsTitle: "Conversation habits",
    reportAnalysisNextGoalTitle: "Next-chat goal",
    reportAnalysisGenerating: "Analyzing the conversation...",
    reportAnalysisCategoryNatural: "Natural phrasing",
    reportAnalysisCategoryNuance: "Nuance",
    reportAnalysisCategoryWordChoice: "Word choice",
    reportAnalysisCategoryTone: "Tone",
    reportAnalysisCategoryFlow: "Flow",
    reportAnalysisCategoryVariety: "Variety",
    reportAnalysisCategoryConnection: "Connection",
    reportAnalysisCategoryExpression: "Expression",
    reportAnalysisCategoryConversation: "Conversation",
    reportAnalysisCategoryImprovement: "To try next",
    reportAnalysisStrengthLabel: "Strong line",
    reportAnalysisWhyGood: "Why it worked",
    reportAnalysisCorrected: "Correction",
    reportAnalysisWhy: "Why?",
    reportAnalysisAlternative: "Another way to say it",
    reportAnalysisExample: "Example",
    reportTakeawaysTitle: "Takeaways",
    reportTakeawaysHint: "Remember just these for today.",
    reportTakeawaysEmpty: "No key takeaways for this session yet.",
    reportCreatedToast: "Learning report saved",
    quizReadyToast: "Your review materials are ready. Open the Review tab.",
    reportSessionsTab: "Session reports",
    reportMonthlyTab: "Monthly report",
    reportBack: "← Reports",
    monthlyOpenFull: "View monthly report",
    homeTabChat: "Chat",
    homeTabSessions: "Sessions",
    homeTabMonthly: "Monthly",
    homeTabReports: "Reports",
    homeTabSaved: "Saved",
    homeTabVocab: "Vocab",
    homeTabQuiz: "Explore",
    homeTabRead: "Web",
    homeTabVideo: "Video",
    homeTabStudy: "Library",
    studyLibraryTitle: "My study files",
    studyAdd: "+ Add file",
    studyAddImage: "Image",
    studyDropHint: "Choose a file or drop it here.\nPDF, EPUB, and TXT are supported.",
    studyOpen: "Open",
    studyContinue: "Continue reading",
    studyDelete: "Delete",
    studyBack: "← Library",
    studyEmpty: "No files yet.\nAdd a book, PDF, or text file,\nthen tap a sentence you don’t know.",
    studySavedExpressions: "{count} saved expressions",
    studyAnalyzedSentences: "{count} analyzed sentences",
    studyPages: "{current} / {total} pages",
    studyStageReading: "Opening file...",
    studyStageExtracting: "Extracting text...",
    studyStageNormalizing: "Organizing the document...",
    studyStageReady: "Ready",
    studyUnsupported: "This file type isn’t supported yet.",
    studyProtected: "This file is protected and can’t be opened.",
    studyNoText: "No text was found in this PDF.",
    studyTooLarge: "This file is too large to open.",
    studyImageSoon: "Photo reading is off for now. Please use PDF, EPUB, or TXT.",
    studyImageHint: "Tap a sentence below to see meaning and analysis. Pinch the photo to zoom.",
    studySelectGloss: "Meaning",
    studySelectHint: "Tap a sentence to see meaning and analysis. Pinch to zoom.",
    studyChapterPrev: "Previous",
    studyChapterNext: "Next",
    studyOcrPage: "Finding text on this page...",
    studyZoomIn: "Zoom in",
    studyZoomOut: "Zoom out",
    studyFailed: "Couldn’t load this file. Try another one.",
    studyResumeHint: "You left off at {percent}%.",
    learningLanguageLabel: "Learning language",
    uiLanguageLabel: "App language",
    videoLearnHeadline: "Learn {targetLanguage} from video",
    videoLearnBody:
      "Pick a title from this month’s library, or paste your own link. Library titles are free; custom links use import points.",
    videoLearnUrlPlaceholder: "Paste a YouTube link",
    videoLearnLoad: "Load video",
    videoLearnInvalidUrl: "Please enter a valid YouTube link.",
    videoLearnGenerating: "Preparing {targetLanguage} captions...",
    videoLearnStepSpeech: "Extracting dialogue",
    videoLearnStepContext: "Topic & scenes",
    videoLearnStepTranslate: "Building Korean study notes",
    videoLearnStepCleanup: "Ready to play",
    videoLearnWhy: "What's this expression?",
    videoLearnWhyDetail: "How it feels in Korean",
    videoLearnSave: "Save",
    videoLearnSavedToast: "Saved to your study notes",
    videoLearnTranscriptShow: "Show full transcript",
    videoLearnTranscriptHide: "Hide transcript",
    videoLearnKeyExpression: "Key expression",
    videoLearnMeaningHere: "Meaning in this line",
    videoLearnNuance: "Nuance",
    videoLearnSimilar: "Similar lines",
    videoLearnBack: "Another video",
    videoLearnIdleCue: "Pick a line from the study notes.",
    videoLearnIdleEnglish: "Play the video to see {targetLanguage} captions here.",
    videoLearnFailed: "Couldn't generate subtitles. Please try again.",
    videoLearnNoSpeech: "No speech was found in this video.",
    videoLearnWrongLanguage:
      "This video isn’t in your learning language. Pick a video in {targetLanguage}.",
    videoLearnQuotaReached:
      "You’ve used this month’s import points. Library and saved videos can still be replayed.",
    videoLearnTooLong:
      "This video is longer than 15 minutes, so it can’t be prepared.",
    videoLearnQuotaHint:
      "{used}/{limit} import points this month · 1 point per 3 minutes · library and saved videos are free",
    videoLearnLibraryTitle: "This month’s library",
    videoLearnLibrarySubtitleFree:
      "Free trial: {used}/{limit} episodes. It doesn’t refill each month — subscribe to open the full monthly pack.",
    videoLearnLibrarySubtitlePremium:
      "This month’s study pack · no points charged",
    videoLearnLibraryEmpty:
      "A library for this language isn’t ready yet. Premium members can paste a link instead.",
    videoLearnLibraryTrial: "Trial",
    videoLearnLibraryLocked: "Locked",
    videoLearnImportLocked:
      "Pasting your own link is a Premium feature and uses import points.",
    videoLearnCatalogLocked:
      "This episode is in the Premium library.",
    videoLearnMoreGenerating: "Finishing the remaining translations…",
    videoLearnWaitingGloss: "Playback waits until the translation is ready",
    videoLearnStudyTitle: "{targetLanguage} lines",
    videoLearnStudyHint:
      "Tap a line to play just that clip. Tap the bar on the left to open sentence analysis, then pick words there.",
    videoLearnStudyEmpty: "No lines extracted yet.",
    videoLearnRangeMode: "Link clips",
    videoLearnRangeHint:
      "Tap Link clips, then tap sentences above or below to set the range. Tap an end clip again to shrink.",
    videoLearnPlayRange: "Play linked clips",
    videoLearnClearRange: "Clear selection",
    videoLearnMergeCues: "Merge clips",
    videoLearnSplitCue: "Split clip",
    videoLearnMergeNeedRange: "Tap neighboring sentences to select 2 or more clips, then merge.",
    videoLearnBundleGaugeHint:
      "Slide the gauge up or down to set the range. The red dot is this clip.",
    videoLearnBundleClickHint:
      "Or tap clips above/below to include them. Tap an end clip again to shrink.",
    videoLearnBundleUp: "Up",
    videoLearnBundleDown: "Down",
    videoLearnSplitTooShort: "This clip is too short to split.",
    videoLearnSplitNeedSelection:
      "Move the gauge to set the front/back boundary, then confirm.",
    videoLearnSplitHint:
      "Tap Split clip to open a gauge. Slide front/back, then confirm.",
    videoLearnSplitSliderHint: "Drag the bar left or right to choose the split.",
    videoLearnSplitFront: "Front",
    videoLearnSplitBack: "Back",
    videoLearnSplitConfirm: "Split here",
    videoLearnSplitCancel: "Cancel",
    videoLearnCuesEditedToast: "Clips updated",
    videoLearnUndoMerge: "Undo merge",
    videoLearnUndoSplit: "Undo split",
    videoLearnUndoEdit: "Undo",
    videoLearnResetAllCues: "Restore original",
    videoLearnUndoMergeToast: "Restored clips from before the merge",
    videoLearnUndoSplitToast: "Restored clips from before the split",
    videoLearnResetAllCuesToast: "Restored the original clips",
    videoLearnFullscreen: "Fullscreen",
    videoLearnFullscreenExit: "Exit fullscreen",
    videoLearnFullscreenHint: "Tap a bar below to play that clip.",
    videoLearnWatchHint:
      "Watch with {targetLanguage} captions. Tap a line to play that clip. Tap the left bar to open sentence analysis, then pick words there.",
    videoLearnSaveSession: "Save this video study pack",
    videoLearnSessionSaved: "Saved",
    videoLearnSessionSavedToast: "Saved. You can reopen this video to keep studying.",
    videoLearnSavedSessions: "Saved video lessons",
    videoLearnOpenSession: "Continue studying",
    videoLearnDeleteSession: "Delete",
    videoLearnSessionLines: " lines",
    videoLearnSessionDeletedToast: "Removed saved video lesson",
    discoverCta: "Find learning content",
    discoverCtaHint: "Hard to find a link? We’ll recommend real content for your interests.",
    discoverTitle: "Find learning content",
    discoverSubtitle: "Discover real videos and articles from public sources, then open them in the existing study tools.",
    discoverChannelsLabel: "My channels",
    discoverTabChannels: "Channels",
    discoverTabTopics: "Topics",
    discoverChannelSearch: "Find channel",
    discoverChannelSearchPlaceholder: "e.g. BBC News, HugoDécrypte",
    discoverChannelAdd: "Add",
    discoverChannelAdded: "Added",
    discoverChannelRemove: "Remove",
    discoverChannelOpen: "Show channel videos",
    discoverChannelEmpty:
      "Search to add a channel. Tap the icon or name to load its videos.",
    discoverChannelSearchEmpty: "No channels found.",
    discoverChannelSubscribers: "{count} subscribers",
    discoverClose: "Collapse",
    discoverTopicLabel: "Topic",
    discoverTopicPlaceholder: "e.g. travel, football, casual chat",
    discoverTopicAny: "All",
    discoverTopicDaily: "Daily chat",
    discoverTopicTravel: "Travel",
    discoverTopicFood: "Food & cooking",
    discoverTopicWork: "Work & business",
    discoverTopicNews: "News",
    discoverTopicSchool: "School & study",
    discoverTopicEntertainment: "Shows & drama",
    discoverTopicSports: "Sports",
    discoverTopicTech: "Tech & science",
    discoverTopicCulture: "Culture & society",
    discoverTopicHealth: "Health & lifestyle",
    discoverTopicMusic: "Music",
    discoverTopicFamily: "Family",
    discoverTopicInterview: "Interview & talk",
    discoverTopicVlog: "Vlog",
    discoverTopicShopping: "Shopping & fashion",
    discoverTopicFinance: "Money & economy",
    discoverTopicNature: "Nature & animals",
    discoverTopicHobbies: "Hobbies & games",
    discoverNaturalLabel: "YouTube search (optional)",
    discoverNaturalPlaceholder: "e.g. chatting with friends, football interview",
    discoverTypeVideo: "Video",
    discoverTypeReading: "Reading",
    discoverDurationLabel: "Length",
    discoverDurationShort: "Short",
    discoverDurationMedium: "Medium",
    discoverDurationLong: "Long",
    discoverDurationAny: "Any",
    discoverLevelLabel: "Level",
    discoverLevelAny: "Any",
    discoverLevelBeginner: "Beginner",
    discoverLevelIntermediate: "Intermediate",
    discoverLevelAdvanced: "Advanced",
    discoverCaptionsLabel: "Captions",
    discoverCaptionsAny: "Any",
    discoverCaptionsOriginal: "Official captions",
    discoverCaptionsBadge: "Official captions",
    discoverImportPoints: "{n} pts",
    discoverSearch: "Find content",
    discoverMore: "Show more",
    discoverFindingMore: "Finding more in the background…",
    discoverSearching: "Searching…",
    discoverNeedTopic: "Pick a topic category or enter a natural-language request.",
    discoverEmpty: "No matching content. Try a broader topic or length.",
    discoverFailed: "Couldn’t find content. Please try again in a moment.",
    discoverYoutubeUnavailable:
      "YouTube search isn’t configured yet. You can still paste a URL to study.",
    discoverProviderQuota: "Search quota was hit. Try again later, or paste a URL.",
    discoverProviderFailed: "External search failed. You can still paste a URL.",
    discoverOpenPreview: "Preview",
    discoverOpenRead: "Read",
    discoverLearn: "Study",
    discoverReadingMinutes: "~{minutes} min",
    webReadHeadline: "Read {targetLanguage} on the web,\nthen analyze what you’re curious about.",
    webReadHowTo:
      "In any app, long-press to select a sentence, then tap Analyze in the menu. The same sentence analysis sheet opens here.\nYou can still use the on-screen overlay in the browser.",
    webReadReadingTitle: "Keep reading, then analyze",
    webReadUrlPlaceholder: "Enter a URL",
    webReadOpen: "Open",
    webReadResume: "Continue reading",
    webReadPastePlaceholder: "Or paste the {targetLanguage} you selected",
    webReadBack: "Back",
    webReadForward: "Forward",
    webReadReload: "Refresh",
    webReadHome: "Close page",
    webReadInvalidUrl: "Enter a valid address.",
    webReadLoadError: "Couldn’t open this page. Check the address and your connection.",
    webReadUnsupported: "This address can’t be opened.",
    webReadNoSelection: "Select some text to analyze.",
    webReadWebLimited:
      "You can also paste the {targetLanguage} below.",
    webReadSelectionHint:
      "Select text in another app, then tap Analyze. Sentence analysis opens in this app.",
    webReadNeedOverlay:
      "Allow display over other apps and screen capture.",
    webReadShortcutReddit: "Reddit",
    webReadShortcutBbc: "BBC",
    webReadShortcutOther: "Guardian",
    exploreHeadline: "Why is it said this way?",
    exploreHint: "Type an {targetLanguage} sentence or expression you’re curious about.",
    explorePlaceholder: "I used to go there when...",
    exploreSubmit: "Analyze",
    exploreRecent: "Recent",
    exploreLoading: "Looking at this sentence...",
    exploreFailed: "Couldn’t load the analysis. Please try again.",
    exploreTapHint: "Tap a part you’re curious about.",
    exploreWhy: "Why this form?",
    exploreUsage: "How to use it",
    exploreOtherUsages: "Other uses",
    exploreMeaningHere: "In this sentence",
    analysisSpokenAlso: "First reading",
    dimensionSyntax: "Grammar",
    dimensionUsage: "Usage",
    dimensionPhonology: "Pronunciation",
    dimensionMorphology: "Word form",
    dimensionPragmatics: "Nuance",
    dimensionEtymology: "Origin",
    analysisKeyElements: "Worth knowing",
    quizTodayTitle: "Today’s review",
    quizTodaySubtitle: "Practice what you struggled with in recent chats.",
    quizMissionPrompt: "Spend 2 minutes reviewing\nwhat you learned recently.",
    quizTodayCountLabel: "Today’s questions",
    quizRecentReviewTitle: "Recent review",
    quizTodayCardTitle: "Today’s review",
    quizTodayMeta: "{count} questions · about {minutes} min",
    quizCompositionGrammar: "Grammar {count}",
    quizCompositionVocab: "Words {count}",
    quizCompositionExpression: "Expressions {count}",
    quizStartCta: "Start review",
    quizContinueCta: "Continue",
    quizReviewAgainCta: "Try new questions",
    quizCreateNewCta: "Create a new quiz",
    quizTodayFinished: "That’s all for today’s review. Come back tomorrow.",
    quizGenerating: "Creating questions...",
    quizGenerateFailed: "Couldn’t create questions. Please try again.",
    quizLoading: "Loading...",
    quizEmptyTitle: "Nothing to review yet.",
    quizEmptyBody:
      "Chat in {targetLanguage} and save words,\nand grammar and vocabulary review cards will be ready.",
    quizEmptyCta: "Chat in {targetLanguage}",
    reviewFilterAll: "All",
    reviewFilterGrammar: "Grammar",
    reviewFilterVocab: "Words",
    reviewMySentence: "What you wrote",
    reviewBetterSentence: "Try this instead",
    reviewExamples: "Examples",
    reviewSimilar: "Similar words",
    reviewRefresh: "Rebuild materials",
    reviewGenerating: "Creating review materials...",
    reviewGenerateFailed: "Couldn’t create review materials.",
    reviewEmptyBody:
      "Save words while chatting.\nReview cards use your grammar mistakes and saved words.",
    reviewCompleteCta: "Done reviewing",
    reviewResetCta: "Clear all",
    reviewSectionFallback: "Review {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ Correct",
    quizIncorrect: "Let’s check that again",
    quizNext: "Next",
    quizSeeResult: "See results",
    quizCompleteTitle: "Today’s review done ✓",
    quizCompleteScore: "You got {correct} of {total} right.",
    quizRememberedTitle: "Looking solid",
    quizReviewAgainTitle: "Worth another look",
    quizBackHome: "Back to review home",
    quizAlreadyDone: "You’ve already finished today’s review.",
    quizTypeGrammar: "Grammar",
    quizTypeVocabulary: "Vocabulary",
    quizTypeExpression: "Expression",
    homeBack: "← Home",
    homeHubBadge: "Home",
    homeHubSubtitle: "Choose where you’d like to practice today.",
    homeOpenCta: "Open",
    homeDestChatDesc: "Practice {targetLanguage} in conversation with corrections.",
    homeDestSessionsDesc: "Review learning reports from completed sessions.",
    homeDestMonthlyDesc: "See this month’s score growth and learning.",
    homeDestSavedDesc: "Review expressions you saved from chat.",
    homeDestVocabDesc: "Search in your language and save {targetLanguage} words.",
    vocabTitle: "Vocabulary",
    vocabFilterAll: "All",
    vocabFilterWords: "Words",
    vocabFilterPhrases: "Phrases",
    vocabStatusLearning: "Learning",
    vocabStatusFamiliar: "Familiar",
    vocabQueryHint: "Search in your UI language to find {targetLanguage} words.",
    vocabSearchPlaceholder: "Search a word in your language",
    vocabSearchCta: "Search",
    vocabSearching: "Searching...",
    vocabResultsTitle: "Results",
    vocabSavedTitle: "Saved words",
    vocabEmpty: "No saved words yet.\nSearch above to add some.",
    vocabHideGloss: "Hide meanings",
    vocabShuffle: "Shuffle",
    vocabRevealGloss: "Tap to see meaning",
    vocabNoResults: "No results found.",
    vocabSave: "Save",
    vocabSaved: "Saved",
    vocabDelete: "Delete",
    vocabSavedToast: "Saved to vocabulary",
    vocabSearchFailed: "Search failed. Please try again.",
    vocabSaveFromChat: "Check words",
    vocabPickTitle: "Pick words",
    vocabPickHint: "Tap highlighted words in this chat to save them.",
    vocabPickModeHint: "Amber = word, sky = phrase/idiom. Tap to see the meaning, then Save.",
    vocabPickEmpty: "No {targetLanguage} words to save yet. Chat a bit first.",
    vocabPickCancel: "Close",
    vocabPickSave: "Save {count}",
    vocabPickSaving: "Saving...",
    vocabPickDone: "Done",
    vocabPickSavedToast: "Word saved",
    vocabPickNoneToast: "No words to save",
    vocabPickFailed: "Couldn’t save words. Please try again.",
    vocabPreviewLoading: "Loading meaning...",
    vocabPreviewSave: "Save",
    vocabPreviewClose: "Close",
    vocabOtherSenses: "Other meanings",
    vocabTabSaved: "Saved words",
    vocabTabCharacters: "Characters",
    characterGuideHint: "Tap a character to see how it sounds and how it’s used.",
    characterPronunciation: "Pronunciation",
    characterCategory: "Type",
    characterMeaning: "Meaning",
    characterUsage: "Usage",
    characterTone: "Tone",
    characterTone1: "1st tone",
    characterTone2: "2nd tone",
    characterTone3: "3rd tone",
    characterTone4: "4th tone",
    characterToneNeutral: "Neutral tone",
    characterExamples: "Examples",
    characterForms: "Shapes in a word",
    characterFormIsolated: "Isolated",
    characterFormInitial: "Initial",
    characterFormMedial: "Medial",
    characterFormFinal: "Final",
    chatHistoryTitle: "Chat history",
    chatHistoryListTitle: "Past chats",
    chatHistoryEmpty:
      "No saved chats yet.\nStart a conversation and it will show up here.",
    chatHistoryContinue: "Continue chat",
    chatHistoryNew: "Start new chat",
    chatHistoryClear: "Clear all",
    chatHistoryCurrent: "Current",
    chatHistoryHasReport: "Has report",
    createReport: "Create report",
    chatCardsOn: "Cards on",
    chatCardsOff: "Cards off",
    chatCardsLabel: "Cards",
    toggleLegendOn: "On",
    toggleLegendOff: "Off",
    sessionSavedToHistoryToast: "Saved to chat history",
    reportCreateEmptyToast: "No conversation yet to create a report",
    reportCreateConfirmTitle: "Create a report?",
    reportCreateConfirmBody:
      "This will end the current chat and create a learning report from it. Continue?",
    reportCreateConfirmCta: "Create report",
    reportCreateConfirmCancel: "Keep chatting",
    reportDailyLimitToast:
      "You’ve already made today’s free report. Go Premium for more.",
    monthlyGrowthTitle: "{month} growth",
    monthlyCurrentScore: "Current score",
    monthlyChange: "Average",
    monthlySessions: "Completed",
    monthlySessionCount: "{count}",
    monthlyEmpty:
      "No learning records this month yet.\nFinish a chat to start building your growth timeline.",
    monthlyNeedMoreForTrend:
      "Complete more reports to see your growth trend.",
    monthlyChartTitle: "Score growth",
    monthlyChartNoScores:
      "No scored sessions yet.\nChat a bit longer, then end the session.",
    monthlyChartTapHint: "Tap a point on the chart to open that session report.",
    monthlyListTitle: "This month’s learning",
    monthlyCalendarHint: "Tap a colored day to open that day’s report.",
    monthlyDayReportsTitle: "Reports this day",
    monthlyNoScore: "No score",
    continuePractice: "Continue Practice",
    comeBackTomorrow: "Come back tomorrow",
    trainingDoneTitle: "You've completed today's training 👍",
    trainingDoneBody: "Come back tomorrow to continue.",
    trainingDoneHint: "If you want, you can keep practicing now.",
    delete: "Delete",
    reuse: "Reuse",
    translating: "Translating...",
    translation: "Translation",
    translateFailed: "Translation failed. Please try again.",
    dailyLimitReached: "You reached today's message limit. Please come back tomorrow.",
    expressionHelperTitle: "💡 You can say it like this",
    expressionSentHint: "This line was sent into the chat.",
    correctionTitle: "Correction",
    noCorrectionNeeded: "No changes needed.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Today's practice is complete 🎯",
    startNewSession: "Start New Session",
    endSession: "End Session",
    languageKorean: "Korean",
    languageEnglish: "English",
    languageSpanish: "Spanish",
    planPremium: "Premium · this month’s library + {limit} import points",
    planFree: "Free plan · {used}/{limit} today",
    upgradeCta: "Upgrade to Premium",
    paywallLimitBanner: "You've reached a free limit. Go Premium to keep learning from video.",
    paywallTitle: "Keep learning with Premium",
    paywallSubtitle:
      "Premium opens this month’s study library and 80 import points for your own links. Saved videos and library titles don’t use points.",
    paywallBenefitsTitle: "Premium includes",
    paywallBenefits:
      "This month’s full study library\n80 import points for your own videos (3 min = 1 point)\nReplaying saved videos is free\nNo daily chat limit",
    paywallCta: "Start for ₩9,900/month",
    paywallRestore: "Restore purchases",
    paywallLater: "Not now",
    paywallNativeOnly: "You can complete payment in the app",
    paywallPurchasing: "Processing…",
    paywallRestoring: "Restoring…",
    paywallActivatedToast: "Premium is now active",
    paywallRestoredToast: "Your purchase was restored",
    paywallRestoreEmpty: "No purchases to restore",
    paywallPurchaseFailed: "We couldn't complete the purchase. Please try again.",
    paywallPurchaseTimeout:
      "The purchase timed out. Install the app from the Play Store, then try again.",
    paywallNoProduct:
      "We couldn't load the subscription product. Check Play Console and RevenueCat setup.",
    paywallCancelled: "Purchase cancelled",
  },
  es: {
    appTitle: "Chat de corrección de {targetLanguage}",
    chatEmptyHint:
      "Ejemplo: \"I had a really busy day today.\"\nEscribe frases completas con tus palabras.",
    chatMode: "Hablar en {targetLanguage}",
    askExpression: "Preguntar expresion",
    inputPlaceholder: "Escribe en {targetLanguage} con tus palabras (ej. I went to the gym today.)",
    expressionPlaceholder: "Escribe en coreano lo que quieres decir",
    send: "Enviar",
    chatStartCta: "Empieza la IA",
    chatStartFailed: "No se pudo empezar la conversación. Inténtalo de nuevo.",
    chatAttachPhoto: "Foto",
    chatRemovePhoto: "Quitar foto",
    chatCall: "Llamar",
    callTranscriptTitle: "Transcripción de la llamada",
    chatCallNoPoints:
      "Te quedaste sin puntos de llamada. Se recargan el próximo mes.",
    chatCalling: "Llamando…",
    chatInCall: "En llamada",
    chatMute: "Silenciar",
    chatUnmute: "Activar sonido",
    chatHangUp: "Colgar",
    chatCallEnded: "Llamada terminada · {duration}",
    chatCallFailed: "No se pudo conectar la llamada. Inténtalo de nuevo.",
    chatMicDenied: "Hace falta permiso de micrófono para llamar.",
    chatNativeMode: "Chat",
    chatTutorMode: "Ayuda",
    sessionMenu: "Menú",
    videoLearnCancelPrep: "Cancelar preparación",
    chatDuringCall: "Durante la llamada, el tutor responde en voz alta.",
    reportContent: "Reportar esta respuesta",
    reportTitle: "Reportar contenido de IA",
    reportSubtitle: "Cuéntanos qué estuvo mal en esta respuesta generada por IA. Revisamos los reportes y ajustamos el asistente.",
    reportReasonOffensive: "Ofensivo o inapropiado",
    reportReasonInaccurate: "Incorrecto o engañoso",
    reportReasonUnsafe: "Consejo peligroso o dañino",
    reportReasonOther: "Otro problema",
    reportNoteLabel: "¿Algo más que añadir? (opcional)",
    reportSubmit: "Enviar reporte",
    reportCancel: "Cancelar",
    reportThanks: "Gracias, tu reporte se envió.",
    reportFailed: "No se pudo enviar el reporte. Inténtalo de nuevo.",
    billingOpen: "Plan",
    billingScreenTitle: "Plan y pago",
    billingFreeLabel: "Gratis",
    billingPremiumLabel: "Premium",
    billingClose: "Cerrar",
    headerImportPoints: "{remaining} pts",
    chatReading: "Lectura",
    translate: "Traducir",
    listen: "Escuchar",
    insightAnalyze: "Analizar",
    inspectTabSentence: "Frase",
    insightSaveWord: "Guardar palabra",
    insightLoading: "Revisando esta expresión...",
    insightFailed: "No se pudo cargar la explicación. Inténtalo de nuevo.",
    insightClose: "Cerrar",
    insightBack: "Anterior",
    insightInSentence: "En esta frase",
    insightPattern: "Estructura",
    insightExamples: "Más ejemplos",
    insightTip: "Ojo",
    insightComparison: "Parecido, pero distinto",
    insightHint: "Selecciona la parte que te interesa y pulsa Analizar.",
    corrected: "Correccion",
    highlighted: "Errores marcados",
    natural: "Otra expresión",
    correctionBlockTitle: "Corrección",
    correctionMyLine: "Lo que escribiste",
    correctionTryThis: "Prueba esto",
    explanation: "Explicacion",
    example: "Ejemplo",
    useThisExpression: "Usar esta expresión",
    save: "Guardar expresión",
    saved: "✔ Guardado",
    savedToBookToast: "Guardado en tu libro de {targetLanguage} ({count})\nPuedes repasarlo cuando quieras.",
    learningBookNav: "Mi libro de {targetLanguage}",
    learningBookTitle: "Mi libro de {targetLanguage}",
    learningEmpty:
      "Todavia no guardaste expresiones\n\nGuarda frases utiles mientras chateas\ny arma tu libro personal de {targetLanguage}",
    learningSearchPlaceholder: "Buscar en mi libro",
    learningSearchNoResults: "No hay resultados.",
    learningFilterEmpty: "No hay tarjetas con este filtro.",
    filterAll: "Todo",
    filterNew: "Nuevas",
    filterPracticing: "Practicando",
    filterUsable: "Familiares",
    cardShowDetails: "Ver detalles",
    cardHideDetails: "Menos",
    reviewPracticingCta: "Repasar expresiones en practica",
    reviewNewCta: "Repasar expresiones nuevas",
    reviewTodayEmpty: "Nada para repasar todavia. Guarda algunas expresiones desde el chat.",
    learningBackToChat: "← Volver al chat",
    dashboardSavedToday: "Guardadas hoy",
    dashboardTotalCards: "Tarjetas",
    dashboardTotalCardsSubtle: "{count} expresiones en total",
    dashboardPracticing: "Practicando",
    dashboardUsable: "Familiares",
    cardMySentence: "Lo que yo escribi",
    cardBetterExpression: "Mejor expresion",
    cardMoreNatural: "Otra expresión",
    cardPoint: "Punto clave",
    practiceAgain: "🔁 Repasar",
    deleteFromBook: "🗑 Borrar",
    reviewFrontHint: "La frase que escribiste",
    reviewReveal: "Ver respuesta",
    reviewForgot: "Aun dificil",
    reviewVague: "Dudoso",
    reviewFamiliar: "Familiar",
    reviewConfidencePrompt: "Crees que podrias usar esta frase de forma natural la proxima vez?",
    progressStatusNew: "🆕 Nueva",
    progressStatusPracticing: "🔁 Practicando",
    progressStatusUsable: "✅ Familiar",
    progressSavedToday: "Guardada hoy",
    progressNotReviewed: "Sin repasar",
    progressReviewCount: "{count} repasos",
    progressLastReviewedToday: "ultimo repaso hoy",
    progressLastReviewedYesterday: "ultimo repaso ayer",
    progressLastReviewedDays: "ultimo repaso hace {count} dias",
    archive: "Informes",
    archiveEmpty: "No hay elementos guardados.",
    savedItemsTab: "Expresiones guardadas",
    sessionsTab: "Informes de aprendizaje",
    sessionsEmpty:
      "Aún no hay informes completados.\nFinaliza una sesión para crear uno.",
    openSession: "Ver informe",
    clearSessions: "Borrar todos los informes",
    freeTraining: "Practica libre",
    messagesUsed: "Mensajes usados",
    resetArchive: "Reiniciar archivo",
    closeArchive: "Cerrar",
    reportMenuTitle: "Informes",
    reportListTitle: "Sesiones completadas",
    reportListEmpty:
      "Aún no hay informes de aprendizaje.\nTermina el chat y finaliza la sesión para crear uno.",
    reportClearAll: "Borrar todo",
    reportViewCta: "Ver informe",
    reportTurnCount: "{count} turnos",
    reportScoreLabel: "{score} pts",
    reportDetailBadge: "Informe de la sesión",
    reportTodayLearning: "Aprendizaje de hoy",
    reportStatExpressions: "Expresiones",
    reportStatCorrections: "Correcciones",
    reportStatTakeaways: "Para llevar",
    reportTimelineTitle: "Conversación",
    reportSummaryTitle: "Resumen de la conversación",
    reportScoreTitle: "Puntuación de la sesión",
    reportScoreInsufficient:
      "No hay suficiente conversación para puntuar con fiabilidad. Habla un poco más y luego finaliza la sesión.",
    reportScoreNativeHint:
      "Naturalidad: 25 = nativo, 0 = casi no sabe {targetLanguage}. La gramática no entra aquí.",
    reportScoreBreakdownTitle: "Desglose de la puntuación",
    reportScoreFactorAccuracy: "Precisión",
    reportScoreFactorNaturalness: "Naturalidad",
    reportScoreFactorFluency: "Longitud del turno",
    reportScoreFactorSpoken: "Estilo oral",
    reportScoreFactorLost: "−{n}",
    reportScoreFactorEarned: "{earned}/{max}",
    reportStrengthsTitle: "Lo que salió bien",
    reportImprovementsTitle: "Qué mejorar",
    reportMyExpression: "Tu frase",
    reportBetterExpression: "Más natural",
    reportLearningTitle: "Expresiones para llevarte",
    reportShowTranscript: "Ver conversación completa",
    reportHideTranscript: "Ocultar conversación",
    reportTranscriptReadonly:
      "Solo lectura: no puedes continuar este chat desde aquí.",
    reportTranscriptYou: "Tú",
    reportTranscriptAi: "IA",
    reportReviewTitle: "Repaso de la conversación",
    reportReviewHint: "Mira el chat tal como se veía en ese momento.",
    reportReviewEmpty: "No hay conversación guardada en esta sesión.",
    reportChatCaptureLabel: "Repetición del chat",
    reportLightCorrectionLabel: "Más natural",
    reportReviewDoneTitle: "Ya repasaste toda la conversación.",
    reportReviewDoneBody: "¿Miramos de cerca el {targetLanguage} que usaste hoy?",
    reportGotoAnalysis: "Ver análisis detallado",
    reportAnalysisTitle: "Análisis detallado",
    reportAnalysisHint: "A partir del {targetLanguage} que usaste: qué funcionó y cómo llevarlo más lejos.",
    reportExpressionsTitle: "Cómo decirlo",
    reportExpressionsHint: "El {targetLanguage} que entró al chat después de preguntar en tu idioma.",
    reportExpressionIntent: "Lo que querías decir",
    reportExpressionUsed: "Frase usada en el chat",
    reportExpressionSimpler: "Más fácil",
    reportExpressionNative: "Más natural",
    reportExpressionAnalysis: "Análisis de la frase",
    reportAnalysisEmpty:
      "La conversación aún es corta para juzgar hábitos. Habla un poco más y podremos analizar el patrón.",
    reportAnalysisStrengthsTitle: "Lo que te salió bien",
    reportAnalysisImprovementsTitle: "Prueba esto",
    reportAnalysisHabitsTitle: "Hábitos de conversación",
    reportAnalysisNextGoalTitle: "Objetivo de la próxima vez",
    reportAnalysisGenerating: "Analizando la conversación...",
    reportAnalysisCategoryNatural: "Expresión natural",
    reportAnalysisCategoryNuance: "Matiz",
    reportAnalysisCategoryWordChoice: "Elección de palabras",
    reportAnalysisCategoryTone: "Tono",
    reportAnalysisCategoryFlow: "Flujo",
    reportAnalysisCategoryVariety: "Variedad",
    reportAnalysisCategoryConnection: "Conexión",
    reportAnalysisCategoryExpression: "Expresión",
    reportAnalysisCategoryConversation: "Conversación",
    reportAnalysisCategoryImprovement: "Para mejorar",
    reportAnalysisStrengthLabel: "Buena expresión",
    reportAnalysisWhyGood: "¿Por qué estuvo bien?",
    reportAnalysisCorrected: "Corrección",
    reportAnalysisWhy: "¿Por qué?",
    reportAnalysisAlternative: "Otra forma de decirlo",
    reportAnalysisExample: "Ejemplo",
    reportTakeawaysTitle: "Para llevarte hoy",
    reportTakeawaysHint: "Con recordar esto es suficiente por hoy.",
    reportTakeawaysEmpty: "Aún no hay expresiones clave para llevarte.",
    reportCreatedToast: "Informe de aprendizaje guardado",
    quizReadyToast: "Tu material de repaso está listo. Ábrelo en la pestaña Repaso.",
    reportSessionsTab: "Informes de sesión",
    reportMonthlyTab: "Informe mensual",
    reportBack: "← Informes",
    monthlyOpenFull: "Ver informe mensual",
    homeTabChat: "Chat",
    homeTabSessions: "Sesiones",
    homeTabMonthly: "Mensual",
    homeTabReports: "Informes",
    homeTabSaved: "Guardado",
    homeTabVocab: "Vocabulario",
    homeTabQuiz: "Explorar",
    homeTabRead: "Web",
    homeTabVideo: "Vídeo",
    homeTabStudy: "Materiales",
    studyLibraryTitle: "Mis materiales",
    studyAdd: "+ Añadir archivo",
    studyAddImage: "Imagen",
    studyDropHint: "Elige un archivo o suéltalo aquí.\nPDF, EPUB y TXT están disponibles.",
    studyOpen: "Abrir",
    studyContinue: "Seguir leyendo",
    studyDelete: "Eliminar",
    studyBack: "← Lista",
    studyEmpty: "Aún no hay archivos.\nAñade un libro, PDF o texto\ny pulsa la frase que no entiendas.",
    studySavedExpressions: "{count} expresiones guardadas",
    studyAnalyzedSentences: "{count} frases analizadas",
    studyPages: "{current} / {total} páginas",
    studyStageReading: "Abriendo archivo...",
    studyStageExtracting: "Extrayendo texto...",
    studyStageNormalizing: "Organizando el documento...",
    studyStageReady: "Listo",
    studyUnsupported: "Este tipo de archivo aún no está disponible.",
    studyProtected: "Este archivo está protegido y no se puede abrir.",
    studyNoText: "No se encontró texto en este PDF.",
    studyTooLarge: "El archivo es demasiado grande.",
    studyImageSoon: "La lectura de fotos está desactivada por ahora. Usa PDF, EPUB o TXT.",
    studyImageHint: "Toca una frase abajo para ver el significado y el análisis. Pellizca la foto para ampliar.",
    studySelectGloss: "Significado",
    studySelectHint: "Toca una frase para ver el significado y el análisis. Pellizca para ampliar.",
    studyChapterPrev: "Anterior",
    studyChapterNext: "Siguiente",
    studyOcrPage: "Buscando texto en esta página...",
    studyZoomIn: "Ampliar",
    studyZoomOut: "Reducir",
    studyFailed: "No se pudo cargar el archivo. Prueba con otro.",
    studyResumeHint: "Lo dejaste en el {percent}%.",
    learningLanguageLabel: "Idioma de estudio",
    uiLanguageLabel: "Idioma de la app",
    videoLearnHeadline: "Aprende {targetLanguage} con vídeos",
    videoLearnBody:
      "Pega un enlace para generar subtítulos y traducción. Los vídeos nuevos usan los minutos del mes; los guardados se pueden repetir gratis.",
    videoLearnUrlPlaceholder: "Pega un enlace de YouTube",
    videoLearnLoad: "Cargar vídeo",
    videoLearnInvalidUrl: "Introduce un enlace válido de YouTube.",
    videoLearnGenerating: "Entendiendo el vídeo completo y preparando el material...",
    videoLearnStepSpeech: "Extrayendo todo el diálogo",
    videoLearnStepContext: "Tema y escenas",
    videoLearnStepTranslate: "Creando subtítulos naturales",
    videoLearnStepCleanup: "Listo para reproducir",
    videoLearnWhy: "¿Qué expresión es?",
    videoLearnWhyDetail: "Así se siente en coreano",
    videoLearnSave: "Guardar",
    videoLearnSavedToast: "Guardado en tu material de estudio",
    videoLearnTranscriptShow: "Ver transcripción",
    videoLearnTranscriptHide: "Cerrar transcripción",
    videoLearnKeyExpression: "Expresión clave",
    videoLearnMeaningHere: "Significado en esta frase",
    videoLearnNuance: "Matiz",
    videoLearnSimilar: "Expresiones parecidas",
    videoLearnBack: "Otro vídeo",
    videoLearnIdleCue: "Elige una línea en el material de estudio.",
    videoLearnIdleEnglish: "Reproduce el vídeo para ver los subtítulos en {targetLanguage} aquí.",
    videoLearnFailed: "No se pudieron generar los subtítulos. Inténtalo de nuevo.",
    videoLearnNoSpeech: "No se encontró habla en este vídeo.",
    videoLearnWrongLanguage:
      "Este vídeo no está en tu idioma de aprendizaje. Elige uno en {targetLanguage}.",
    videoLearnQuotaReached:
      "Ya usaste los puntos de importación de este mes. La biblioteca y los vídeos guardados se pueden repetir.",
    videoLearnTooLong:
      "Este vídeo supera los 15 minutos y no se puede preparar.",
    videoLearnQuotaHint:
      "{used}/{limit} puntos de importación este mes · 1 punto cada 3 min · biblioteca y guardados son gratis",
    videoLearnLibraryTitle: "Biblioteca de este mes",
    videoLearnLibrarySubtitleFree:
      "Prueba gratis: {used}/{limit} episodios. No se renueva cada mes; suscríbete para abrir el pack mensual.",
    videoLearnLibrarySubtitlePremium:
      "Pack de este mes · sin puntos",
    videoLearnLibraryEmpty:
      "Aún no hay biblioteca para este idioma. Con Premium puedes pegar un enlace.",
    videoLearnLibraryTrial: "Prueba",
    videoLearnLibraryLocked: "Bloqueado",
    videoLearnImportLocked:
      "Pegar tu propio enlace es de Premium y usa puntos.",
    videoLearnCatalogLocked:
      "Este episodio está en la biblioteca Premium.",
    videoLearnMoreGenerating: "Terminando el resto de las traducciones…",
    videoLearnWaitingGloss: "La reproducción espera a que esté la traducción",
    videoLearnStudyTitle: "Frases en {targetLanguage}",
    videoLearnStudyHint:
      "Usa 🔊 para oír ese momento del vídeo y toca la frase para analizarla.",
    videoLearnStudyEmpty: "Aún no hay frases extraídas.",
    videoLearnRangeMode: "Unir clips",
    videoLearnRangeHint:
      "Pulsa Unir clips para ver la barra vertical. Arriba = anteriores, abajo = siguientes.",
    videoLearnPlayRange: "Oír juntas",
    videoLearnClearRange: "Quitar selección",
    videoLearnMergeCues: "Unir clips",
    videoLearnSplitCue: "Dividir clip",
    videoLearnMergeNeedRange: "Une 2 o más clips con la barra y luego fusiónalos.",
    videoLearnBundleGaugeHint:
      "Desliza la barra arriba o abajo. El punto rojo es este clip.",
    videoLearnBundleClickHint:
      "O toca clips arriba/abajo para incluirlos. Toca un extremo otra vez para reducir.",
    videoLearnBundleUp: "Arriba",
    videoLearnBundleDown: "Abajo",
    videoLearnSplitTooShort: "Este clip es demasiado corto para dividir.",
    videoLearnSplitNeedSelection:
      "Mueve la barra para marcar el límite y confirma.",
    videoLearnSplitHint:
      "Pulsa Dividir clip para ver la barra. Ajusta delante/detrás y confirma.",
    videoLearnSplitSliderHint: "Desliza la barra para elegir el corte.",
    videoLearnSplitFront: "Delante",
    videoLearnSplitBack: "Detrás",
    videoLearnSplitConfirm: "Dividir aquí",
    videoLearnSplitCancel: "Cancelar",
    videoLearnCuesEditedToast: "Clips actualizados",
    videoLearnUndoMerge: "Deshacer unión",
    videoLearnUndoSplit: "Deshacer división",
    videoLearnUndoEdit: "Deshacer",
    videoLearnResetAllCues: "Restaurar original",
    videoLearnUndoMergeToast: "Se restauró el estado anterior a la unión",
    videoLearnUndoSplitToast: "Se restauró el estado anterior a la división",
    videoLearnResetAllCuesToast: "Se restauraron los clips originales",
    videoLearnFullscreen: "Pantalla completa",
    videoLearnFullscreenExit: "Salir",
    videoLearnFullscreenHint: "Toca una barra de abajo para oír ese tramo.",
    videoLearnWatchHint:
      "Mira con subtítulos en {targetLanguage}. Pulsa 🔊 para oír ese tramo y toca el texto para analizarlo.",
    videoLearnSaveSession: "Guardar este material de vídeo",
    videoLearnSessionSaved: "Guardado",
    videoLearnSessionSavedToast: "Guardado. Puedes volver a abrir el vídeo para seguir estudiando.",
    videoLearnSavedSessions: "Vídeos guardados",
    videoLearnOpenSession: "Seguir estudiando",
    videoLearnDeleteSession: "Eliminar",
    videoLearnSessionLines: " frases",
    videoLearnSessionDeletedToast: "Material de vídeo eliminado",
    discoverCta: "Buscar material de estudio",
    discoverCtaHint: "¿Te cuesta encontrar un enlace? Te recomendamos contenido real según tus intereses.",
    discoverTitle: "Buscar material",
    discoverSubtitle: "Encuentra vídeos y artículos públicos y ábrelos en las herramientas de estudio existentes.",
    discoverChannelsLabel: "Mis canales",
    discoverTabChannels: "Canales",
    discoverTabTopics: "Temas",
    discoverChannelSearch: "Buscar canal",
    discoverChannelSearchPlaceholder: "p. ej. BBC Mundo, RTVE",
    discoverChannelAdd: "Añadir",
    discoverChannelAdded: "Añadido",
    discoverChannelRemove: "Quitar",
    discoverChannelOpen: "Ver vídeos del canal",
    discoverChannelEmpty:
      "Busca un canal para añadirlo. El icono o el nombre carga sus vídeos.",
    discoverChannelSearchEmpty: "No se encontraron canales.",
    discoverChannelSubscribers: "{count} suscriptores",
    discoverClose: "Plegar",
    discoverTopicLabel: "Tema",
    discoverTopicPlaceholder: "p. ej. viaje, fútbol, conversación diaria",
    discoverTopicAny: "Todo",
    discoverTopicDaily: "Conversación diaria",
    discoverTopicTravel: "Viajes",
    discoverTopicFood: "Comida y cocina",
    discoverTopicWork: "Trabajo y negocios",
    discoverTopicNews: "Noticias",
    discoverTopicSchool: "Estudio y escuela",
    discoverTopicEntertainment: "Series y drama",
    discoverTopicSports: "Deportes",
    discoverTopicTech: "Tecnología y ciencia",
    discoverTopicCulture: "Cultura y sociedad",
    discoverTopicHealth: "Salud y estilo de vida",
    discoverTopicMusic: "Música",
    discoverTopicFamily: "Familia",
    discoverTopicInterview: "Entrevistas y charlas",
    discoverTopicVlog: "Vlog",
    discoverTopicShopping: "Compras y moda",
    discoverTopicFinance: "Economía y finanzas",
    discoverTopicNature: "Naturaleza y animales",
    discoverTopicHobbies: "Aficiones y juegos",
    discoverNaturalLabel: "Búsqueda en YouTube (opcional)",
    discoverNaturalPlaceholder: "p. ej. charla entre amigos, entrevista de fútbol",
    discoverTypeVideo: "Vídeo",
    discoverTypeReading: "Lectura",
    discoverDurationLabel: "Duración",
    discoverDurationShort: "Corta",
    discoverDurationMedium: "Media",
    discoverDurationLong: "Larga",
    discoverDurationAny: "Cualquiera",
    discoverLevelLabel: "Nivel",
    discoverLevelAny: "Cualquiera",
    discoverLevelBeginner: "Principiante",
    discoverLevelIntermediate: "Intermedio",
    discoverLevelAdvanced: "Avanzado",
    discoverCaptionsLabel: "Subtítulos",
    discoverCaptionsAny: "Cualquiera",
    discoverCaptionsOriginal: "Con subtítulos oficiales",
    discoverCaptionsBadge: "Subtítulos oficiales",
    discoverImportPoints: "{n} pts",
    discoverSearch: "Buscar",
    discoverMore: "Ver más",
    discoverFindingMore: "Buscando más en segundo plano…",
    discoverSearching: "Buscando…",
    discoverNeedTopic: "Elige un tema o escribe una petición en lenguaje natural.",
    discoverEmpty: "No hay resultados. Prueba un tema o duración más amplios.",
    discoverFailed: "No se pudo buscar. Inténtalo de nuevo en un momento.",
    discoverYoutubeUnavailable:
      "La búsqueda de YouTube aún no está configurada. Puedes pegar una URL.",
    discoverProviderQuota: "Se alcanzó el límite de búsqueda. Prueba más tarde o pega una URL.",
    discoverProviderFailed: "Falló la búsqueda externa. Puedes pegar una URL.",
    discoverOpenPreview: "Ver",
    discoverOpenRead: "Leer",
    discoverLearn: "Estudiar",
    discoverReadingMinutes: "~{minutes} min",
    webReadHeadline: "Lee {targetLanguage} en la web\ny analiza lo que te interese.",
    webReadHowTo:
      "Lee el sitio en su propia pantalla.\nToca Analizar y elige una frase.",
    webReadReadingTitle: "Sigue leyendo y analiza",
    webReadUrlPlaceholder: "Introduce una URL",
    webReadOpen: "Abrir",
    webReadResume: "Seguir leyendo",
    webReadPastePlaceholder: "O pega el {targetLanguage} que seleccionaste",
    webReadBack: "Atrás",
    webReadForward: "Adelante",
    webReadReload: "Actualizar",
    webReadHome: "Cerrar página",
    webReadInvalidUrl: "Introduce una dirección válida.",
    webReadLoadError: "No se pudo abrir la página. Revisa la dirección y la conexión.",
    webReadUnsupported: "No se puede abrir esta dirección.",
    webReadNoSelection: "Selecciona texto para analizar.",
    webReadWebLimited:
      "También puedes pegar el {targetLanguage} abajo.",
    webReadSelectionHint:
      "En la otra app, toca Analizar y luego una frase.\nMantén pulsado el botón para terminar.",
    webReadNeedOverlay:
      "Hay que permitir mostrar sobre otras apps y capturar la pantalla.",
    webReadShortcutReddit: "Reddit",
    webReadShortcutBbc: "BBC",
    webReadShortcutOther: "Guardian",
    exploreHeadline: "¿Por qué se dice así?",
    exploreHint: "Escribe una frase o expresión en {targetLanguage} que te interese.",
    explorePlaceholder: "I used to go there when...",
    exploreSubmit: "Analizar",
    exploreRecent: "Reciente",
    exploreLoading: "Mirando esta frase...",
    exploreFailed: "No se pudo cargar el análisis. Inténtalo de nuevo.",
    exploreTapHint: "Toca la parte que te interesa.",
    exploreWhy: "¿Por qué esta forma?",
    exploreUsage: "Cómo usarlo",
    exploreOtherUsages: "Otros usos",
    exploreMeaningHere: "En esta frase",
    analysisSpokenAlso: "Primera lectura",
    dimensionSyntax: "Gramática",
    dimensionUsage: "Uso",
    dimensionPhonology: "Pronunciación",
    dimensionMorphology: "Forma",
    dimensionPragmatics: "Matiz",
    dimensionEtymology: "Origen",
    analysisKeyElements: "Conviene saber",
    quizTodayTitle: "Repaso de hoy",
    quizTodaySubtitle:
      "Practica lo que te costó en conversaciones recientes.",
    quizMissionPrompt: "Dedica 2 minutos a repasar\nlo que aprendiste recientemente.",
    quizTodayCountLabel: "Preguntas de hoy",
    quizRecentReviewTitle: "Repaso reciente",
    quizTodayCardTitle: "Repaso de hoy",
    quizTodayMeta: "{count} preguntas · unos {minutes} min",
    quizCompositionGrammar: "Gramática {count}",
    quizCompositionVocab: "Palabras {count}",
    quizCompositionExpression: "Expresiones {count}",
    quizStartCta: "Empezar repaso",
    quizContinueCta: "Continuar",
    quizReviewAgainCta: "Nuevas preguntas",
    quizCreateNewCta: "Crear un cuestionario nuevo",
    quizTodayFinished: "Con esto termina el repaso de hoy. Vuelve mañana.",
    quizGenerating: "Creando preguntas...",
    quizGenerateFailed: "No se pudieron crear las preguntas. Inténtalo de nuevo.",
    quizLoading: "Cargando...",
    quizEmptyTitle: "Aún no hay nada que repasar.",
    quizEmptyBody:
      "Habla en {targetLanguage} y guarda palabras\ny tendrás fichas de gramática y vocabulario.",
    quizEmptyCta: "Hablar en {targetLanguage}",
    reviewFilterAll: "Todo",
    reviewFilterGrammar: "Gramática",
    reviewFilterVocab: "Palabras",
    reviewMySentence: "Lo que escribiste",
    reviewBetterSentence: "Prueba así",
    reviewExamples: "Ejemplos",
    reviewSimilar: "Palabras parecidas",
    reviewRefresh: "Volver a crear el material",
    reviewGenerating: "Creando material de repaso...",
    reviewGenerateFailed: "No se pudo crear el material de repaso.",
    reviewEmptyBody:
      "Guarda palabras al chatear.\nEl repaso usa tu gramática y las palabras guardadas.",
    reviewCompleteCta: "Repaso listo",
    reviewResetCta: "Vaciar",
    reviewSectionFallback: "Repaso {n}",
    quizProgress: "{current} / {total}",
    quizCorrect: "✓ Correcto",
    quizIncorrect: "¿Lo revisamos?",
    quizNext: "Siguiente",
    quizSeeResult: "Ver resultado",
    quizCompleteTitle: "Repaso de hoy listo ✓",
    quizCompleteScore: "Acertaste {correct} de {total}.",
    quizRememberedTitle: "Lo recuerdas bien",
    quizReviewAgainTitle: "Para revisar",
    quizBackHome: "Volver al inicio del repaso",
    quizAlreadyDone: "Ya completaste el repaso de hoy.",
    quizTypeGrammar: "Gramática",
    quizTypeVocabulary: "Vocabulario",
    quizTypeExpression: "Expresión",
    homeBack: "← Inicio",
    homeHubBadge: "Inicio",
    homeHubSubtitle: "Elige dónde quieres practicar hoy.",
    homeOpenCta: "Abrir",
    homeDestChatDesc: "Practica {targetLanguage} en conversación con correcciones.",
    homeDestSessionsDesc: "Revisa los informes de tus sesiones completadas.",
    homeDestMonthlyDesc: "Mira el crecimiento de este mes.",
    homeDestSavedDesc: "Repasa las expresiones que guardaste.",
    homeDestVocabDesc: "Busca en tu idioma y guarda palabras en {targetLanguage}.",
    vocabTitle: "Vocabulario",
    vocabFilterAll: "Todo",
    vocabFilterWords: "Palabras",
    vocabFilterPhrases: "Expresiones",
    vocabStatusLearning: "Aprendiendo",
    vocabStatusFamiliar: "Familiar",
    vocabQueryHint: "Busca en el idioma de la interfaz para ver palabras en {targetLanguage}.",
    vocabSearchPlaceholder: "Busca una palabra en tu idioma",
    vocabSearchCta: "Buscar",
    vocabSearching: "Buscando...",
    vocabResultsTitle: "Resultados",
    vocabSavedTitle: "Palabras guardadas",
    vocabEmpty: "Aún no hay palabras guardadas.\nBusca arriba para añadir.",
    vocabHideGloss: "Ocultar significados",
    vocabShuffle: "Aleatorio",
    vocabRevealGloss: "Toca para ver el significado",
    vocabNoResults: "No hay resultados.",
    vocabSave: "Guardar",
    vocabSaved: "Guardado",
    vocabDelete: "Eliminar",
    vocabSavedToast: "Guardado en el vocabulario",
    vocabSearchFailed: "La búsqueda falló. Inténtalo de nuevo.",
    vocabSaveFromChat: "Revisar palabras",
    vocabPickTitle: "Elegir palabras",
    vocabPickHint: "Toca las palabras resaltadas del chat para guardarlas.",
    vocabPickModeHint: "Ámbar = palabra, celeste = locución. Toca para ver el significado.",
    vocabPickEmpty: "Aún no hay palabras en {targetLanguage}. Habla un poco primero.",
    vocabPickCancel: "Cerrar",
    vocabPickSave: "Guardar {count}",
    vocabPickSaving: "Guardando...",
    vocabPickDone: "Listo",
    vocabPickSavedToast: "Palabra guardada",
    vocabPickNoneToast: "No hay palabras para guardar",
    vocabPickFailed: "No se pudieron guardar. Inténtalo de nuevo.",
    vocabPreviewLoading: "Cargando significado...",
    vocabPreviewSave: "Guardar",
    vocabPreviewClose: "Cerrar",
    vocabOtherSenses: "Otros sentidos",
    vocabTabSaved: "Palabras guardadas",
    vocabTabCharacters: "Caracteres",
    characterGuideHint:
      "Toca un carácter para ver cómo suena y cómo se usa.",
    characterPronunciation: "Pronunciación",
    characterCategory: "Tipo",
    characterMeaning: "Significado",
    characterUsage: "Uso",
    characterTone: "Tono",
    characterTone1: "1.er tono",
    characterTone2: "2.º tono",
    characterTone3: "3.er tono",
    characterTone4: "4.º tono",
    characterToneNeutral: "Tono neutro",
    characterExamples: "Ejemplos",
    characterForms: "Formas en la palabra",
    characterFormIsolated: "Aislada",
    characterFormInitial: "Inicial",
    characterFormMedial: "Media",
    characterFormFinal: "Final",
    chatHistoryTitle: "Historial de chat",
    chatHistoryListTitle: "Chats anteriores",
    chatHistoryEmpty:
      "Aún no hay chats guardados.\nEmpieza una conversación y aparecerá aquí.",
    chatHistoryContinue: "Continuar chat",
    chatHistoryNew: "Nuevo chat",
    chatHistoryClear: "Borrar todo",
    chatHistoryCurrent: "Actual",
    chatHistoryHasReport: "Con informe",
    createReport: "Crear informe",
    chatCardsOn: "Tarjetas visibles",
    chatCardsOff: "Tarjetas ocultas",
    chatCardsLabel: "Tarjetas",
    toggleLegendOn: "On",
    toggleLegendOff: "Off",
    sessionSavedToHistoryToast: "Guardado en el historial",
    reportCreateEmptyToast: "Aún no hay conversación para crear un informe",
    reportCreateConfirmTitle: "¿Crear un informe?",
    reportCreateConfirmBody:
      "Esto terminará el chat actual y creará un informe de aprendizaje. ¿Continuar?",
    reportCreateConfirmCta: "Crear informe",
    reportCreateConfirmCancel: "Seguir hablando",
    reportDailyLimitToast:
      "Ya usaste el informe gratis de hoy. Pasa a Premium para crear más.",
    monthlyGrowthTitle: "Crecimiento · {month}",
    monthlyCurrentScore: "Puntuación actual",
    monthlyChange: "Promedio",
    monthlySessions: "Completadas",
    monthlySessionCount: "{count}",
    monthlyEmpty:
      "Aún no hay registros de aprendizaje este mes.\nTermina una conversación para ver tu progreso aquí.",
    monthlyNeedMoreForTrend:
      "Con más informes podrás ver la tendencia de crecimiento.",
    monthlyChartTitle: "Crecimiento de puntuación",
    monthlyChartNoScores:
      "Todavía no hay sesiones con puntuación.\nHabla un poco más y termina la sesión.",
    monthlyChartTapHint:
      "Toca un punto del gráfico para abrir el informe de esa sesión.",
    monthlyListTitle: "Aprendizaje de este mes",
    monthlyCalendarHint: "Toca un día coloreado para ver el informe de ese día.",
    monthlyDayReportsTitle: "Informes de este día",
    monthlyNoScore: "Sin puntuación",
    continuePractice: "Continuar practicando",
    comeBackTomorrow: "Volver manana",
    trainingDoneTitle: "Has completado el entrenamiento de hoy 👍",
    trainingDoneBody: "Vuelve manana para continuar.",
    trainingDoneHint: "Si quieres, puedes seguir practicando ahora.",
    delete: "Eliminar",
    reuse: "Reutilizar",
    translating: "Traduciendo...",
    translation: "Traduccion",
    translateFailed: "No se pudo traducir. Intentalo de nuevo.",
    dailyLimitReached: "Llegaste al limite de mensajes de hoy. Vuelve manana.",
    expressionHelperTitle: "💡 Puedes decirlo asi",
    expressionSentHint: "Esta frase se envió al chat.",
    correctionTitle: "Correccion",
    noCorrectionNeeded: "No hace falta corregir.",
    correctionFeedbackCorrect: "👍 Great sentence! Very natural.",
    correctionFeedbackError: "💡 Good try! Just a small mistake.",
    sessionComplete: "Completaste la practica de hoy 🎯",
    startNewSession: "Start New Session",
    endSession: "Finalizar sesion",
    languageKorean: "Coreano",
    languageEnglish: "Ingles",
    languageSpanish: "Espanol",
    planPremium: "Premium · biblioteca del mes + {limit} puntos",
    planFree: "Plan gratis · {used}/{limit} hoy",
    upgradeCta: "Mejorar a Premium",
    paywallLimitBanner: "Llegaste a un límite gratis. Premium te deja seguir con vídeos.",
    paywallTitle: "Sigue aprendiendo con Premium",
    paywallSubtitle:
      "Premium abre la biblioteca de este mes y 80 puntos para importar tus enlaces. La biblioteca y los vídeos guardados no gastan puntos.",
    paywallBenefitsTitle: "Premium incluye",
    paywallBenefits:
      "Biblioteca de estudio de este mes\n80 puntos para importar tus vídeos (3 min = 1 punto)\nRepetir vídeos guardados es gratis\nSin límite diario de chat",
    paywallCta: "Empezar por 9.900 ₩/mes",
    paywallRestore: "Restaurar compras",
    paywallLater: "Ahora no",
    paywallNativeOnly: "Puedes pagar en la app",
    paywallPurchasing: "Procesando…",
    paywallRestoring: "Restaurando…",
    paywallActivatedToast: "Premium activado",
    paywallRestoredToast: "Compra restaurada",
    paywallRestoreEmpty: "No hay compras para restaurar",
    paywallPurchaseFailed: "No se pudo completar la compra. Inténtalo de nuevo.",
    paywallPurchaseTimeout:
      "La compra tardó demasiado. Instala la app desde Play Store e inténtalo de nuevo.",
    paywallNoProduct:
      "No se pudo cargar el producto. Revisa Play Console y RevenueCat.",
    paywallCancelled: "Compra cancelada",
  },
  ja: { ...generatedLocales.ja, ...generatedBillingOverlay },
  zh: { ...generatedLocales.zh, ...generatedBillingOverlay },
  vi: { ...generatedLocales.vi, ...generatedBillingOverlay },
  fr: { ...generatedLocales.fr, ...generatedBillingOverlay },
  it: { ...generatedLocales.it, ...generatedBillingOverlay },
  pt: { ...generatedLocales.pt, ...generatedBillingOverlay },
  ru: { ...generatedLocales.ru, ...generatedBillingOverlay },
  id: { ...generatedLocales.id, ...generatedBillingOverlay },
  ar: { ...generatedLocales.ar, ...generatedBillingOverlay },
  th: { ...generatedLocales.th, ...generatedBillingOverlay },
  hi: { ...generatedLocales.hi, ...generatedBillingOverlay },
} as const;

export type Locale = keyof typeof copy;
export type UICopy = (typeof copy)[Locale];

export function isLocale(value: string): value is Locale {
  return Object.prototype.hasOwnProperty.call(copy, value);
}

type _LearningLanguagesAreUiLocales =
  LearningLanguageCode extends Locale ? true : never;
const _learningLanguagesAreUiLocales: _LearningLanguagesAreUiLocales = true;
void _learningLanguagesAreUiLocales;
