/**
 * Common multi-word English units (compounds, collocations, light idioms)
 * for vocabulary pick mode. Matched greedily, longest first.
 */
const ENGLISH_PHRASES = [
  // — rooms / places —
  "reading room",
  "living room",
  "dining room",
  "waiting room",
  "locker room",
  "rest room",
  "restroom",
  "bath room",
  "bathroom",
  "bed room",
  "bedroom",
  "class room",
  "classroom",
  "chat room",
  "emergency room",
  "fitting room",
  "dressing room",
  "conference room",
  "meeting room",
  "break room",
  "storage room",
  "laundry room",
  "control room",
  "engine room",
  "press room",
  "green room",
  "mail room",
  "server room",
  "study hall",
  "study room",
  "lecture hall",
  "town hall",
  "city hall",
  "police station",
  "fire station",
  "gas station",
  "bus stop",
  "bus station",
  "train station",
  "subway station",
  "parking lot",
  "parking garage",
  "shopping mall",
  "shopping center",
  "convenience store",
  "grocery store",
  "department store",
  "post office",
  "coffee shop",
  "book store",
  "bookstore",
  "drug store",
  "drugstore",
  "high school",
  "middle school",
  "elementary school",
  "graduate school",
  "boarding school",
  "home page",
  "home office",
  "front desk",
  "check-in",
  "check in",
  "check-out",
  "check out",
  "takeout",
  "take out",
  "hang out",
  "work out",
  "workout",
  "warm up",
  "cool down",

  // — everyday compounds —
  "ice cream",
  "cell phone",
  "mobile phone",
  "credit card",
  "debit card",
  "id card",
  "business card",
  "gift card",
  "boarding pass",
  "traffic jam",
  "rush hour",
  "real estate",
  "full time",
  "part time",
  "full-time",
  "part-time",
  "long term",
  "short term",
  "long-term",
  "short-term",
  "high end",
  "low end",
  "next door",
  "up to date",
  "out of date",
  "brand new",
  "well known",
  "well-known",
  "so called",
  "so-called",
  "common sense",
  "peer pressure",
  "climate change",
  "social media",
  "artificial intelligence",
  "machine learning",
  "remote work",
  "work from home",
  "open source",
  "user interface",
  "user experience",
  "customer service",
  "tech support",
  "voice mail",
  "voicemail",
  "e mail",
  "email",
  "web site",
  "website",
  "pass word",
  "password",
  "screen shot",
  "screenshot",
  "time zone",
  "day light",
  "daylight",
  "night life",
  "nightlife",
  "week end",
  "weekend",
  "birth day",
  "birthday",
  "girl friend",
  "girlfriend",
  "boy friend",
  "boyfriend",
  "best friend",
  "family member",
  "blood pressure",
  "mental health",
  "first aid",
  "junk food",
  "fast food",
  "soft drink",
  "hot dog",
  "french fries",
  "peanut butter",
  "olive oil",
  "mineral water",
  "tap water",
  "air conditioning",
  "air conditioner",
  "washing machine",
  "vacuum cleaner",
  "remote control",
  "alarm clock",
  "sleeping bag",
  "teddy bear",
  "comic book",
  "note book",
  "notebook",
  "text book",
  "textbook",
  "flash card",
  "flashcard",
  "word processor",
  "search engine",
  "data base",
  "database",
  "hard drive",
  "flash drive",
  "touch screen",
  "smart phone",
  "smartphone",
  "lap top",
  "laptop",
  "desk top",
  "desktop",

  // — time / calendar —
  "good morning",
  "good afternoon",
  "good evening",
  "good night",
  "good night",
  "see you",
  "see you later",
  "see you soon",
  "thank you",
  "thanks a lot",
  "of course",
  "no problem",
  "no way",
  "by the way",
  "in fact",
  "for example",
  "for instance",
  "as well",
  "as usual",
  "at least",
  "at most",
  "at all",
  "so far",
  "right now",
  "right away",
  "for now",
  "for good",
  "in advance",
  "on time",
  "in time",
  "ahead of time",
  "from scratch",
  "once in a while",
  "every now and then",
  "all of a sudden",
  "in the long run",
  "day by day",
  "one by one",
  "step by step",
  "little by little",

  // — common idioms / fixed phrases —
  "make sense",
  "make sure",
  "make up",
  "make out",
  "make it",
  "take care",
  "take place",
  "take part",
  "take a look",
  "take a break",
  "take notes",
  "take off",
  "take on",
  "take over",
  "take up",
  "give up",
  "give in",
  "give out",
  "look after",
  "look for",
  "look forward to",
  "look into",
  "look up",
  "look out",
  "look like",
  "find out",
  "figure out",
  "come up with",
  "come across",
  "come true",
  "get along",
  "get along with",
  "get over",
  "get rid of",
  "get used to",
  "get started",
  "go on",
  "go ahead",
  "go through",
  "go over",
  "go for",
  "put off",
  "put on",
  "put up with",
  "turn on",
  "turn off",
  "turn out",
  "turn into",
  "turn down",
  "turn up",
  "pick up",
  "pick out",
  "set up",
  "set out",
  "bring up",
  "break up",
  "break down",
  "break out",
  "break into",
  "run out",
  "run out of",
  "run into",
  "show up",
  "show off",
  "end up",
  "keep going",
  "keep in mind",
  "bear in mind",
  "pay attention",
  "pay off",
  "catch up",
  "catch up with",
  "fall behind",
  "fall asleep",
  "fall in love",
  "in love",
  "on purpose",
  "by accident",
  "by chance",
  "in charge",
  "in charge of",
  "in trouble",
  "out of order",
  "out of stock",
  "out of the blue",
  "under the weather",
  "piece of cake",
  "a piece of cake",
  "last straw",
  "the last straw",
  "big deal",
  "no big deal",
  "long story short",
  "to be honest",
  "to be fair",
  "as soon as",
  "as long as",
  "as far as",
  "in case",
  "in case of",
  "instead of",
  "because of",
  "due to",
  "according to",
  "in spite of",
  "even though",
  "even if",
  "what if",
  "how come",
  "kind of",
  "sort of",
  "a lot of",
  "lots of",
  "plenty of",
  "a couple of",
  "a few",
  "a little",
  "each other",
  "one another",
  "each other",
  "used to",
  "be used to",
  "supposed to",
  "have to",
  "ought to",
  "able to",
  "going to",
  "about to",
  "rather than",
  "other than",
  "more than",
  "less than",
  "as well as",
  "not only",
  "such as",
  "so that",
  "in order to",
  "in order for",
  "on the other hand",
  "in other words",
  "for instance",
  "at the same time",
  "from time to time",
  "once upon a time",
  "the other day",
  "these days",
  "nowadays",
  "right now",
  "just in case",
  "no longer",
  "not anymore",
  "as of now",
  "so far so good",
  "better late than never",
  "easier said than done",
  "practice makes perfect",
  "better safe than sorry",
  "actions speak louder than words",
  "break a leg",
  "hit the books",
  "hit the road",
  "call it a day",
  "call off",
  "wrap up",
  "speak up",
  "calm down",
  "cheer up",
  "hurry up",
  "slow down",
  "sit down",
  "stand up",
  "wake up",
  "grow up",
  "show up",
  "dress up",
  "clean up",
  "mess up",
  "screw up",
  "fill out",
  "fill in",
  "hand in",
  "hand out",
  "drop off",
  "drop by",
  "drop out",
  "pass out",
  "pass away",
  "pass by",
  "come back",
  "come in",
  "come on",
  "come over",
  "go back",
  "go out",
  "go away",
  "stay up",
  "stay in",
  "move on",
  "move in",
  "move out",
  "log in",
  "log out",
  "sign up",
  "sign in",
  "sign out",
  "sign off",
  "check in",
  "check out",
  "plug in",
  "plug out",
  "print out",
  "back up",
  "backup",
  "set aside",
  "point out",
  "sort out",
  "work on",
  "depend on",
  "focus on",
  "rely on",
  "deal with",
  "cope with",
  "catch a cold",
  "have a cold",
  "have a fever",
  "take medicine",
  "see a doctor",
  "make an appointment",
  "make a reservation",
  "make a decision",
  "make a mistake",
  "make progress",
  "make money",
  "make friends",
  "do homework",
  "do the dishes",
  "do laundry",
  "do exercise",
  "take a shower",
  "take a bath",
  "brush teeth",
  "brush your teeth",
  "wash hands",
  "wash your hands",
  "get dressed",
  "get ready",
  "get home",
  "get back",
  "come home",
  "leave home",
  "go home",
  "go to bed",
  "go to sleep",
  "fall asleep",
  "wake up",
  "have breakfast",
  "have lunch",
  "have dinner",
  "have a meal",
  "eat out",
  "eat in",
  "order takeout",
  "pay the bill",
  "split the bill",
  "leave a tip",
  "ask for",
  "ask about",
  "talk about",
  "think about",
  "think of",
  "dream of",
  "dream about",
  "worry about",
  "care about",
  "care for",
  "wait for",
  "look for",
  "search for",
  "apply for",
  "prepare for",
  "ready for",
  "good at",
  "bad at",
  "interested in",
  "afraid of",
  "proud of",
  "tired of",
  "bored with",
  "angry at",
  "angry with",
  "happy with",
  "satisfied with",
  "famous for",
  "known for",
  "responsible for",
  "available for",
  "suitable for",
  "similar to",
  "different from",
  "close to",
  "far from",
  "next to",
  "in front of",
  "in back of",
  "on top of",
  "at the top of",
  "at the bottom of",
  "in the middle of",
  "at the end of",
  "at the beginning of",
  "in the beginning",
  "in the end",
  "on the way",
  "on my way",
  "out of the way",
  "by the way",
  "in the way",
  "out of sight",
  "out of mind",
  "keep in touch",
  "get in touch",
  "lose touch",
  "stay in touch",
  "catch up with",
  "keep up with",
  "put up with",
  "come up with",
  "end up with",
  "get away with",
  "get along with",
  "fall in love with",
  "be in love with",
  "out of the question",
  "no doubt",
  "without a doubt",
  "for sure",
  "for real",
  "in general",
  "in particular",
  "in detail",
  "in short",
  "in summary",
  "to sum up",
  "all in all",
  "after all",
  "above all",
  "first of all",
  "last but not least",
  "on the contrary",
  "as a result",
  "as a matter of fact",
  "in my opinion",
  "from my point of view",
  "point of view",
  "make a difference",
  "make up your mind",
  "change your mind",
  "keep an eye on",
  "keep your word",
  "break your word",
  "take it easy",
  "take it personally",
  "don't take it personally",
  "give it a try",
  "give it a shot",
  "have a look",
  "have a seat",
  "have a good time",
  "have fun",
  "good luck",
  "best of luck",
  "congratulations",
  "happy birthday",
  "merry christmas",
  "happy new year",
  "see you tomorrow",
  "talk to you later",
  "nice to meet you",
  "pleased to meet you",
  "how are you",
  "how have you been",
  "how's it going",
  "how is it going",
  "what is up",
  "what's up",
  "what's going on",
  "what's the matter",
  "what's wrong",
  "never mind",
  "don't worry",
  "no worries",
  "you're welcome",
  "my pleasure",
  "excuse me",
  "i'm sorry",
  "i am sorry",
  "pardon me",
  "after you",
  "go ahead",
  "help yourself",
  "make yourself at home",
  "feel free",
  "let me know",
  "keep me posted",
  "get back to you",
  "talk soon",
  "take care of",
  "take care of yourself",
] as const;

function normalizePhraseKey(phrase: string): string {
  return phrase
    .trim()
    .toLowerCase()
    .replace(/[’‘]/g, "'")
    .replace(/\s+/g, " ");
}

/** Lowercase phrase → canonical display form (first listed spelling). */
const PHRASE_BY_KEY = new Map<string, string>();
let maxPhraseWordCount = 1;

for (const phrase of ENGLISH_PHRASES) {
  const key = normalizePhraseKey(phrase);
  if (!PHRASE_BY_KEY.has(key)) {
    PHRASE_BY_KEY.set(key, phrase);
  }
  const words = key.split(" ").length;
  if (words > maxPhraseWordCount) maxPhraseWordCount = words;
}

export function isKnownEnglishPhrase(text: string): boolean {
  return PHRASE_BY_KEY.has(normalizePhraseKey(text));
}

export type EnglishLookupSegment = {
  kind: "phrase" | "word" | "text";
  value: string;
};

type WordHit = { index: number; value: string };

/**
 * Split text so known multi-word phrases are one tappable unit;
 * remaining English tokens stay single words.
 */
export function segmentEnglishForLookup(text: string): EnglishLookupSegment[] {
  if (!text) return [];

  const wordRe = /[\p{L}\p{M}][\p{L}\p{M}'’]*(?:-[\p{L}\p{M}'’]*)*/gu;
  const words: WordHit[] = [];
  let match: RegExpExecArray | null;
  while ((match = wordRe.exec(text)) !== null) {
    words.push({ index: match.index, value: match[0] });
  }

  if (words.length === 0) {
    return [{ kind: "text", value: text }];
  }

  const segments: EnglishLookupSegment[] = [];
  let cursor = 0;
  let i = 0;

  const pushGap = (until: number) => {
    if (until > cursor) {
      segments.push({ kind: "text", value: text.slice(cursor, until) });
      cursor = until;
    }
  };

  const isPhraseSpan = (span: string) =>
    /^[\p{L}\p{M}'’]+(?:-[\p{L}\p{M}'’]+)*(?:\s+[\p{L}\p{M}'’]+(?:-[\p{L}\p{M}'’]+)*)+$/u.test(
      span,
    );

  while (i < words.length) {
    let matchedLen = 0;
    let matchedEnd = 0;
    let matchedValue = "";

    const maxLen = Math.min(maxPhraseWordCount, words.length - i);
    for (let len = maxLen; len >= 2; len -= 1) {
      const first = words[i];
      const last = words[i + len - 1];
      const span = text.slice(first.index, last.index + last.value.length);
      // Only spaces between words (no other punctuation inside the phrase).
      if (!isPhraseSpan(span)) {
        continue;
      }
      const key = normalizePhraseKey(span);
      if (PHRASE_BY_KEY.has(key)) {
        matchedLen = len;
        matchedEnd = last.index + last.value.length;
        matchedValue = span;
        break;
      }
    }

    const word = words[i];
    pushGap(word.index);

    if (matchedLen > 0) {
      segments.push({ kind: "phrase", value: matchedValue });
      cursor = matchedEnd;
      i += matchedLen;
      continue;
    }

    segments.push({ kind: "word", value: word.value });
    cursor = word.index + word.value.length;
    i += 1;
  }

  pushGap(text.length);
  return segments;
}
