import type { CharacterExample, CharacterGuide, CharacterItem, LocalizedText } from "./types.ts";

function m(ko: string, en: string): LocalizedText {
  return { ko, en };
}

function ex(text: string, reading: string, ko: string, en: string): CharacterExample {
  return { text, reading, meaning: m(ko, en) };
}

type KanaRow = {
  char: string;
  reading: string;
  examples: CharacterExample[];
};

const HIRAGANA: KanaRow[] = [
  { char: "あ", reading: "a", examples: [ex("あさ", "asa", "아침", "morning"), ex("あめ", "ame", "비", "rain")] },
  { char: "い", reading: "i", examples: [ex("いえ", "ie", "집", "house"), ex("いま", "ima", "지금", "now")] },
  { char: "う", reading: "u", examples: [ex("うみ", "umi", "바다", "sea"), ex("うた", "uta", "노래", "song")] },
  { char: "え", reading: "e", examples: [ex("えき", "eki", "역", "station"), ex("えいご", "eigo", "영어", "English")] },
  { char: "お", reading: "o", examples: [ex("おと", "oto", "소리", "sound"), ex("おかね", "okane", "돈", "money")] },
  { char: "か", reading: "ka", examples: [ex("かさ", "kasa", "우산", "umbrella"), ex("かわ", "kawa", "강", "river")] },
  { char: "き", reading: "ki", examples: [ex("き", "ki", "나무", "tree"), ex("きた", "kita", "북쪽", "north")] },
  { char: "く", reading: "ku", examples: [ex("くに", "kuni", "나라", "country"), ex("くるま", "kuruma", "차", "car")] },
  { char: "け", reading: "ke", examples: [ex("けさ", "kesa", "오늘 아침", "this morning"), ex("けん", "ken", "도(ticket)", "ticket")] },
  { char: "こ", reading: "ko", examples: [ex("こえ", "koe", "목소리", "voice"), ex("ここ", "koko", "여기", "here")] },
  { char: "さ", reading: "sa", examples: [ex("さかな", "sakana", "물고기", "fish"), ex("さくら", "sakura", "벚꽃", "cherry blossom")] },
  { char: "し", reading: "shi", examples: [ex("しお", "shio", "소금", "salt"), ex("しんぶん", "shinbun", "신문", "newspaper")] },
  { char: "す", reading: "su", examples: [ex("すし", "sushi", "초밥", "sushi"), ex("みず", "mizu", "물", "water")] },
  { char: "せ", reading: "se", examples: [ex("せんせい", "sensei", "선생님", "teacher"), ex("せかい", "sekai", "세계", "world")] },
  { char: "そ", reading: "so", examples: [ex("そら", "sora", "하늘", "sky"), ex("そこ", "soko", "거기", "there")] },
  { char: "た", reading: "ta", examples: [ex("たべる", "taberu", "먹다", "to eat"), ex("たまご", "tamago", "달걀", "egg")] },
  { char: "ち", reading: "chi", examples: [ex("ちず", "chizu", "지도", "map"), ex("いち", "ichi", "하나", "one")] },
  { char: "つ", reading: "tsu", examples: [ex("つき", "tsuki", "달", "moon"), ex("なつ", "natsu", "여름", "summer")] },
  { char: "て", reading: "te", examples: [ex("て", "te", "손", "hand"), ex("てんき", "tenki", "날씨", "weather")] },
  { char: "と", reading: "to", examples: [ex("とり", "tori", "새", "bird"), ex("ともだち", "tomodachi", "친구", "friend")] },
  { char: "な", reading: "na", examples: [ex("なまえ", "namae", "이름", "name"), ex("なつ", "natsu", "여름", "summer")] },
  { char: "に", reading: "ni", examples: [ex("にほん", "nihon", "일본", "Japan"), ex("にく", "niku", "고기", "meat")] },
  { char: "ぬ", reading: "nu", examples: [ex("いぬ", "inu", "개", "dog"), ex("ぬの", "nuno", "천", "cloth")] },
  { char: "ね", reading: "ne", examples: [ex("ねこ", "neko", "고양이", "cat"), ex("ねる", "neru", "자다", "to sleep")] },
  { char: "の", reading: "no", examples: [ex("のり", "nori", "김", "seaweed"), ex("のむ", "nomu", "마시다", "to drink")] },
  { char: "は", reading: "ha", examples: [ex("はな", "hana", "꽃", "flower"), ex("はし", "hashi", "젓가락", "chopsticks")] },
  { char: "ひ", reading: "hi", examples: [ex("ひと", "hito", "사람", "person"), ex("ひる", "hiru", "낮", "noon")] },
  { char: "ふ", reading: "fu", examples: [ex("ふゆ", "fuyu", "겨울", "winter"), ex("ふね", "fune", "배", "ship")] },
  { char: "へ", reading: "he", examples: [ex("へや", "heya", "방", "room"), ex("へた", "heta", "서투른", "unskilled")] },
  { char: "ほ", reading: "ho", examples: [ex("ほし", "hoshi", "별", "star"), ex("ほん", "hon", "책", "book")] },
  { char: "ま", reading: "ma", examples: [ex("まち", "machi", "마을", "town"), ex("まど", "mado", "창", "window")] },
  { char: "み", reading: "mi", examples: [ex("みず", "mizu", "물", "water"), ex("みみ", "mimi", "귀", "ear")] },
  { char: "む", reading: "mu", examples: [ex("むし", "mushi", "벌레", "insect"), ex("むら", "mura", "촌", "village")] },
  { char: "め", reading: "me", examples: [ex("め", "me", "눈", "eye"), ex("あめ", "ame", "비", "rain")] },
  { char: "も", reading: "mo", examples: [ex("もり", "mori", "숲", "forest"), ex("もも", "momo", "복숭아", "peach")] },
  { char: "や", reading: "ya", examples: [ex("やま", "yama", "산", "mountain"), ex("やすみ", "yasumi", "휴식", "rest")] },
  { char: "ゆ", reading: "yu", examples: [ex("ゆき", "yuki", "눈", "snow"), ex("ゆめ", "yume", "꿈", "dream")] },
  { char: "よ", reading: "yo", examples: [ex("よる", "yoru", "밤", "night"), ex("よむ", "yomu", "읽다", "to read")] },
  { char: "ら", reading: "ra", examples: [ex("らいねん", "rainen", "내년", "next year"), ex("さくら", "sakura", "벚꽃", "cherry blossom")] },
  { char: "り", reading: "ri", examples: [ex("りんご", "ringo", "사과", "apple"), ex("とり", "tori", "새", "bird")] },
  { char: "る", reading: "ru", examples: [ex("はる", "haru", "봄", "spring"), ex("くるま", "kuruma", "차", "car")] },
  { char: "れ", reading: "re", examples: [ex("れい", "rei", "예", "example"), ex("これ", "kore", "이것", "this")] },
  { char: "ろ", reading: "ro", examples: [ex("ろく", "roku", "여섯", "six"), ex("しろ", "shiro", "흰색", "white")] },
  { char: "わ", reading: "wa", examples: [ex("わたし", "watashi", "나", "I"), ex("かわ", "kawa", "강", "river")] },
  { char: "を", reading: "o", examples: [ex("てを", "te o", "손을 (목적)", "hand (object)"), ex("みずを", "mizu o", "물을", "water (object)")] },
  { char: "ん", reading: "n", examples: [ex("ほん", "hon", "책", "book"), ex("にほん", "nihon", "일본", "Japan")] },
];

const DAKUTEN: KanaRow[] = [
  { char: "が", reading: "ga", examples: [ex("がっこう", "gakkou", "학교", "school"), ex("がいこく", "gaikoku", "외국", "foreign country")] },
  { char: "ぎ", reading: "gi", examples: [ex("ぎんこう", "ginkou", "은행", "bank"), ex("かぎ", "kagi", "열쇠", "key")] },
  { char: "ぐ", reading: "gu", examples: [ex("いぐ", "igu", "가다(방언)", "to go"), ex("ぐあい", "guai", "상태", "condition")] },
  { char: "げ", reading: "ge", examples: [ex("げんき", "genki", "건강", "healthy"), ex("ひげ", "hige", "수염", "beard")] },
  { char: "ご", reading: "go", examples: [ex("ごはん", "gohan", "밥", "meal"), ex("ごご", "gogo", "오후", "afternoon")] },
  { char: "ざ", reading: "za", examples: [ex("かぜ", "kaze", "바람", "wind"), ex("ざっし", "zasshi", "잡지", "magazine")] },
  { char: "じ", reading: "ji", examples: [ex("じかん", "jikan", "시간", "time"), ex("みじかい", "mijikai", "짧은", "short")] },
  { char: "ず", reading: "zu", examples: [ex("みず", "mizu", "물", "water"), ex("ちず", "chizu", "지도", "map")] },
  { char: "ぜ", reading: "ze", examples: [ex("かぜ", "kaze", "감기", "cold"), ex("ぜんぜん", "zenzen", "전혀", "not at all")] },
  { char: "ぞ", reading: "zo", examples: [ex("かぞく", "kazoku", "가족", "family"), ex("どうぞ", "douzo", "제발", "please")] },
  { char: "だ", reading: "da", examples: [ex("だれ", "dare", "누구", "who"), ex("だいがく", "daigaku", "대학", "university")] },
  { char: "ぢ", reading: "ji", examples: [ex("はなぢ", "hanaji", "코피", "nosebleed")] },
  { char: "づ", reading: "zu", examples: [ex("つづく", "tsuzuku", "이어지다", "to continue")] },
  { char: "で", reading: "de", examples: [ex("でんわ", "denwa", "전화", "phone"), ex("でかける", "dekakeru", "나가다", "to go out")] },
  { char: "ど", reading: "do", examples: [ex("どこ", "doko", "어디", "where"), ex("ともだち", "tomodachi", "친구", "friend")] },
  { char: "ば", reading: "ba", examples: [ex("ばんごはん", "bangohan", "저녁", "dinner"), ex("ばあい", "baai", "경우", "case")] },
  { char: "び", reading: "bi", examples: [ex("びょういん", "byouin", "병원", "hospital"), ex("さびしい", "sabishii", "외로운", "lonely")] },
  { char: "ぶ", reading: "bu", examples: [ex("ぶた", "buta", "돼지", "pig"), ex("ぶんか", "bunka", "문화", "culture")] },
  { char: "べ", reading: "be", examples: [ex("べんきょう", "benkyou", "공부", "study"), ex("たべる", "taberu", "먹다", "to eat")] },
  { char: "ぼ", reading: "bo", examples: [ex("ぼうし", "boushi", "모자", "hat"), ex("ぼん", "bon", "트레이", "tray")] },
  { char: "ぱ", reading: "pa", examples: [ex("パン", "pan", "빵", "bread"), ex("いっぱい", "ippai", "가득", "full")] },
  { char: "ぴ", reading: "pi", examples: [ex("えんぴつ", "enpitsu", "연필", "pencil"), ex("ぴったり", "pittari", "딱", "exactly")] },
  { char: "ぷ", reading: "pu", examples: [ex("きっぷ", "kippu", "표", "ticket"), ex("アップル", "appuru", "사과", "apple")] },
  { char: "ぺ", reading: "pe", examples: [ex("ぺん", "pen", "펜", "pen"), ex("ぺらぺら", "perapera", "유창한", "fluent")] },
  { char: "ぽ", reading: "po", examples: [ex("ぽけっと", "poketto", "주머니", "pocket"), ex("しっぽ", "shippo", "꼬리", "tail")] },
];

function toKatakana(text: string): string {
  return Array.from(text)
    .map((ch) => {
      const code = ch.codePointAt(0);
      if (code && code >= 0x3041 && code <= 0x3096) {
        return String.fromCodePoint(code + 0x60);
      }
      return ch;
    })
    .join("");
}

const KATAKANA_EXAMPLES: Record<string, CharacterExample[]> = {
  ア: [ex("アメリカ", "amerika", "미국", "America"), ex("アイス", "aisu", "아이스크림", "ice cream")],
  イ: [ex("イタリア", "itaria", "이탈리아", "Italy"), ex("イス", "isu", "의자", "chair")],
  ウ: [ex("ウール", "uuru", "울", "wool"), ex("ウイルス", "uirusu", "바이러스", "virus")],
  エ: [ex("エレベーター", "erebeetaa", "엘리베이터", "elevator"), ex("エアコン", "eakon", "에어컨", "air con")],
  オ: [ex("オレンジ", "orenji", "오렌지", "orange"), ex("オフィス", "ofisu", "사무실", "office")],
  カ: [ex("カメラ", "kamera", "카메라", "camera"), ex("カード", "kaado", "카드", "card")],
  キ: [ex("キロ", "kiro", "킬로", "kilo"), ex("キャンプ", "kyanpu", "캠프", "camp")],
  ク: [ex("クラス", "kurasu", "반", "class"), ex("クリーム", "kuriimu", "크림", "cream")],
  ケ: [ex("ケーキ", "keeki", "케이크", "cake"), ex("ケース", "keesu", "케이스", "case")],
  コ: [ex("コーヒー", "koohii", "커피", "coffee"), ex("コート", "kooto", "코트", "coat")],
  サ: [ex("サラダ", "sarada", "샐러드", "salad"), ex("サービス", "saabisu", "서비스", "service")],
  シ: [ex("シャツ", "shatsu", "셔츠", "shirt"), ex("システム", "shisutemu", "시스템", "system")],
  ス: [ex("スポーツ", "supootsu", "스포츠", "sports"), ex("スーパー", "suupaa", "슈퍼", "supermarket")],
  セ: [ex("セーター", "seetaa", "스웨터", "sweater"), ex("センター", "sentaa", "센터", "center")],
  ソ: [ex("ソファ", "sofa", "소파", "sofa"), ex("ソース", "soosu", "소스", "sauce")],
  タ: [ex("タクシー", "takushii", "택시", "taxi"), ex("タオル", "taoru", "수건", "towel")],
  チ: [ex("チーズ", "chiizu", "치즈", "cheese"), ex("チケット", "chiketto", "티켓", "ticket")],
  ツ: [ex("ツアー", "tsuaa", "투어", "tour"), ex("ツナ", "tsuna", "참치", "tuna")],
  テ: [ex("テレビ", "terebi", "TV", "TV"), ex("テスト", "tesuto", "시험", "test")],
  ト: [ex("トマト", "tomato", "토마토", "tomato"), ex("トイレ", "toire", "화장실", "toilet")],
  ナ: [ex("ナイフ", "naifu", "나이프", "knife"), ex("ノート", "nooto", "공책", "notebook")],
  ニ: [ex("ニュース", "nyuusu", "뉴스", "news"), ex("ニット", "nitto", "니트", "knit")],
  ヌ: [ex("ヌードル", "nuudoru", "면", "noodle")],
  ネ: [ex("ネクタイ", "nekutai", "넥타이", "necktie"), ex("ネット", "netto", "인터넷", "net")],
  ノ: [ex("ノート", "nooto", "공책", "notebook"), ex("ノック", "nokku", "노크", "knock")],
  ハ: [ex("ハンバーガー", "hanbaagaa", "햄버거", "hamburger"), ex("ハート", "haato", "하트", "heart")],
  ヒ: [ex("ヒント", "hinto", "힌트", "hint"), ex("ヒーター", "hiitaa", "히터", "heater")],
  フ: [ex("フィルム", "firumu", "필름", "film"), ex("フォーク", "fooku", "포크", "fork")],
  ヘ: [ex("ヘリ", "heri", "헬기", "heli"), ex("ヘア", "hea", "헤어", "hair")],
  ホ: [ex("ホテル", "hoteru", "호텔", "hotel"), ex("ホーム", "hoomu", "홈", "home")],
  マ: [ex("マンゴー", "mangoo", "망고", "mango"), ex("マスク", "masuku", "마스크", "mask")],
  ミ: [ex("ミルク", "miruku", "우유", "milk"), ex("ミュージック", "myuujikku", "음악", "music")],
  ム: [ex("ムービー", "muubii", "영화", "movie"), ex("ムード", "muudo", "분위기", "mood")],
  メ: [ex("メニュー", "menyuu", "메뉴", "menu"), ex("メール", "meeru", "메일", "mail")],
  モ: [ex("モデル", "moderu", "모델", "model"), ex("モーター", "mootaa", "모터", "motor")],
  ヤ: [ex("ヤード", "yaado", "야드", "yard"), ex("ヤクルト", "yakuruto", "야쿠르트", "Yakult")],
  ユ: [ex("ユーモア", "yuumoa", "유머", "humor"), ex("ユーザー", "yuuzaa", "사용자", "user")],
  ヨ: [ex("ヨガ", "yoga", "요가", "yoga"), ex("ヨーグルト", "yooguruto", "요거트", "yogurt")],
  ラ: [ex("ラジオ", "rajio", "라디오", "radio"), ex("ラーメン", "raamen", "라면", "ramen")],
  リ: [ex("リモコン", "rimokon", "리모컨", "remote"), ex("リスト", "risuto", "목록", "list")],
  ル: [ex("ルール", "ruuru", "규칙", "rule"), ex("ルーム", "ruumu", "방", "room")],
  レ: [ex("レストラン", "resutoran", "식당", "restaurant"), ex("レモン", "remon", "레몬", "lemon")],
  ロ: [ex("ロボット", "robotto", "로봇", "robot"), ex("ロック", "rokku", "록", "rock")],
  ワ: [ex("ワイン", "wain", "와인", "wine"), ex("ワット", "watto", "와트", "watt")],
  ヲ: [ex("ヲタク", "otaku", "오타쿠", "otaku")],
  ン: [ex("パン", "pan", "빵", "bread"), ex("ペン", "pen", "펜", "pen")],
  ガ: [ex("ガス", "gasu", "가스", "gas"), ex("ガイド", "gaido", "가이드", "guide")],
  ギ: [ex("ギター", "gitaa", "기타", "guitar"), ex("ギフト", "gifuto", "선물", "gift")],
  グ: [ex("グループ", "guruupu", "그룹", "group"), ex("グラス", "gurasu", "잔", "glass")],
  ゲ: [ex("ゲーム", "geemu", "게임", "game"), ex("ゲート", "geeto", "게이트", "gate")],
  ゴ: [ex("ゴルフ", "gorufu", "골프", "golf"), ex("ゴール", "gooru", "골", "goal")],
  ザ: [ex("デザイン", "dezain", "디자인", "design")],
  ジ: [ex("ジーンズ", "jiinzu", "청바지", "jeans"), ex("ジュース", "juusu", "주스", "juice")],
  ズ: [ex("ズボン", "zubon", "바지", "pants")],
  ゼ: [ex("ゼロ", "zero", "영", "zero")],
  ゾ: [ex("ゾーン", "zoon", "존", "zone")],
  ダ: [ex("ダンス", "dansu", "댄스", "dance"), ex("ダウンロード", "daunroodo", "다운로드", "download")],
  デ: [ex("デパート", "depaato", "백화점", "department store"), ex("データ", "deeta", "데이터", "data")],
  ド: [ex("ドア", "doa", "문", "door"), ex("ドリンク", "dorinku", "음료", "drink")],
  バ: [ex("バス", "basu", "버스", "bus"), ex("バナナ", "banana", "바나나", "banana")],
  ビ: [ex("ビール", "biiru", "맥주", "beer"), ex("ビデオ", "bideo", "비디오", "video")],
  ブ: [ex("ブルー", "buruu", "파랑", "blue"), ex("バッグ", "baggu", "가방", "bag")],
  ベ: [ex("ベッド", "beddo", "침대", "bed"), ex("ベルト", "beruto", "벨트", "belt")],
  ボ: [ex("ボール", "booru", "공", "ball"), ex("ボタン", "botan", "단추", "button")],
  パ: [ex("パン", "pan", "빵", "bread"), ex("パソコン", "pasokon", "PC", "PC")],
  ピ: [ex("ピアノ", "piano", "피아노", "piano"), ex("ピザ", "piza", "피자", "pizza")],
  プ: [ex("プール", "puuru", "수영장", "pool"), ex("プレゼント", "purezento", "선물", "present")],
  ペ: [ex("ペン", "pen", "펜", "pen"), ex("ペット", "petto", "반려동물", "pet")],
  ポ: [ex("ポスト", "posuto", "우체통", "post"), ex("ポイント", "pointo", "포인트", "point")],
};

function kanaItems(
  rows: KanaRow[],
  category: "hiragana" | "katakana",
): CharacterItem[] {
  return rows.map((row) => {
    const katakana = category === "katakana";
    const character = katakana ? toKatakana(row.char) : row.char;
    const examples = katakana
      ? KATAKANA_EXAMPLES[character] ?? []
      : row.examples;
    return {
      id: `ja-${category}-${row.reading}-${character}`,
      character,
      reading: row.reading,
      pronunciation: row.reading,
      category,
      examples,
    };
  });
}

const KANJI: CharacterItem[] = [
  {
    id: "ja-kanji-hito",
    character: "人",
    reading: "ひと / ジン",
    pronunciation: "hito",
    category: "kanji",
    meaning: m("사람", "person"),
    usage: m("사람을 가리킬 때", "people"),
    examples: [ex("ひと", "hito", "사람", "person"), ex("日本人", "nihonjin", "일본인", "Japanese person")],
  },
  {
    id: "ja-kanji-hi",
    character: "日",
    reading: "ひ / ニチ",
    pronunciation: "hi",
    category: "kanji",
    meaning: m("해, 날", "sun / day"),
    usage: m("날짜·일본을 말할 때", "dates, Japan"),
    examples: [ex("今日", "kyou", "오늘", "today"), ex("日本", "nihon", "일본", "Japan")],
  },
  {
    id: "ja-kanji-tsuki",
    character: "月",
    reading: "つき / ゲツ",
    pronunciation: "tsuki",
    category: "kanji",
    meaning: m("달, 월", "moon / month"),
    examples: [ex("つき", "tsuki", "달", "moon"), ex("一月", "ichigatsu", "1월", "January")],
  },
  {
    id: "ja-kanji-ima",
    character: "今",
    reading: "いま / コン",
    pronunciation: "ima",
    category: "kanji",
    meaning: m("지금", "now"),
    examples: [ex("いま", "ima", "지금", "now"), ex("今日", "kyou", "오늘", "today")],
  },
  {
    id: "ja-kanji-gaku",
    character: "学",
    reading: "まな(ぶ) / ガク",
    pronunciation: "gaku",
    category: "kanji",
    meaning: m("배우다", "to learn"),
    examples: [ex("学ぶ", "manabu", "배우다", "to learn"), ex("学生", "gakusei", "학생", "student")],
  },
  {
    id: "ja-kanji-sei",
    character: "生",
    reading: "い(きる) / セイ",
    pronunciation: "sei",
    category: "kanji",
    meaning: m("살다, 생", "life / to live"),
    examples: [ex("学生", "gakusei", "학생", "student"), ex("先生", "sensei", "선생님", "teacher")],
  },
  {
    id: "ja-kanji-dai",
    character: "大",
    reading: "おお(きい) / ダイ",
    pronunciation: "oo",
    category: "kanji",
    meaning: m("크다", "big"),
    examples: [ex("大きい", "ookii", "크다", "big"), ex("大学", "daigaku", "대학", "university")],
  },
  {
    id: "ja-kanji-shou",
    character: "小",
    reading: "ちい(さい) / ショウ",
    pronunciation: "chii",
    category: "kanji",
    meaning: m("작다", "small"),
    examples: [ex("小さい", "chiisai", "작다", "small"), ex("小学校", "shougakkou", "초등학교", "elementary school")],
  },
  {
    id: "ja-kanji-naka",
    character: "中",
    reading: "なか / チュウ",
    pronunciation: "naka",
    category: "kanji",
    meaning: m("안, 가운데", "inside / middle"),
    examples: [ex("なか", "naka", "안", "inside"), ex("中国", "chuugoku", "중국", "China")],
  },
  {
    id: "ja-kanji-kuni",
    character: "国",
    reading: "くに / コク",
    pronunciation: "kuni",
    category: "kanji",
    meaning: m("나라", "country"),
    examples: [ex("くに", "kuni", "나라", "country"), ex("外国", "gaikoku", "외국", "foreign country")],
  },
  {
    id: "ja-kanji-yama",
    character: "山",
    reading: "やま / サン",
    pronunciation: "yama",
    category: "kanji",
    meaning: m("산", "mountain"),
    examples: [ex("やま", "yama", "산", "mountain"), ex("富士山", "fujisan", "후지산", "Mt. Fuji")],
  },
  {
    id: "ja-kanji-kawa",
    character: "川",
    reading: "かわ / セン",
    pronunciation: "kawa",
    category: "kanji",
    meaning: m("강", "river"),
    examples: [ex("かわ", "kawa", "강", "river")],
  },
  {
    id: "ja-kanji-mizu",
    character: "水",
    reading: "みず / スイ",
    pronunciation: "mizu",
    category: "kanji",
    meaning: m("물", "water"),
    examples: [ex("みず", "mizu", "물", "water"), ex("水曜日", "suiyoubi", "수요일", "Wednesday")],
  },
  {
    id: "ja-kanji-hi-fire",
    character: "火",
    reading: "ひ / カ",
    pronunciation: "hi",
    category: "kanji",
    meaning: m("불", "fire"),
    examples: [ex("ひ", "hi", "불", "fire"), ex("火曜日", "kayoubi", "화요일", "Tuesday")],
  },
  {
    id: "ja-kanji-ki",
    character: "木",
    reading: "き / モク",
    pronunciation: "ki",
    category: "kanji",
    meaning: m("나무", "tree"),
    examples: [ex("き", "ki", "나무", "tree"), ex("木曜日", "mokuyoubi", "목요일", "Thursday")],
  },
  {
    id: "ja-kanji-kane",
    character: "金",
    reading: "かね / キン",
    pronunciation: "kane",
    category: "kanji",
    meaning: m("금, 돈", "gold / money"),
    examples: [ex("おかね", "okane", "돈", "money"), ex("金曜日", "kinyoubi", "금요일", "Friday")],
  },
  {
    id: "ja-kanji-tsuchi",
    character: "土",
    reading: "つち / ド",
    pronunciation: "tsuchi",
    category: "kanji",
    meaning: m("흙", "earth"),
    examples: [ex("つち", "tsuchi", "흙", "soil"), ex("土曜日", "doyoubi", "토요일", "Saturday")],
  },
  {
    id: "ja-kanji-miru",
    character: "見",
    reading: "み(る) / ケン",
    pronunciation: "mi",
    category: "kanji",
    meaning: m("보다", "to see"),
    examples: [ex("見る", "miru", "보다", "to see"), ex("見せる", "miseru", "보여 주다", "to show")],
  },
  {
    id: "ja-kanji-iku",
    character: "行",
    reading: "い(く) / コウ",
    pronunciation: "iku",
    category: "kanji",
    meaning: m("가다", "to go"),
    examples: [ex("行く", "iku", "가다", "to go"), ex("銀行", "ginkou", "은행", "bank")],
  },
  {
    id: "ja-kanji-taberu",
    character: "食",
    reading: "た(べる) / ショク",
    pronunciation: "tabe",
    category: "kanji",
    meaning: m("먹다", "to eat"),
    examples: [ex("食べる", "taberu", "먹다", "to eat"), ex("食事", "shokuji", "식사", "meal")],
  },
  {
    id: "ja-kanji-nomu",
    character: "飲",
    reading: "の(む) / イン",
    pronunciation: "nomu",
    category: "kanji",
    meaning: m("마시다", "to drink"),
    examples: [ex("飲む", "nomu", "마시다", "to drink"), ex("飲み物", "nomimono", "음료", "drink")],
  },
  {
    id: "ja-kanji-hanasu",
    character: "話",
    reading: "はな(す) / ワ",
    pronunciation: "hana",
    category: "kanji",
    meaning: m("말하다", "to speak"),
    examples: [ex("話す", "hanasu", "말하다", "to speak"), ex("電話", "denwa", "전화", "phone")],
  },
  {
    id: "ja-kanji-tomo",
    character: "友",
    reading: "とも / ユウ",
    pronunciation: "tomo",
    category: "kanji",
    meaning: m("친구", "friend"),
    examples: [ex("友だち", "tomodachi", "친구", "friend")],
  },
  {
    id: "ja-kanji-watashi",
    character: "私",
    reading: "わたし / シ",
    pronunciation: "watashi",
    category: "kanji",
    meaning: m("나", "I / me"),
    examples: [ex("わたし", "watashi", "나", "I")],
  },
];

export const JA_GUIDE: CharacterGuide = {
  language: "ja",
  categories: [
    { id: "hiragana", label: m("히라가나", "Hiragana") },
    { id: "katakana", label: m("가타카나", "Katakana") },
    { id: "kanji", label: m("기초 한자", "Basic kanji") },
  ],
  items: [
    ...kanaItems(HIRAGANA, "hiragana"),
    ...kanaItems(DAKUTEN, "hiragana"),
    ...kanaItems(HIRAGANA, "katakana"),
    ...kanaItems(DAKUTEN, "katakana"),
    ...KANJI,
  ],
};
