import type { DiscoveryTopicId } from "@/lib/contentDiscovery/topicCategories";
import type { LearningLanguageCode } from "@/lib/learningLanguages";

/**
 * What a native speaker would type into YouTube / News / Wikipedia.
 * Do not append the English language name ("Italian") to these.
 */
const NATIVE_TERMS: Record<
  DiscoveryTopicId,
  Record<LearningLanguageCode, string[]>
> = {
  any: {
    en: ["everyday conversation", "vlog"],
    ko: ["일상 대화", "브이로그"],
    ja: ["日常会話", "会話"],
    zh: ["日常对话", "口语"],
    es: ["conversación cotidiana", "vlog"],
    fr: ["conversation quotidienne", "vlog"],
    it: ["conversazione", "vita quotidiana"],
    pt: ["conversa do dia a dia", "vlog"],
    ru: ["разговор", "повседневная речь"],
  },
  daily: {
    en: ["everyday conversation", "daily life"],
    ko: ["일상 대화", "일상 브이로그"],
    ja: ["日常会話", "雑談"],
    zh: ["日常对话", "生活"],
    es: ["conversación cotidiana", "día a día"],
    fr: ["vie quotidienne", "conversation"],
    it: ["vita quotidiana", "chiacchiere"],
    pt: ["dia a dia", "conversa casual"],
    ru: ["повседневный разговор", "будни"],
  },
  travel: {
    en: ["travel", "travel vlog", "trip"],
    ko: ["여행", "여행 브이로그"],
    ja: ["旅行", "旅 vlog"],
    zh: ["旅行", "旅游"],
    es: ["viaje", "vacaciones", "turismo"],
    fr: ["voyage", "vacances", "tourisme"],
    it: ["viaggio", "vacanza", "turismo"],
    pt: ["viagem", "férias", "turismo"],
    ru: ["путешествие", "отпуск", "туризм"],
  },
  food: {
    en: ["cooking", "recipe", "food"],
    ko: ["요리", "레시피", "먹방"],
    ja: ["料理", "レシピ", "グルメ"],
    zh: ["美食", "做饭", "食谱"],
    es: ["comida", "recetas", "cocina"],
    fr: ["cuisine", "recettes", "nourriture"],
    it: ["cucina", "ricette", "cibo"],
    pt: ["comida", "receitas", "culinária"],
    ru: ["еда", "рецепты", "готовка"],
  },
  work: {
    en: ["office", "work meeting", "career"],
    ko: ["직장", "회사 생활", "회의"],
    ja: ["仕事", "会社", "会議"],
    zh: ["工作", "职场", "开会"],
    es: ["trabajo", "oficina", "reunión"],
    fr: ["travail", "bureau", "réunion"],
    it: ["lavoro", "ufficio", "riunione"],
    pt: ["trabalho", "escritório", "reunião"],
    ru: ["работа", "офис", "совещание"],
  },
  news: {
    en: ["news", "current events"],
    ko: ["뉴스", "시사"],
    ja: ["ニュース", "時事"],
    zh: ["新闻", "时事"],
    es: ["noticias", "actualidad"],
    fr: ["actualités", "infos"],
    it: ["notizie", "attualità"],
    pt: ["notícias", "atualidades"],
    ru: ["новости", "события"],
  },
  school: {
    en: ["university", "classroom", "study"],
    ko: ["학교", "공부", "대학"],
    ja: ["学校", "勉強", "大学"],
    zh: ["学校", "学习", "大学"],
    es: ["escuela", "universidad", "estudiar"],
    fr: ["école", "université", "étudier"],
    it: ["scuola", "università", "studiare"],
    pt: ["escola", "universidade", "estudar"],
    ru: ["школа", "учёба", "университет"],
  },
  entertainment: {
    en: ["drama", "movie clip", "TV show"],
    ko: ["드라마", "예능", "영화"],
    ja: ["ドラマ", "映画", "バラエティ"],
    zh: ["电视剧", "综艺", "电影"],
    es: ["serie", "película", "programa"],
    fr: ["série", "film", "émission"],
    it: ["serie TV", "film", "programma"],
    pt: ["série", "filme", "programa"],
    ru: ["сериал", "фильм", "шоу"],
  },
  sports: {
    en: ["sports", "football match"],
    ko: ["스포츠", "축구"],
    ja: ["スポーツ", "サッカー"],
    zh: ["体育", "足球"],
    es: ["deportes", "fútbol"],
    fr: ["sport", "football"],
    it: ["sport", "calcio"],
    pt: ["esporte", "futebol"],
    ru: ["спорт", "футбол"],
  },
  tech: {
    en: ["technology", "science"],
    ko: ["IT", "과학", "기술"],
    ja: ["テクノロジー", "科学"],
    zh: ["科技", "科学"],
    es: ["tecnología", "ciencia"],
    fr: ["technologie", "science"],
    it: ["tecnologia", "scienza"],
    pt: ["tecnologia", "ciência"],
    ru: ["технологии", "наука"],
  },
  culture: {
    en: ["culture", "tradition", "city life"],
    ko: ["문화", "전통", "도시 생활"],
    ja: ["文化", "伝統", "暮らし"],
    zh: ["文化", "传统", "城市生活"],
    es: ["cultura", "tradición"],
    fr: ["culture", "tradition"],
    it: ["cultura", "tradizione", "vita in città"],
    pt: ["cultura", "tradição"],
    ru: ["культура", "традиции"],
  },
  health: {
    en: ["health", "fitness"],
    ko: ["건강", "운동"],
    ja: ["健康", "フィットネス"],
    zh: ["健康", "健身"],
    es: ["salud", "fitness"],
    fr: ["santé", "sport"],
    it: ["salute", "fitness"],
    pt: ["saúde", "fitness"],
    ru: ["здоровье", "фитнес"],
  },
  music: {
    en: ["music", "live concert"],
    ko: ["음악", "라이브"],
    ja: ["音楽", "ライブ"],
    zh: ["音乐", "演唱会"],
    es: ["música", "concierto"],
    fr: ["musique", "concert"],
    it: ["musica", "concerto"],
    pt: ["música", "show"],
    ru: ["музыка", "концерт"],
  },
  family: {
    en: ["family", "parenting"],
    ko: ["가족", "육아"],
    ja: ["家族", "子育て"],
    zh: ["家庭", "育儿"],
    es: ["familia", "crianza"],
    fr: ["famille", "parentalité"],
    it: ["famiglia", "genitori"],
    pt: ["família", "criação dos filhos"],
    ru: ["семья", "дети"],
  },
  interview: {
    en: ["interview", "podcast", "talk"],
    ko: ["인터뷰", "토크"],
    ja: ["インタビュー", "対談"],
    zh: ["访谈", "播客"],
    es: ["entrevista", "podcast"],
    fr: ["interview", "podcast"],
    it: ["intervista", "podcast", "talk"],
    pt: ["entrevista", "podcast"],
    ru: ["интервью", "подкаст"],
  },
  vlog: {
    en: ["vlog", "day in my life"],
    ko: ["브이로그", "하루 브이로그"],
    ja: ["vlog", "日常"],
    zh: ["vlog", "日常"],
    es: ["vlog", "un día en mi vida"],
    fr: ["vlog", "une journée"],
    it: ["vlog", "una giornata"],
    pt: ["vlog", "um dia na minha vida"],
    ru: ["влог", "один день из жизни"],
  },
  shopping: {
    en: ["shopping", "fashion haul"],
    ko: ["쇼핑", "패션"],
    ja: ["買い物", "ファッション"],
    zh: ["购物", "穿搭"],
    es: ["compras", "moda"],
    fr: ["shopping", "mode"],
    it: ["shopping", "moda"],
    pt: ["compras", "moda"],
    ru: ["шопинг", "мода"],
  },
  finance: {
    en: ["finance", "economy", "investing"],
    ko: ["경제", "재테크"],
    ja: ["経済", "投資"],
    zh: ["经济", "理财"],
    es: ["economía", "finanzas"],
    fr: ["économie", "finance"],
    it: ["economia", "finanza"],
    pt: ["economia", "finanças"],
    ru: ["экономика", "финансы"],
  },
  nature: {
    en: ["nature", "animals", "wildlife"],
    ko: ["자연", "동물"],
    ja: ["自然", "動物"],
    zh: ["自然", "动物"],
    es: ["naturaleza", "animales"],
    fr: ["nature", "animaux"],
    it: ["natura", "animali"],
    pt: ["natureza", "animais"],
    ru: ["природа", "животные"],
  },
  hobbies: {
    en: ["hobby", "gaming", "how to"],
    ko: ["취미", "게임"],
    ja: ["趣味", "ゲーム"],
    zh: ["爱好", "游戏"],
    es: ["hobby", "videojuegos"],
    fr: ["loisir", "jeux vidéo"],
    it: ["hobby", "videogiochi"],
    pt: ["hobby", "games"],
    ru: ["хобби", "игры"],
  },
};

export function nativeSearchTerms(
  topicId: DiscoveryTopicId | undefined,
  language: LearningLanguageCode,
): string[] {
  const id = topicId && topicId in NATIVE_TERMS ? topicId : "any";
  return NATIVE_TERMS[id][language] ?? NATIVE_TERMS[id].en;
}
