// Localized copy for the nine store-canvas scenes. Every listing learns English;
// the app UI, headlines and translations are in the listing's language.

export const EN = {
  L1: "Hey! How's your day going?",
  me1: "I just got home from work.",
  L2: "Nice! What do you like to do after work?",
  me2: "I usually watch movies.",
  L3: "Cool! What kind of movies do you like?",
  L4: "Cool! What kind of books do you enjoy?",
  me4: "Um, I...",
  L5: "I like fantasy and mystery books.",
  L6: "What do you do on weekends?",
  L7: "No rush. Do you like playing sports?",
  me7: "Yes, I play soccer with my friends.",
  L8: "Nice! Where do you play?",
  L9: "Hi! How was your weekend?",
  me9: "Good! I saw a movie with a friend.",
  L10: "Oh, which movie did you see?",
  me10: "An action movie. It was so fun!",
  L11: "Nice! Did you get popcorn?",
  seg1: "This market opens every morning at six.",
  L12: "You have to try the noodles here. They're amazing.",
  seg3: "Let's grab a table before it gets busy.",
  L13: "I usually grab a coffee before work.",
  L14: "grab a coffee",
  L16: "Any fun plans for the weekend?",
  ex1: "What are your plans for the summer?",
  ex2: "Do you have any ideas for the project?",
};

export const LOCALES = {
  "ko-KR": {
    lang: "ko", dir: "1_한국",
    font: "'Noto Sans CJK KR', 'Noto Sans', sans-serif",
    ui: {
      stop: "중단", friend: "친구", inputHint: "편하게 아무 얘기나 해 보세요.", translate: "해석",
      seeWhy: "왜 막혔는지 보기", stuckTitle: "막혔던 지점", couldSay: "이렇게 말할 수 있었어요", heard: "이렇게 들렸어요",
      allRecognized: "모든 단어가 정확히 인식되었어요.", tryAgain: "다시 해보기", close: "닫기",
      otherVideos: "다른 영상", videoLessons: "영상 학습", merge: "구간 묶기", split: "구간 쪼개기",
      loop: "반복 ×3", keyExpr: "핵심 표현", saved: "저장됨", savedToBook: "단어장에 저장됨",
      sentence: "문장", role: "통사", usage: "쓰임", form: "형태", examples: "다른 예문",
      iSpeak: "내 언어", learning: "배울 언어", more: "+ 9개 언어 더",
      chatInTarget: "영어로 대화", learnExpr: "표현 알아보기", inputChat: "영어로 써보세요. 막히면 한국어도 돼요",
      tabs: ["지도", "채팅", "통화", "영상 학습", "단어장"],
    },
    native: "한국어", targets: ["English", "日本語", "中文", "Español"],
    heads: [
      ["AI 영어 회화", "AI 친구와\n편하게 영어 수다", "말하면 바로 답하고, 해석도 같이 보여줘요"],
      ["통화 학습", "말이 막혀도\n이유를 알려줘요", "이렇게 말할 수 있었어요, 발음 확인까지"],
      ["막혀도 괜찮아요", "머뭇거리면\n천천히 다시 물어봐요", "모르는 말은 한국어로 풀어줘요"],
      ["영어 회화 연습", "친구랑 수다 떨듯\n영어로 말해요", "정해진 대본 없이, 하고 싶은 말을 그대로"],
      ["14개 언어", "내 언어로 배우고\n원하는 언어로 말하기", "학습 언어와 앱 언어를 자유롭게 골라요"],
      ["영상 학습", "진짜 영상을\n한 문장씩 나눠서", "문장을 누르면 그 부분만 다시 재생돼요"],
      ["영상 학습", "다시 듣고, 저장하고,\n내 것으로", "원하는 문장을 반복하고 단어장에 모아요"],
      ["한국어로 써도 OK", "하고 싶은 말을 쓰면\n영어로 바꿔줘요", "편한 말로 써도 대화는 계속 이어져요"],
      ["단어 하나까지", "단어를 누르면\n이유까지 알려줘요", "문법, 쓰임, 예문을 한국어로"],
    ],
    t: {
      L1: "안녕! 오늘 하루 어때?", L2: "좋네! 퇴근하고 보통 뭐 해?", L3: "멋지다! 어떤 영화 좋아해?",
      L4: "좋네! 어떤 책 좋아해?", L5: "저는 판타지랑 미스터리 책을 좋아해요.", L6: "주말에 보통 뭐 해?",
      L7: "천천히 해요. “Do you like playing sports?”는 ‘운동하는 거 좋아해?’라는 뜻이에요.",
      L8: "좋다! 어디서 해?", L9: "안녕! 주말 잘 보냈어?", L10: "오, 무슨 영화 봤어?", L11: "좋다! 팝콘도 먹었어?",
      L12: "여기 국수는 꼭 먹어봐야 해. 진짜 맛있어.", L13: "나는 보통 출근 전에 커피 한잔해.", L14: "커피 한잔하다",
      L15: "안녕, 좋은 아침이야!", L16: "주말에 재밌는 계획 있어?",
      L19: "질문은 이해했지만 장르 이름이 바로 떠오르지 않아 잠깐 머뭇거렸어요.",
      forMain: "여기서 ‘for’는 주말을 위한 계획이라는 뜻이에요.",
      forRole: "‘plans’ 뒤에서 언제를 위한 계획인지 이어줘요.",
      forUsage: "특정한 시간이나 목적을 나타낼 때 써요.",
      forForm: "형태가 바뀌지 않아요.",
      ex1: "여름에 무슨 계획 있어?", ex2: "프로젝트에 대한 아이디어 있어?",
    },
  },
  "ja-JP": {
    lang: "ja", dir: "2_일본",
    font: "'Noto Sans CJK JP', 'Noto Sans', sans-serif",
    ui: {
      stop: "中断", friend: "友だち", inputHint: "気軽に何でも話してみよう。", translate: "訳",
      seeWhy: "詰まった理由を見る", stuckTitle: "つまずいたポイント", couldSay: "こう言えました", heard: "こう聞こえました",
      allRecognized: "すべての単語が正しく認識されました。", tryAgain: "もう一度", close: "閉じる",
      otherVideos: "ほかの動画", videoLessons: "動画学習", merge: "区間を結合", split: "区間を分割",
      loop: "繰り返し ×3", keyExpr: "キーフレーズ", saved: "保存済み", savedToBook: "単語帳に保存しました",
      sentence: "文", role: "構文", usage: "使い方", form: "形", examples: "ほかの例文",
      iSpeak: "自分の言語", learning: "学ぶ言語", more: "+ ほか9言語",
      chatInTarget: "英語で会話", learnExpr: "表現を調べる", inputChat: "英語で書いてみよう。詰まったら日本語でもOK",
      tabs: ["マップ", "チャット", "通話", "動画学習", "単語帳"],
    },
    native: "日本語", targets: ["English", "한국어", "中文", "Español"],
    heads: [
      ["AI英会話", "AIの友だちと\n気軽に英語でおしゃべり", "すぐ返事が来て、訳も一緒に見られます"],
      ["通話で練習", "言葉に詰まっても\n理由がわかる", "言えたはずの一言と、発音チェックまで"],
      ["詰まっても大丈夫", "迷ったら\nゆっくり聞き直してくれる", "わからない言葉は日本語で説明"],
      ["英会話の練習", "友だちと話すように\n英語で話そう", "台本なしで、言いたいことをそのまま"],
      ["14の言語", "自分の言語で学んで\n好きな言語で話す", "学ぶ言語もアプリの言語も自由に選べます"],
      ["動画で学ぶ", "本物の動画を\n一文ずつに", "文をタップすると、その部分だけ再生"],
      ["動画で学ぶ", "聞き直して、保存して、\n自分のものに", "好きな文を繰り返し、単語帳にまとめる"],
      ["日本語で書いてもOK", "言いたいことを書けば\n英語にしてくれる", "日本語で書いても、会話はそのまま続きます"],
      ["一語ずつ", "単語をタップすると\n理由までわかる", "文法・使い方・例文を日本語で"],
    ],
    t: {
      L1: "やあ！今日はどんな一日？", L2: "いいね！仕事のあとは何してるの？", L3: "いいね！どんな映画が好き？",
      L4: "いいね！どんな本が好き？", L5: "ファンタジーとミステリーの本が好きです。", L6: "週末はいつも何してる？",
      L7: "ゆっくりで大丈夫。“Do you like playing sports?”は「スポーツするのは好き？」という意味です。",
      L8: "いいね！どこでやってるの？", L9: "やあ！週末はどうだった？", L10: "へえ、何の映画を見たの？", L11: "いいね！ポップコーンも食べた？",
      L12: "ここの麺はぜひ食べてみて。すごくおいしいよ。", L13: "仕事の前にいつもコーヒーを買うんだ。", L14: "コーヒーを買う・飲む",
      L15: "おはよう！", L16: "週末、何か楽しい予定ある？",
      L19: "質問は理解できましたが、ジャンル名がすぐに出てこなかったようです。",
      forMain: "ここでの「for」は「週末の（ための）予定」という意味です。",
      forRole: "「plans」のあとで、いつのための予定かをつなぎます。",
      forUsage: "特定の時間や目的を表すときに使います。",
      forForm: "形は変わりません。",
      ex1: "夏の予定は何？", ex2: "プロジェクトのアイデアはある？",
    },
  },
  "zh-CN": {
    lang: "zh", dir: "3_중국",
    font: "'Noto Sans CJK SC', 'Noto Sans', sans-serif",
    ui: {
      stop: "结束", friend: "朋友", inputHint: "随便聊点什么吧。", translate: "翻译",
      seeWhy: "看看卡在哪儿", stuckTitle: "卡住的地方", couldSay: "可以这样说", heard: "听到的是",
      allRecognized: "所有单词都识别正确。", tryAgain: "再试一次", close: "关闭",
      otherVideos: "其他视频", videoLessons: "视频学习", merge: "合并片段", split: "拆分片段",
      loop: "循环 ×3", keyExpr: "重点表达", saved: "已收藏", savedToBook: "已存入单词本",
      sentence: "句子", role: "句法", usage: "用法", form: "形式", examples: "更多例句",
      iSpeak: "我的语言", learning: "学习语言", more: "+ 另外9种语言",
      chatInTarget: "用英语聊", learnExpr: "查看表达", inputChat: "用英语写写看，卡住了用中文也行",
      tabs: ["地图", "聊天", "通话", "视频学习", "单词本"],
    },
    native: "中文", targets: ["English", "日本語", "한국어", "Español"],
    heads: [
      ["AI英语会话", "和AI朋友\n轻松聊英语", "马上回复，翻译也一起显示"],
      ["通话练习", "说不出来时，\n告诉你原因", "本可以这样说，还能检查发音"],
      ["卡住也没关系", "犹豫时，\n慢慢再问你一次", "不懂的话用中文解释"],
      ["英语会话练习", "像和朋友聊天一样\n说英语", "没有剧本，想说什么就说什么"],
      ["14种语言", "用母语学习，\n用想学的语言交流", "学习语言和界面语言自由选择"],
      ["视频学习", "真实视频\n按句拆分", "点一下句子，只重播那一段"],
      ["视频学习", "重听、收藏，\n变成自己的", "反复听喜欢的句子，收进单词本"],
      ["用中文写也可以", "写下想说的话，\n帮你变成英语", "用中文写，对话照样继续"],
      ["逐词理解", "点一下单词，\n连原因都告诉你", "语法、用法和例句，用中文讲解"],
    ],
    t: {
      L1: "嗨！今天过得怎么样？", L2: "不错！下班后你一般做什么？", L3: "酷！你喜欢什么样的电影？",
      L4: "不错！你喜欢什么样的书？", L5: "我喜欢奇幻和推理小说。", L6: "你周末一般做什么？",
      L7: "慢慢来。“Do you like playing sports?”的意思是“你喜欢运动吗？”",
      L8: "不错！在哪儿踢？", L9: "嗨！周末过得怎么样？", L10: "哦，看的什么电影？", L11: "不错！吃爆米花了吗？",
      L12: "这里的面一定要尝尝，特别好吃。", L13: "我上班前通常会买杯咖啡。", L14: "买杯咖啡",
      L15: "嗨，早上好！", L16: "周末有什么好玩的计划吗？",
      L19: "你听懂了问题，但一时想不起类型的名称，所以犹豫了一下。",
      forMain: "这里的“for”表示“为周末安排的”计划。",
      forRole: "接在“plans”后面，说明计划是为哪个时间的。",
      forUsage: "用来表示特定的时间或目的。",
      forForm: "形式不变。",
      ex1: "你夏天有什么计划？", ex2: "你对这个项目有什么想法吗？",
    },
  },
  "es-ES": {
    lang: "es", dir: "4_스페인",
    font: "'Noto Sans', sans-serif",
    ui: {
      stop: "Parar", friend: "amigo", inputHint: "Habla de lo que quieras.", translate: "Traducción",
      seeWhy: "Ver por qué me trabé", stuckTitle: "Dónde te trabaste", couldSay: "Podrías haber dicho", heard: "Esto es lo que oímos",
      allRecognized: "Todas las palabras se reconocieron bien.", tryAgain: "Intentar de nuevo", close: "Cerrar",
      otherVideos: "Otros vídeos", videoLessons: "Vídeos", merge: "Unir", split: "Dividir",
      loop: "Repetir ×3", keyExpr: "Expresión clave", saved: "Guardada", savedToBook: "Guardada en tu vocabulario",
      sentence: "Frase", role: "Sintaxis", usage: "Uso", form: "Forma", examples: "Más ejemplos",
      iSpeak: "Hablo", learning: "Aprendo", more: "+ 9 idiomas más",
      chatInTarget: "Hablar en inglés", learnExpr: "Ver expresiones", inputChat: "Escribe en inglés, o en español si te atascas",
      tabs: ["Mapa", "Chat", "Llamar", "Vídeo", "Vocabulario"],
    },
    native: "Español", targets: ["English", "Français", "Italiano", "Português"],
    heads: [
      ["CONVERSACIÓN CON IA", "Habla inglés\ncon un amigo IA", "Responde al instante y te muestra la traducción"],
      ["PRACTICA HABLANDO", "¿Te quedas en blanco?\nTe dice por qué", "Lo que podrías haber dicho y tu pronunciación"],
      ["SIN PRISA", "Si dudas,\nte lo pregunta otra vez", "Te explica en español lo que no entiendes"],
      ["PRACTICA INGLÉS", "Habla inglés como si\ncharlaras con un amigo", "Sin guiones: di lo que quieras decir"],
      ["14 IDIOMAS", "Aprende en tu idioma,\nhabla en el que quieras", "Elige el idioma de estudio y el de la app"],
      ["APRENDE CON VÍDEOS", "Vídeos reales,\nfrase a frase", "Toca una frase para escuchar solo esa parte"],
      ["APRENDE CON VÍDEOS", "Repite, guarda\ny hazlo tuyo", "Repite la frase que quieras y guárdala"],
      ["ESCRIBE EN ESPAÑOL", "Escribe lo que quieres.\nTe sale en inglés.", "Escribe en español y la conversación sigue"],
      ["PALABRA POR PALABRA", "Toca una palabra\ny entiende el porqué", "Gramática, uso y ejemplos, en español"],
    ],
    t: {
      L1: "¡Hola! ¿Qué tal tu día?", L2: "¡Genial! ¿Qué te gusta hacer después del trabajo?", L3: "¡Qué bien! ¿Qué tipo de películas te gustan?",
      L4: "¡Qué bien! ¿Qué tipo de libros te gustan?", L5: "Me gustan los libros de fantasía y de misterio.", L6: "¿Qué haces los fines de semana?",
      L7: "Sin prisa. “Do you like playing sports?” significa «¿Te gusta hacer deporte?».",
      L8: "¡Genial! ¿Dónde juegas?", L9: "¡Hola! ¿Qué tal el fin de semana?", L10: "Ah, ¿qué película viste?", L11: "¡Genial! ¿Comiste palomitas?",
      L12: "Tienes que probar los fideos de aquí. Están buenísimos.", L13: "Normalmente me tomo un café antes del trabajo.", L14: "tomarse un café",
      L15: "¡Hola, buenos días!", L16: "¿Algún plan divertido para el fin de semana?",
      L19: "Entendiste la pregunta, pero no te salió a tiempo el nombre de los géneros.",
      forMain: "Aquí “for” indica que los planes son para el fin de semana.",
      forRole: "Va después de “plans” y dice para cuándo son.",
      forUsage: "Se usa para indicar un momento o un propósito.",
      forForm: "No cambia de forma.",
      ex1: "¿Qué planes tienes para el verano?", ex2: "¿Tienes alguna idea para el proyecto?",
    },
  },
  "hi-IN": {
    lang: "hi", dir: "5_인도",
    font: "'Noto Sans Devanagari', 'Noto Sans', sans-serif",
    ui: {
      stop: "रोकें", friend: "दोस्त", inputHint: "जो मन करे, बात करें।", translate: "अनुवाद",
      seeWhy: "क्यों अटका, देखें", stuckTitle: "जहाँ अटके", couldSay: "आप ऐसे कह सकते थे", heard: "हमने यह सुना",
      allRecognized: "सभी शब्द सही पहचाने गए।", tryAgain: "फिर से कोशिश करें", close: "बंद करें",
      otherVideos: "दूसरे वीडियो", videoLessons: "वीडियो लर्निंग", merge: "हिस्से जोड़ें", split: "हिस्सा बाँटें",
      loop: "दोहराएँ ×3", keyExpr: "मुख्य अभिव्यक्ति", saved: "सेव हुआ", savedToBook: "शब्दकोश में सेव हुआ",
      sentence: "वाक्य", role: "वाक्य-रचना", usage: "उपयोग", form: "रूप", examples: "और उदाहरण",
      iSpeak: "मेरी भाषा", learning: "सीख रहे हैं", more: "+ 9 और भाषाएँ",
      chatInTarget: "अंग्रेज़ी में बात करें", learnExpr: "अभिव्यक्ति देखें", inputChat: "अंग्रेज़ी में लिखें — अटकें तो हिंदी में भी",
      tabs: ["मैप", "चैट", "कॉल", "वीडियो", "शब्दकोश"],
    },
    native: "हिन्दी", targets: ["English", "Español", "Français", "日本語"],
    heads: [
      ["AI अंग्रेज़ी बातचीत", "AI दोस्त के साथ\nआराम से अंग्रेज़ी बोलें", "तुरंत जवाब, साथ में अनुवाद भी"],
      ["कॉल पर अभ्यास", "अटक गए?\nवजह भी बताता है", "आप क्या कह सकते थे, और उच्चारण की जाँच"],
      ["कोई जल्दी नहीं", "झिझकें तो\nधीरे से दोबारा पूछता है", "जो समझ न आए, हिंदी में समझाता है"],
      ["अंग्रेज़ी बातचीत का अभ्यास", "दोस्त से गपशप की तरह\nअंग्रेज़ी बोलें", "कोई स्क्रिप्ट नहीं, जो कहना है वही कहें"],
      ["14 भाषाएँ", "अपनी भाषा में सीखें,\nपसंद की भाषा में बोलें", "सीखने की भाषा और ऐप की भाषा खुद चुनें"],
      ["वीडियो से सीखें", "असली वीडियो,\nएक-एक वाक्य में", "वाक्य पर टैप करें, सिर्फ़ वही हिस्सा चलेगा"],
      ["वीडियो से सीखें", "दोबारा सुनें, सेव करें,\nअपना बनाएँ", "पसंद का वाक्य दोहराएँ और शब्दकोश में रखें"],
      ["हिंदी में लिखें", "जो कहना है लिखें,\nअंग्रेज़ी में बदल देगा", "हिंदी में लिखें, बातचीत चलती रहेगी"],
      ["शब्द-दर-शब्द", "शब्द पर टैप करें,\nवजह भी जानें", "व्याकरण, उपयोग और उदाहरण हिंदी में"],
    ],
    t: {
      L1: "हाय! आज का दिन कैसा जा रहा है?", L2: "बढ़िया! काम के बाद आपको क्या करना पसंद है?", L3: "वाह! आपको किस तरह की फ़िल्में पसंद हैं?",
      L4: "वाह! आपको किस तरह की किताबें पसंद हैं?", L5: "मुझे फ़ैंटेसी और मिस्ट्री किताबें पसंद हैं।", L6: "आप वीकेंड पर क्या करते हैं?",
      L7: "कोई जल्दी नहीं। “Do you like playing sports?” का मतलब है “क्या आपको खेलना पसंद है?”",
      L8: "बढ़िया! आप कहाँ खेलते हैं?", L9: "हाय! वीकेंड कैसा रहा?", L10: "अच्छा, कौन-सी फ़िल्म देखी?", L11: "बढ़िया! पॉपकॉर्न भी लिया?",
      L12: "यहाँ के नूडल्स ज़रूर खाकर देखो। बहुत स्वादिष्ट हैं।", L13: "मैं आमतौर पर काम से पहले एक कॉफ़ी ले लेता हूँ।", L14: "कॉफ़ी ले लेना",
      L15: "हाय, गुड मॉर्निंग!", L16: "वीकेंड के लिए कोई मज़ेदार प्लान है?",
      L19: "आपने सवाल समझ लिया, पर शैलियों के नाम तुरंत याद नहीं आए, इसलिए आप थोड़ा रुक गए।",
      forMain: "यहाँ “for” बताता है कि प्लान वीकेंड के लिए हैं।",
      forRole: "“plans” के बाद आकर बताता है कि प्लान किस समय के लिए हैं।",
      forUsage: "किसी खास समय या मक़सद के लिए इस्तेमाल होता है।",
      forForm: "इसका रूप नहीं बदलता।",
      ex1: "गर्मियों के लिए आपके क्या प्लान हैं?", ex2: "क्या प्रोजेक्ट के लिए आपके पास कोई आइडिया है?",
    },
  },
};
